/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  EntwurfView,
  KonversationView,
  NachrichtView,
  SendenDto
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Konversationen
 */
export const getKommunikationAdminKonversationen = (

 ) => {
      return http<KonversationView[]>(
      {url: `/kommunikation/admin/konversationen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Entwurf
 */
export const postKommunikationAdminKonversationenIdEntwurf = (
    id: number,
 ) => {
      return http<EntwurfView>(
      {url: `/kommunikation/admin/konversationen/${id}/entwurf`, method: 'POST'
    },
      );
    }
  /**
 * @summary Gelesen
 */
export const postKommunikationAdminKonversationenIdGelesen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/admin/konversationen/${id}/gelesen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Nachrichten
 */
export const getKommunikationAdminKonversationenIdNachrichten = (
    id: number,
 ) => {
      return http<NachrichtView[]>(
      {url: `/kommunikation/admin/konversationen/${id}/nachrichten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Antworten
 */
export const postKommunikationAdminKonversationenIdNachrichten = (
    id: number,
    sendenDto: SendenDto,
 ) => {
      return http<NachrichtView>(
      {url: `/kommunikation/admin/konversationen/${id}/nachrichten`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendenDto
    },
      );
    }
  /**
 * @summary Eroeffne
 */
export const postKommunikationAdminVorgaenge = (
    sendenDto: SendenDto,
 ) => {
      return http<KonversationView>(
      {url: `/kommunikation/admin/vorgaenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendenDto
    },
      );
    }
  export type GetKommunikationAdminKonversationenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationAdminKonversationen>>>
export type PostKommunikationAdminKonversationenIdEntwurfResult = NonNullable<Awaited<ReturnType<typeof postKommunikationAdminKonversationenIdEntwurf>>>
export type PostKommunikationAdminKonversationenIdGelesenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationAdminKonversationenIdGelesen>>>
export type GetKommunikationAdminKonversationenIdNachrichtenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationAdminKonversationenIdNachrichten>>>
export type PostKommunikationAdminKonversationenIdNachrichtenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationAdminKonversationenIdNachrichten>>>
export type PostKommunikationAdminVorgaengeResult = NonNullable<Awaited<ReturnType<typeof postKommunikationAdminVorgaenge>>>
