/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  Anforderung,
  EinschreibungDto,
  WbtBestellung
} from '../../model';

import { http } from '../../http';



  /**
 * @summary List
 */
export const getLmsEinschreibungen = (

 ) => {
      return http<EinschreibungDto[]>(
      {url: `/lms/einschreibungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Anfordern
 */
export const postLmsEinschreibungen = (
    anforderung: Anforderung,
 ) => {
      return http<unknown>(
      {url: `/lms/einschreibungen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: anforderung
    },
      );
    }
  /**
 * @summary Aus Bestellung
 */
export const postLmsEinschreibungenBestellung = (
    wbtBestellung: WbtBestellung,
 ) => {
      return http<unknown>(
      {url: `/lms/einschreibungen/bestellung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wbtBestellung
    },
      );
    }
  /**
 * @summary Storno Bestellung
 */
export const postLmsEinschreibungenBestellungVendureOrderIdStorno = (
    vendureOrderId: string,
 ) => {
      return http<EinschreibungDto[]>(
      {url: `/lms/einschreibungen/bestellung/${vendureOrderId}/storno`, method: 'POST'
    },
      );
    }
  /**
 * @summary Ausschreiben
 */
export const postLmsEinschreibungenIdAusschreiben = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/lms/einschreibungen/${id}/ausschreiben`, method: 'POST'
    },
      );
    }
  /**
 * @summary Neu Versuch
 */
export const postLmsEinschreibungenIdNeuVersuch = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/lms/einschreibungen/${id}/neu-versuch`, method: 'POST'
    },
      );
    }
  export type GetLmsEinschreibungenResult = NonNullable<Awaited<ReturnType<typeof getLmsEinschreibungen>>>
export type PostLmsEinschreibungenResult = NonNullable<Awaited<ReturnType<typeof postLmsEinschreibungen>>>
export type PostLmsEinschreibungenBestellungResult = NonNullable<Awaited<ReturnType<typeof postLmsEinschreibungenBestellung>>>
export type PostLmsEinschreibungenBestellungVendureOrderIdStornoResult = NonNullable<Awaited<ReturnType<typeof postLmsEinschreibungenBestellungVendureOrderIdStorno>>>
export type PostLmsEinschreibungenIdAusschreibenResult = NonNullable<Awaited<ReturnType<typeof postLmsEinschreibungenIdAusschreiben>>>
export type PostLmsEinschreibungenIdNeuVersuchResult = NonNullable<Awaited<ReturnType<typeof postLmsEinschreibungenIdNeuVersuch>>>
