/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Offene
 */
export const GetPartyAnmeldungenQueryParams = zod.object({
  "status": zod.enum(['ANGEFRAGT', 'BESTAETIGT_EBZ', 'AKTIV', 'ABGEBROCHEN', 'ABGESCHLOSSEN']).optional()
})

export const GetPartyAnmeldungenResponseItem = zod.object({
  "anmeldungId": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "zahlungspflichtigerDebitorId": zod.number().optional(),
  "schuljahr": zod.string().optional(),
  "halbjahr": zod.number().optional(),
  "status": zod.string().optional()
})
export const GetPartyAnmeldungenResponse = zod.array(GetPartyAnmeldungenResponseItem)

/**
 * @summary Bestaetigen
 */
export const PostPartyAnmeldungenIdBestaetigungParams = zod.object({
  "id": zod.number()
})

export const PostPartyAnmeldungenIdBestaetigungResponse = zod.object({
  "anmeldungId": zod.number().optional(),
  "status": zod.string().optional(),
  "teilnehmerName": zod.string().optional(),
  "kontextOrganisationId": zod.number().optional()
})

