/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetPartyPortalRechnungenParams,
  PortalRechnungView,
  RechnungsKontextView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Meine Rechnungen
 */
export const getPartyPortalRechnungen = (
    params?: GetPartyPortalRechnungenParams,
 ) => {
      return http<PortalRechnungView[]>(
      {url: `/party/portal/rechnungen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Zugferd
 */
export const getPartyPortalRechnungenIdZugferd = (
    id: number,
 ) => {
      return http<Blob>(
      {url: `/party/portal/rechnungen/${id}/zugferd`, method: 'GET',
        responseType: 'blob'
    },
      );
    }
  /**
 * @summary Rechnungs Kontexte
 */
export const getPartyPortalRechnungsKontexte = (

 ) => {
      return http<RechnungsKontextView[]>(
      {url: `/party/portal/rechnungs-kontexte`, method: 'GET'
    },
      );
    }
  export type GetPartyPortalRechnungenResult = NonNullable<Awaited<ReturnType<typeof getPartyPortalRechnungen>>>
export type GetPartyPortalRechnungenIdZugferdResult = NonNullable<Awaited<ReturnType<typeof getPartyPortalRechnungenIdZugferd>>>
export type GetPartyPortalRechnungsKontexteResult = NonNullable<Awaited<ReturnType<typeof getPartyPortalRechnungsKontexte>>>
