/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List
 */
export const GetLmsEinschreibungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "wbtKursId": zod.number().optional(),
  "kursTitel": zod.string().optional(),
  "keycloakSub": zod.string().optional(),
  "email": zod.string().optional(),
  "status": zod.enum(['ANGEFORDERT', 'EINGESCHRIEBEN', 'FEHLGESCHLAGEN', 'STORNO_ANGEFORDERT', 'AUSGESCHRIEBEN']).optional(),
  "openolatIdentityKey": zod.number().optional(),
  "versuche": zod.number().optional(),
  "letzterFehler": zod.string().optional()
})
export const GetLmsEinschreibungenResponse = zod.array(GetLmsEinschreibungenResponseItem)

/**
 * @summary Anfordern
 */
export const postLmsEinschreibungenBodyKeycloakSubRegExp = new RegExp('\\S');



export const PostLmsEinschreibungenBody = zod.object({
  "keycloakSub": zod.string().regex(postLmsEinschreibungenBodyKeycloakSubRegExp),
  "email": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "vendureOrderId": zod.string().optional(),
  "wbtKursIds": zod.array(zod.number()).min(1)
})

export const PostLmsEinschreibungenResponse = zod.unknown()

/**
 * @summary Aus Bestellung
 */
export const postLmsEinschreibungenBestellungBodyVendureOrderIdRegExp = new RegExp('\\S');
export const postLmsEinschreibungenBestellungBodyKeycloakSubRegExp = new RegExp('\\S');



export const PostLmsEinschreibungenBestellungBody = zod.object({
  "vendureOrderId": zod.string().regex(postLmsEinschreibungenBestellungBodyVendureOrderIdRegExp),
  "keycloakSub": zod.string().regex(postLmsEinschreibungenBestellungBodyKeycloakSubRegExp),
  "email": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "vendureProductIds": zod.array(zod.string()).min(1)
})

export const PostLmsEinschreibungenBestellungResponse = zod.unknown()

/**
 * @summary Storno Bestellung
 */
export const PostLmsEinschreibungenBestellungVendureOrderIdStornoParams = zod.object({
  "vendureOrderId": zod.string()
})

export const PostLmsEinschreibungenBestellungVendureOrderIdStornoResponseItem = zod.object({
  "id": zod.number().optional(),
  "wbtKursId": zod.number().optional(),
  "kursTitel": zod.string().optional(),
  "keycloakSub": zod.string().optional(),
  "email": zod.string().optional(),
  "status": zod.enum(['ANGEFORDERT', 'EINGESCHRIEBEN', 'FEHLGESCHLAGEN', 'STORNO_ANGEFORDERT', 'AUSGESCHRIEBEN']).optional(),
  "openolatIdentityKey": zod.number().optional(),
  "versuche": zod.number().optional(),
  "letzterFehler": zod.string().optional()
})
export const PostLmsEinschreibungenBestellungVendureOrderIdStornoResponse = zod.array(PostLmsEinschreibungenBestellungVendureOrderIdStornoResponseItem)

/**
 * @summary Ausschreiben
 */
export const PostLmsEinschreibungenIdAusschreibenParams = zod.object({
  "id": zod.number()
})

export const PostLmsEinschreibungenIdAusschreibenResponse = zod.unknown()

/**
 * @summary Neu Versuch
 */
export const PostLmsEinschreibungenIdNeuVersuchParams = zod.object({
  "id": zod.number()
})

export const PostLmsEinschreibungenIdNeuVersuchResponse = zod.unknown()

