/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AuftragDto,
  PostHubspotSyncBackfill200,
  PostHubspotSyncCompaniesOrganisationId200,
  PostHubspotSyncConsentPersonId200,
  PostHubspotSyncContactsPersonId200,
  PostHubspotSyncErasurePersonId200,
  PostHubspotSyncRetryAuftragId200,
  PostHubspotSyncRun200
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Auftraege
 */
export const getHubspotSyncAuftraege = (

 ) => {
      return http<AuftragDto[]>(
      {url: `/hubspot/sync/auftraege`, method: 'GET'
    },
      );
    }
  /**
 * @summary Backfill
 */
export const postHubspotSyncBackfill = (

 ) => {
      return http<PostHubspotSyncBackfill200>(
      {url: `/hubspot/sync/backfill`, method: 'POST'
    },
      );
    }
  /**
 * @summary Company
 */
export const postHubspotSyncCompaniesOrganisationId = (
    organisationId: number,
 ) => {
      return http<PostHubspotSyncCompaniesOrganisationId200>(
      {url: `/hubspot/sync/companies/${organisationId}`, method: 'POST'
    },
      );
    }
  /**
 * @summary Consent
 */
export const postHubspotSyncConsentPersonId = (
    personId: number,
 ) => {
      return http<PostHubspotSyncConsentPersonId200>(
      {url: `/hubspot/sync/consent/${personId}`, method: 'POST'
    },
      );
    }
  /**
 * @summary Contact
 */
export const postHubspotSyncContactsPersonId = (
    personId: number,
 ) => {
      return http<PostHubspotSyncContactsPersonId200>(
      {url: `/hubspot/sync/contacts/${personId}`, method: 'POST'
    },
      );
    }
  /**
 * @summary Erasure
 */
export const postHubspotSyncErasurePersonId = (
    personId: number,
 ) => {
      return http<PostHubspotSyncErasurePersonId200>(
      {url: `/hubspot/sync/erasure/${personId}`, method: 'POST'
    },
      );
    }
  /**
 * @summary Retry
 */
export const postHubspotSyncRetryAuftragId = (
    auftragId: number,
 ) => {
      return http<PostHubspotSyncRetryAuftragId200>(
      {url: `/hubspot/sync/retry/${auftragId}`, method: 'POST'
    },
      );
    }
  /**
 * @summary Run
 */
export const postHubspotSyncRun = (

 ) => {
      return http<PostHubspotSyncRun200>(
      {url: `/hubspot/sync/run`, method: 'POST'
    },
      );
    }
  export type GetHubspotSyncAuftraegeResult = NonNullable<Awaited<ReturnType<typeof getHubspotSyncAuftraege>>>
export type PostHubspotSyncBackfillResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncBackfill>>>
export type PostHubspotSyncCompaniesOrganisationIdResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncCompaniesOrganisationId>>>
export type PostHubspotSyncConsentPersonIdResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncConsentPersonId>>>
export type PostHubspotSyncContactsPersonIdResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncContactsPersonId>>>
export type PostHubspotSyncErasurePersonIdResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncErasurePersonId>>>
export type PostHubspotSyncRetryAuftragIdResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncRetryAuftragId>>>
export type PostHubspotSyncRunResult = NonNullable<Awaited<ReturnType<typeof postHubspotSyncRun>>>
