/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  Konto,
  PostMockSuite8VerfuegbarkeitParams
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Konten
 */
export const getMockSuite8Konten = (

 ) => {
      return http<Konto[]>(
      {url: `/mock/suite8/konten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Status
 */
export const getMockSuite8Status = (

 ) => {
      return http<unknown>(
      {url: `/mock/suite8/status`, method: 'GET'
    },
      );
    }
  /**
 * @summary Verfuegbarkeit
 */
export const postMockSuite8Verfuegbarkeit = (
    params?: PostMockSuite8VerfuegbarkeitParams,
 ) => {
      return http<unknown>(
      {url: `/mock/suite8/verfuegbarkeit`, method: 'POST',
        params
    },
      );
    }
  export type GetMockSuite8KontenResult = NonNullable<Awaited<ReturnType<typeof getMockSuite8Konten>>>
export type GetMockSuite8StatusResult = NonNullable<Awaited<ReturnType<typeof getMockSuite8Status>>>
export type PostMockSuite8VerfuegbarkeitResult = NonNullable<Awaited<ReturnType<typeof postMockSuite8Verfuegbarkeit>>>
