/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Konten
 */
export const GetMockSuite8KontenResponseItem = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "bezahlkartenNr": zod.string().optional(),
  "angelegtAm": zod.string().datetime({"offset":true}).optional()
})
export const GetMockSuite8KontenResponse = zod.array(GetMockSuite8KontenResponseItem)

/**
 * @summary Status
 */
export const GetMockSuite8StatusResponse = zod.unknown()

/**
 * @summary Verfuegbarkeit
 */
export const PostMockSuite8VerfuegbarkeitQueryParams = zod.object({
  "verfuegbar": zod.boolean().optional()
})

export const PostMockSuite8VerfuegbarkeitResponse = zod.unknown()

