/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Vertrag Bestaetigen
 */
export const PostPartyPortalAnmeldungenIdVertragBestaetigenParams = zod.object({
  "id": zod.number()
})

export const PostPartyPortalAnmeldungenIdVertragBestaetigenResponse = zod.unknown()

/**
 * @summary Azubi Anmelden
 */
export const postPartyPortalAzubiAnmeldungBodyAzubiEmailRegExp = new RegExp('\\S');
export const postPartyPortalAzubiAnmeldungBodyAzubiNameRegExp = new RegExp('\\S');
export const postPartyPortalAzubiAnmeldungBodySchuljahrRegExp = new RegExp('\\S');


export const PostPartyPortalAzubiAnmeldungBody = zod.object({
  "organisationId": zod.number(),
  "azubiEmail": zod.string().regex(postPartyPortalAzubiAnmeldungBodyAzubiEmailRegExp),
  "azubiName": zod.string().regex(postPartyPortalAzubiAnmeldungBodyAzubiNameRegExp),
  "schuljahr": zod.string().regex(postPartyPortalAzubiAnmeldungBodySchuljahrRegExp),
  "halbjahr": zod.number().optional(),
  "zimmerart": zod.enum(['KEINE', 'DOPPEL', 'EINZEL']),
  "unterrichtBetragCent": zod.number().optional(),
  "uebernachtungBetragCent": zod.number().optional()
})

export const PostPartyPortalAzubiAnmeldungResponse = zod.unknown()

