/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  EntscheidungDto,
  Fall,
  ReviewView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Entscheide
 */
export const postPartyReviewsEntscheidung = (
    entscheidungDto: EntscheidungDto,
 ) => {
      return http<ReviewView>(
      {url: `/party/reviews/entscheidung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: entscheidungDto
    },
      );
    }
  /**
 * @summary Queue
 */
export const getPartyReviewsQueue = (

 ) => {
      return http<Fall[]>(
      {url: `/party/reviews/queue`, method: 'GET'
    },
      );
    }
  export type PostPartyReviewsEntscheidungResult = NonNullable<Awaited<ReturnType<typeof postPartyReviewsEntscheidung>>>
export type GetPartyReviewsQueueResult = NonNullable<Awaited<ReturnType<typeof getPartyReviewsQueue>>>
