/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Beratung
 */
export const PostKommunikationPortalBeratungBody = zod.object({
  "frage": zod.string().optional()
})

export const PostKommunikationPortalBeratungResponse = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "betreff": zod.string().optional(),
  "status": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "partner": zod.string().optional(),
  "letzteVorschau": zod.string().optional(),
  "letzteZeit": zod.string().datetime({"offset":true}).optional(),
  "ungelesen": zod.boolean().optional()
})

/**
 * @summary Offene Bestaetigungen
 */
export const GetKommunikationPortalBestaetigungenOffenResponseItem = zod.object({
  "id": zod.number().optional(),
  "ereignisTyp": zod.string().optional(),
  "kategorie": zod.string().optional(),
  "betreff": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "gelesen": zod.boolean().optional(),
  "bestaetigungErforderlich": zod.boolean().optional(),
  "bestaetigtAm": zod.string().datetime({"offset":true}).optional(),
  "bestaetigenBis": zod.string().datetime({"offset":true}).optional(),
  "status": zod.string().optional()
})
export const GetKommunikationPortalBestaetigungenOffenResponse = zod.array(GetKommunikationPortalBestaetigungenOffenResponseItem)

/**
 * @summary Direkt
 */
export const PostKommunikationPortalDirektBody = zod.object({
  "personId": zod.number().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional()
})

export const PostKommunikationPortalDirektResponse = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "betreff": zod.string().optional(),
  "status": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "partner": zod.string().optional(),
  "letzteVorschau": zod.string().optional(),
  "letzteZeit": zod.string().datetime({"offset":true}).optional(),
  "ungelesen": zod.boolean().optional()
})

/**
 * @summary Setze Einstellungen
 */
export const PutKommunikationPortalEinstellungenBody = zod.object({
  "digest": zod.boolean().optional(),
  "quietVon": zod.string().optional(),
  "quietBis": zod.string().optional(),
  "maxProStunde": zod.number().optional()
})

export const PutKommunikationPortalEinstellungenResponse = zod.unknown()

/**
 * @summary Einstellungen
 */
export const GetKommunikationPortalEinstellungenResponse = zod.object({
  "digest": zod.boolean().optional(),
  "quietVon": zod.string().optional(),
  "quietBis": zod.string().optional(),
  "maxProStunde": zod.number().optional()
})

/**
 * @summary Ereignisse
 */
export const GetKommunikationPortalEreignisseResponseItem = zod.object({
  "id": zod.number().optional(),
  "ereignisTyp": zod.string().optional(),
  "kategorie": zod.string().optional(),
  "betreff": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "gelesen": zod.boolean().optional(),
  "bestaetigungErforderlich": zod.boolean().optional(),
  "bestaetigtAm": zod.string().datetime({"offset":true}).optional(),
  "bestaetigenBis": zod.string().datetime({"offset":true}).optional(),
  "status": zod.string().optional()
})
export const GetKommunikationPortalEreignisseResponse = zod.array(GetKommunikationPortalEreignisseResponseItem)

/**
 * @summary Bestaetigen
 */
export const PostKommunikationPortalEreignisseIdBestaetigenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationPortalEreignisseIdBestaetigenResponse = zod.unknown()

/**
 * @summary Gelesen
 */
export const PostKommunikationPortalEreignisseIdGelesenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationPortalEreignisseIdGelesenResponse = zod.unknown()

/**
 * @summary Konversationen
 */
export const GetKommunikationPortalKonversationenResponseItem = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "betreff": zod.string().optional(),
  "status": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "partner": zod.string().optional(),
  "letzteVorschau": zod.string().optional(),
  "letzteZeit": zod.string().datetime({"offset":true}).optional(),
  "ungelesen": zod.boolean().optional()
})
export const GetKommunikationPortalKonversationenResponse = zod.array(GetKommunikationPortalKonversationenResponseItem)

/**
 * @summary Konversationen Ungelesen
 */
export const GetKommunikationPortalKonversationenUngelesenResponse = zod.object({
  "anzahl": zod.number().optional()
})

/**
 * @summary Konversation Gelesen
 */
export const PostKommunikationPortalKonversationenIdGelesenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationPortalKonversationenIdGelesenResponse = zod.unknown()

/**
 * @summary Nachrichten
 */
export const GetKommunikationPortalKonversationenIdNachrichtenParams = zod.object({
  "id": zod.number()
})

export const GetKommunikationPortalKonversationenIdNachrichtenResponseItem = zod.object({
  "id": zod.number().optional(),
  "absenderTyp": zod.string().optional(),
  "absender": zod.string().optional(),
  "kiGeneriert": zod.boolean().optional(),
  "inhaltHtml": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional()
})
export const GetKommunikationPortalKonversationenIdNachrichtenResponse = zod.array(GetKommunikationPortalKonversationenIdNachrichtenResponseItem)

/**
 * @summary Antworten
 */
export const PostKommunikationPortalKonversationenIdNachrichtenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationPortalKonversationenIdNachrichtenBody = zod.object({
  "personId": zod.number().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional()
})

export const PostKommunikationPortalKonversationenIdNachrichtenResponse = zod.object({
  "id": zod.number().optional(),
  "absenderTyp": zod.string().optional(),
  "absender": zod.string().optional(),
  "kiGeneriert": zod.boolean().optional(),
  "inhaltHtml": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Praeferenzen
 */
export const GetKommunikationPortalPraeferenzenResponseItem = zod.object({
  "kanal": zod.string().optional(),
  "kategorie": zod.string().optional(),
  "aktiv": zod.boolean().optional()
})
export const GetKommunikationPortalPraeferenzenResponse = zod.array(GetKommunikationPortalPraeferenzenResponseItem)

/**
 * @summary Setze Praeferenz
 */
export const PutKommunikationPortalPraeferenzenKanalParams = zod.object({
  "kanal": zod.enum(['PORTAL', 'EMAIL', 'SMS'])
})

export const PutKommunikationPortalPraeferenzenKanalQueryParams = zod.object({
  "kategorie": zod.enum(['ANMELDUNG', 'RECHNUNG', 'EINSCHREIBUNG', 'PRUEFUNG', 'SYSTEM', 'INTERN']).optional()
})

export const PutKommunikationPortalPraeferenzenKanalBody = zod.object({
  "aktiv": zod.boolean().optional()
})

export const PutKommunikationPortalPraeferenzenKanalResponse = zod.unknown()

/**
 * @summary Ungelesen
 */
export const GetKommunikationPortalUngelesenResponse = zod.object({
  "anzahl": zod.number().optional()
})

