/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AnmeldungStatusView,
  GetPartyAnmeldungenParams,
  OffeneAnmeldungView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Offene
 */
export const getPartyAnmeldungen = (
    params?: GetPartyAnmeldungenParams,
 ) => {
      return http<OffeneAnmeldungView[]>(
      {url: `/party/anmeldungen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Bestaetigen
 */
export const postPartyAnmeldungenIdBestaetigung = (
    id: number,
 ) => {
      return http<AnmeldungStatusView>(
      {url: `/party/anmeldungen/${id}/bestaetigung`, method: 'POST'
    },
      );
    }
  export type GetPartyAnmeldungenResult = NonNullable<Awaited<ReturnType<typeof getPartyAnmeldungen>>>
export type PostPartyAnmeldungenIdBestaetigungResult = NonNullable<Awaited<ReturnType<typeof postPartyAnmeldungenIdBestaetigung>>>
