/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Registry
 */
export const GetBildungAngeboteResponseItem = zod.object({
  "id": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().optional(),
  "titel": zod.string().optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().optional()
})
export const GetBildungAngeboteResponse = zod.array(GetBildungAngeboteResponseItem)

/**
 * @summary Projiziere In Shop
 */
export const PostBildungAngeboteIdShopProjektionParams = zod.object({
  "id": zod.number()
})

export const PostBildungAngeboteIdShopProjektionResponse = zod.object({
  "id": zod.number().optional(),
  "code": zod.string().optional(),
  "vendureProductId": zod.string().optional(),
  "vendureVariantId": zod.string().optional()
})

/**
 * @summary List Berufsschuljahre
 */
export const getBildungBerufsschuljahreResponseCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getBildungBerufsschuljahreResponseTitelMax = 200;


export const getBildungBerufsschuljahreResponseTitelRegExp = new RegExp('\\S');
export const getBildungBerufsschuljahreResponseKurzbeschreibungMax = 2000;

export const getBildungBerufsschuljahreResponseVerantwortlichMax = 120;

export const getBildungBerufsschuljahreResponsePreisCentMin = 0;


export const getBildungBerufsschuljahreResponseRatenGesamtMin = 0;

export const getBildungBerufsschuljahreResponseVendureProductIdMax = 64;

export const getBildungBerufsschuljahreResponseZielgruppeMax = 200;

export const getBildungBerufsschuljahreResponseFachrichtungMax = 200;


export const getBildungBerufsschuljahreResponseFachrichtungRegExp = new RegExp('\\S');
export const getBildungBerufsschuljahreResponseSchuljahrRegExp = new RegExp('^\\d{4}/\\d{2}$');

export const getBildungBerufsschuljahreResponseSchildNrwSchluesselMax = 32;

export const getBildungBerufsschuljahreResponsePlaetzeMin = 0;



export const GetBildungBerufsschuljahreResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(getBildungBerufsschuljahreResponseCodeRegExp),
  "titel": zod.string().max(getBildungBerufsschuljahreResponseTitelMax).regex(getBildungBerufsschuljahreResponseTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(getBildungBerufsschuljahreResponseKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(getBildungBerufsschuljahreResponseVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(getBildungBerufsschuljahreResponsePreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(getBildungBerufsschuljahreResponseRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(getBildungBerufsschuljahreResponseVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(getBildungBerufsschuljahreResponseZielgruppeMax).optional(),
  "fachrichtung": zod.string().max(getBildungBerufsschuljahreResponseFachrichtungMax).regex(getBildungBerufsschuljahreResponseFachrichtungRegExp),
  "schuljahr": zod.string().regex(getBildungBerufsschuljahreResponseSchuljahrRegExp),
  "jahrgang": zod.number().min(1).optional(),
  "beginn": zod.string().date().optional(),
  "schildNrwSchluessel": zod.string().max(getBildungBerufsschuljahreResponseSchildNrwSchluesselMax).optional(),
  "plaetze": zod.number().min(getBildungBerufsschuljahreResponsePlaetzeMin).optional()
})
export const GetBildungBerufsschuljahreResponse = zod.array(GetBildungBerufsschuljahreResponseItem)

/**
 * @summary Create Berufsschuljahr
 */
export const postBildungBerufsschuljahreBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postBildungBerufsschuljahreBodyTitelMax = 200;


export const postBildungBerufsschuljahreBodyTitelRegExp = new RegExp('\\S');
export const postBildungBerufsschuljahreBodyKurzbeschreibungMax = 2000;

export const postBildungBerufsschuljahreBodyVerantwortlichMax = 120;

export const postBildungBerufsschuljahreBodyPreisCentMin = 0;


export const postBildungBerufsschuljahreBodyRatenGesamtMin = 0;

export const postBildungBerufsschuljahreBodyVendureProductIdMax = 64;

export const postBildungBerufsschuljahreBodyZielgruppeMax = 200;

export const postBildungBerufsschuljahreBodyFachrichtungMax = 200;


export const postBildungBerufsschuljahreBodyFachrichtungRegExp = new RegExp('\\S');
export const postBildungBerufsschuljahreBodySchuljahrRegExp = new RegExp('^\\d{4}/\\d{2}$');

export const postBildungBerufsschuljahreBodySchildNrwSchluesselMax = 32;

export const postBildungBerufsschuljahreBodyPlaetzeMin = 0;



export const PostBildungBerufsschuljahreBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(postBildungBerufsschuljahreBodyCodeRegExp),
  "titel": zod.string().max(postBildungBerufsschuljahreBodyTitelMax).regex(postBildungBerufsschuljahreBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(postBildungBerufsschuljahreBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(postBildungBerufsschuljahreBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(postBildungBerufsschuljahreBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(postBildungBerufsschuljahreBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(postBildungBerufsschuljahreBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(postBildungBerufsschuljahreBodyZielgruppeMax).optional(),
  "fachrichtung": zod.string().max(postBildungBerufsschuljahreBodyFachrichtungMax).regex(postBildungBerufsschuljahreBodyFachrichtungRegExp),
  "schuljahr": zod.string().regex(postBildungBerufsschuljahreBodySchuljahrRegExp),
  "jahrgang": zod.number().min(1).optional(),
  "beginn": zod.string().date().optional(),
  "schildNrwSchluessel": zod.string().max(postBildungBerufsschuljahreBodySchildNrwSchluesselMax).optional(),
  "plaetze": zod.number().min(postBildungBerufsschuljahreBodyPlaetzeMin).optional()
})

export const PostBildungBerufsschuljahreResponse = zod.unknown()

/**
 * @summary Update Berufsschuljahr
 */
export const PutBildungBerufsschuljahreIdParams = zod.object({
  "id": zod.number()
})

export const putBildungBerufsschuljahreIdBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putBildungBerufsschuljahreIdBodyTitelMax = 200;


export const putBildungBerufsschuljahreIdBodyTitelRegExp = new RegExp('\\S');
export const putBildungBerufsschuljahreIdBodyKurzbeschreibungMax = 2000;

export const putBildungBerufsschuljahreIdBodyVerantwortlichMax = 120;

export const putBildungBerufsschuljahreIdBodyPreisCentMin = 0;


export const putBildungBerufsschuljahreIdBodyRatenGesamtMin = 0;

export const putBildungBerufsschuljahreIdBodyVendureProductIdMax = 64;

export const putBildungBerufsschuljahreIdBodyZielgruppeMax = 200;

export const putBildungBerufsschuljahreIdBodyFachrichtungMax = 200;


export const putBildungBerufsschuljahreIdBodyFachrichtungRegExp = new RegExp('\\S');
export const putBildungBerufsschuljahreIdBodySchuljahrRegExp = new RegExp('^\\d{4}/\\d{2}$');

export const putBildungBerufsschuljahreIdBodySchildNrwSchluesselMax = 32;

export const putBildungBerufsschuljahreIdBodyPlaetzeMin = 0;



export const PutBildungBerufsschuljahreIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(putBildungBerufsschuljahreIdBodyCodeRegExp),
  "titel": zod.string().max(putBildungBerufsschuljahreIdBodyTitelMax).regex(putBildungBerufsschuljahreIdBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(putBildungBerufsschuljahreIdBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(putBildungBerufsschuljahreIdBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(putBildungBerufsschuljahreIdBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(putBildungBerufsschuljahreIdBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(putBildungBerufsschuljahreIdBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(putBildungBerufsschuljahreIdBodyZielgruppeMax).optional(),
  "fachrichtung": zod.string().max(putBildungBerufsschuljahreIdBodyFachrichtungMax).regex(putBildungBerufsschuljahreIdBodyFachrichtungRegExp),
  "schuljahr": zod.string().regex(putBildungBerufsschuljahreIdBodySchuljahrRegExp),
  "jahrgang": zod.number().min(1).optional(),
  "beginn": zod.string().date().optional(),
  "schildNrwSchluessel": zod.string().max(putBildungBerufsschuljahreIdBodySchildNrwSchluesselMax).optional(),
  "plaetze": zod.number().min(putBildungBerufsschuljahreIdBodyPlaetzeMin).optional()
})

export const PutBildungBerufsschuljahreIdResponse = zod.unknown()

/**
 * @summary Get Berufsschuljahr
 */
export const GetBildungBerufsschuljahreIdParams = zod.object({
  "id": zod.number()
})

export const GetBildungBerufsschuljahreIdResponse = zod.unknown()

/**
 * @summary Archive Berufsschuljahr
 */
export const DeleteBildungBerufsschuljahreIdParams = zod.object({
  "id": zod.number()
})

export const DeleteBildungBerufsschuljahreIdResponse = zod.unknown()

/**
 * @summary List Seminare
 */
export const getBildungSeminareResponseCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getBildungSeminareResponseTitelMax = 200;


export const getBildungSeminareResponseTitelRegExp = new RegExp('\\S');
export const getBildungSeminareResponseKurzbeschreibungMax = 2000;

export const getBildungSeminareResponseVerantwortlichMax = 120;

export const getBildungSeminareResponsePreisCentMin = 0;


export const getBildungSeminareResponseRatenGesamtMin = 0;

export const getBildungSeminareResponseVendureProductIdMax = 64;

export const getBildungSeminareResponseZielgruppeMax = 200;


export const getBildungSeminareResponseAbschlussMax = 120;

export const getBildungSeminareResponseMinTNMin = 0;




export const GetBildungSeminareResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(getBildungSeminareResponseCodeRegExp),
  "titel": zod.string().max(getBildungSeminareResponseTitelMax).regex(getBildungSeminareResponseTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(getBildungSeminareResponseKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(getBildungSeminareResponseVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(getBildungSeminareResponsePreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(getBildungSeminareResponseRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(getBildungSeminareResponseVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(getBildungSeminareResponseZielgruppeMax).optional(),
  "kategorie": zod.enum(['FUEHRUNG', 'FACHKOMPETENZ', 'COMPLIANCE', 'IT_DIGITAL', 'SPRACHEN', 'SONSTIGE']),
  "dauerUE": zod.number().min(1).optional(),
  "abschluss": zod.string().max(getBildungSeminareResponseAbschlussMax).optional(),
  "zertifikat": zod.boolean().optional(),
  "minTN": zod.number().min(getBildungSeminareResponseMinTNMin).optional(),
  "maxTN": zod.number().min(1).optional()
})
export const GetBildungSeminareResponse = zod.array(GetBildungSeminareResponseItem)

/**
 * @summary Create Seminar
 */
export const postBildungSeminareBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postBildungSeminareBodyTitelMax = 200;


export const postBildungSeminareBodyTitelRegExp = new RegExp('\\S');
export const postBildungSeminareBodyKurzbeschreibungMax = 2000;

export const postBildungSeminareBodyVerantwortlichMax = 120;

export const postBildungSeminareBodyPreisCentMin = 0;


export const postBildungSeminareBodyRatenGesamtMin = 0;

export const postBildungSeminareBodyVendureProductIdMax = 64;

export const postBildungSeminareBodyZielgruppeMax = 200;


export const postBildungSeminareBodyAbschlussMax = 120;

export const postBildungSeminareBodyMinTNMin = 0;




export const PostBildungSeminareBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(postBildungSeminareBodyCodeRegExp),
  "titel": zod.string().max(postBildungSeminareBodyTitelMax).regex(postBildungSeminareBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(postBildungSeminareBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(postBildungSeminareBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(postBildungSeminareBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(postBildungSeminareBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(postBildungSeminareBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(postBildungSeminareBodyZielgruppeMax).optional(),
  "kategorie": zod.enum(['FUEHRUNG', 'FACHKOMPETENZ', 'COMPLIANCE', 'IT_DIGITAL', 'SPRACHEN', 'SONSTIGE']),
  "dauerUE": zod.number().min(1).optional(),
  "abschluss": zod.string().max(postBildungSeminareBodyAbschlussMax).optional(),
  "zertifikat": zod.boolean().optional(),
  "minTN": zod.number().min(postBildungSeminareBodyMinTNMin).optional(),
  "maxTN": zod.number().min(1).optional()
})

export const PostBildungSeminareResponse = zod.unknown()

/**
 * @summary Update Seminar
 */
export const PutBildungSeminareIdParams = zod.object({
  "id": zod.number()
})

export const putBildungSeminareIdBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putBildungSeminareIdBodyTitelMax = 200;


export const putBildungSeminareIdBodyTitelRegExp = new RegExp('\\S');
export const putBildungSeminareIdBodyKurzbeschreibungMax = 2000;

export const putBildungSeminareIdBodyVerantwortlichMax = 120;

export const putBildungSeminareIdBodyPreisCentMin = 0;


export const putBildungSeminareIdBodyRatenGesamtMin = 0;

export const putBildungSeminareIdBodyVendureProductIdMax = 64;

export const putBildungSeminareIdBodyZielgruppeMax = 200;


export const putBildungSeminareIdBodyAbschlussMax = 120;

export const putBildungSeminareIdBodyMinTNMin = 0;




export const PutBildungSeminareIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(putBildungSeminareIdBodyCodeRegExp),
  "titel": zod.string().max(putBildungSeminareIdBodyTitelMax).regex(putBildungSeminareIdBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(putBildungSeminareIdBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(putBildungSeminareIdBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(putBildungSeminareIdBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(putBildungSeminareIdBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(putBildungSeminareIdBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(putBildungSeminareIdBodyZielgruppeMax).optional(),
  "kategorie": zod.enum(['FUEHRUNG', 'FACHKOMPETENZ', 'COMPLIANCE', 'IT_DIGITAL', 'SPRACHEN', 'SONSTIGE']),
  "dauerUE": zod.number().min(1).optional(),
  "abschluss": zod.string().max(putBildungSeminareIdBodyAbschlussMax).optional(),
  "zertifikat": zod.boolean().optional(),
  "minTN": zod.number().min(putBildungSeminareIdBodyMinTNMin).optional(),
  "maxTN": zod.number().min(1).optional()
})

export const PutBildungSeminareIdResponse = zod.unknown()

/**
 * @summary Get Seminar
 */
export const GetBildungSeminareIdParams = zod.object({
  "id": zod.number()
})

export const GetBildungSeminareIdResponse = zod.unknown()

/**
 * @summary Archive Seminar
 */
export const DeleteBildungSeminareIdParams = zod.object({
  "id": zod.number()
})

export const DeleteBildungSeminareIdResponse = zod.unknown()

/**
 * @summary List Studiengaenge
 */
export const getBildungStudiengaengeResponseCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getBildungStudiengaengeResponseTitelMax = 200;


export const getBildungStudiengaengeResponseTitelRegExp = new RegExp('\\S');
export const getBildungStudiengaengeResponseKurzbeschreibungMax = 2000;

export const getBildungStudiengaengeResponseVerantwortlichMax = 120;

export const getBildungStudiengaengeResponsePreisCentMin = 0;


export const getBildungStudiengaengeResponseRatenGesamtMin = 0;

export const getBildungStudiengaengeResponseVendureProductIdMax = 64;

export const getBildungStudiengaengeResponseZielgruppeMax = 200;

export const getBildungStudiengaengeResponseStartsemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');

export const getBildungStudiengaengeResponsePlaetzeMin = 0;



export const GetBildungStudiengaengeResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(getBildungStudiengaengeResponseCodeRegExp),
  "titel": zod.string().max(getBildungStudiengaengeResponseTitelMax).regex(getBildungStudiengaengeResponseTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(getBildungStudiengaengeResponseKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(getBildungStudiengaengeResponseVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(getBildungStudiengaengeResponsePreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(getBildungStudiengaengeResponseRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(getBildungStudiengaengeResponseVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(getBildungStudiengaengeResponseZielgruppeMax).optional(),
  "abschluss": zod.enum(['BACHELOR', 'MASTER']),
  "studienform": zod.enum(['VOLLZEIT', 'DUAL', 'BERUFSBEGLEITEND']),
  "startsemester": zod.string().regex(getBildungStudiengaengeResponseStartsemesterRegExp),
  "regelstudienzeitSemester": zod.number().min(1).optional(),
  "akkreditierungBis": zod.string().date().optional(),
  "plaetze": zod.number().min(getBildungStudiengaengeResponsePlaetzeMin).optional()
})
export const GetBildungStudiengaengeResponse = zod.array(GetBildungStudiengaengeResponseItem)

/**
 * @summary Create Studiengang
 */
export const postBildungStudiengaengeBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postBildungStudiengaengeBodyTitelMax = 200;


export const postBildungStudiengaengeBodyTitelRegExp = new RegExp('\\S');
export const postBildungStudiengaengeBodyKurzbeschreibungMax = 2000;

export const postBildungStudiengaengeBodyVerantwortlichMax = 120;

export const postBildungStudiengaengeBodyPreisCentMin = 0;


export const postBildungStudiengaengeBodyRatenGesamtMin = 0;

export const postBildungStudiengaengeBodyVendureProductIdMax = 64;

export const postBildungStudiengaengeBodyZielgruppeMax = 200;

export const postBildungStudiengaengeBodyStartsemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');

export const postBildungStudiengaengeBodyPlaetzeMin = 0;



export const PostBildungStudiengaengeBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(postBildungStudiengaengeBodyCodeRegExp),
  "titel": zod.string().max(postBildungStudiengaengeBodyTitelMax).regex(postBildungStudiengaengeBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(postBildungStudiengaengeBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(postBildungStudiengaengeBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(postBildungStudiengaengeBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(postBildungStudiengaengeBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(postBildungStudiengaengeBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(postBildungStudiengaengeBodyZielgruppeMax).optional(),
  "abschluss": zod.enum(['BACHELOR', 'MASTER']),
  "studienform": zod.enum(['VOLLZEIT', 'DUAL', 'BERUFSBEGLEITEND']),
  "startsemester": zod.string().regex(postBildungStudiengaengeBodyStartsemesterRegExp),
  "regelstudienzeitSemester": zod.number().min(1).optional(),
  "akkreditierungBis": zod.string().date().optional(),
  "plaetze": zod.number().min(postBildungStudiengaengeBodyPlaetzeMin).optional()
})

export const PostBildungStudiengaengeResponse = zod.unknown()

/**
 * @summary Update Studiengang
 */
export const PutBildungStudiengaengeIdParams = zod.object({
  "id": zod.number()
})

export const putBildungStudiengaengeIdBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putBildungStudiengaengeIdBodyTitelMax = 200;


export const putBildungStudiengaengeIdBodyTitelRegExp = new RegExp('\\S');
export const putBildungStudiengaengeIdBodyKurzbeschreibungMax = 2000;

export const putBildungStudiengaengeIdBodyVerantwortlichMax = 120;

export const putBildungStudiengaengeIdBodyPreisCentMin = 0;


export const putBildungStudiengaengeIdBodyRatenGesamtMin = 0;

export const putBildungStudiengaengeIdBodyVendureProductIdMax = 64;

export const putBildungStudiengaengeIdBodyZielgruppeMax = 200;

export const putBildungStudiengaengeIdBodyStartsemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');

export const putBildungStudiengaengeIdBodyPlaetzeMin = 0;



export const PutBildungStudiengaengeIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(putBildungStudiengaengeIdBodyCodeRegExp),
  "titel": zod.string().max(putBildungStudiengaengeIdBodyTitelMax).regex(putBildungStudiengaengeIdBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(putBildungStudiengaengeIdBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(putBildungStudiengaengeIdBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(putBildungStudiengaengeIdBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(putBildungStudiengaengeIdBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(putBildungStudiengaengeIdBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(putBildungStudiengaengeIdBodyZielgruppeMax).optional(),
  "abschluss": zod.enum(['BACHELOR', 'MASTER']),
  "studienform": zod.enum(['VOLLZEIT', 'DUAL', 'BERUFSBEGLEITEND']),
  "startsemester": zod.string().regex(putBildungStudiengaengeIdBodyStartsemesterRegExp),
  "regelstudienzeitSemester": zod.number().min(1).optional(),
  "akkreditierungBis": zod.string().date().optional(),
  "plaetze": zod.number().min(putBildungStudiengaengeIdBodyPlaetzeMin).optional()
})

export const PutBildungStudiengaengeIdResponse = zod.unknown()

/**
 * @summary Get Studiengang
 */
export const GetBildungStudiengaengeIdParams = zod.object({
  "id": zod.number()
})

export const GetBildungStudiengaengeIdResponse = zod.unknown()

/**
 * @summary Archive Studiengang
 */
export const DeleteBildungStudiengaengeIdParams = zod.object({
  "id": zod.number()
})

export const DeleteBildungStudiengaengeIdResponse = zod.unknown()

/**
 * @summary List Tagungen
 */
export const getBildungTagungenResponseCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getBildungTagungenResponseTitelMax = 200;


export const getBildungTagungenResponseTitelRegExp = new RegExp('\\S');
export const getBildungTagungenResponseKurzbeschreibungMax = 2000;

export const getBildungTagungenResponseVerantwortlichMax = 120;

export const getBildungTagungenResponsePreisCentMin = 0;


export const getBildungTagungenResponseRatenGesamtMin = 0;

export const getBildungTagungenResponseVendureProductIdMax = 64;

export const getBildungTagungenResponseZielgruppeMax = 200;

export const getBildungTagungenResponseThemaMax = 200;


export const getBildungTagungenResponseThemaRegExp = new RegExp('\\S');
export const getBildungTagungenResponseOrtMax = 200;

export const getBildungTagungenResponseProgrammUrlMax = 300;


export const getBildungTagungenResponseProgrammUrlRegExp = new RegExp('^https?://.+');



export const GetBildungTagungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(getBildungTagungenResponseCodeRegExp),
  "titel": zod.string().max(getBildungTagungenResponseTitelMax).regex(getBildungTagungenResponseTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(getBildungTagungenResponseKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(getBildungTagungenResponseVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(getBildungTagungenResponsePreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(getBildungTagungenResponseRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(getBildungTagungenResponseVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(getBildungTagungenResponseZielgruppeMax).optional(),
  "thema": zod.string().max(getBildungTagungenResponseThemaMax).regex(getBildungTagungenResponseThemaRegExp),
  "terminVon": zod.string().date(),
  "terminBis": zod.string().date().optional(),
  "ort": zod.string().max(getBildungTagungenResponseOrtMax).optional(),
  "programmUrl": zod.string().max(getBildungTagungenResponseProgrammUrlMax).regex(getBildungTagungenResponseProgrammUrlRegExp).optional(),
  "maxTN": zod.number().min(1).optional()
})
export const GetBildungTagungenResponse = zod.array(GetBildungTagungenResponseItem)

/**
 * @summary Create Tagung
 */
export const postBildungTagungenBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postBildungTagungenBodyTitelMax = 200;


export const postBildungTagungenBodyTitelRegExp = new RegExp('\\S');
export const postBildungTagungenBodyKurzbeschreibungMax = 2000;

export const postBildungTagungenBodyVerantwortlichMax = 120;

export const postBildungTagungenBodyPreisCentMin = 0;


export const postBildungTagungenBodyRatenGesamtMin = 0;

export const postBildungTagungenBodyVendureProductIdMax = 64;

export const postBildungTagungenBodyZielgruppeMax = 200;

export const postBildungTagungenBodyThemaMax = 200;


export const postBildungTagungenBodyThemaRegExp = new RegExp('\\S');
export const postBildungTagungenBodyOrtMax = 200;

export const postBildungTagungenBodyProgrammUrlMax = 300;


export const postBildungTagungenBodyProgrammUrlRegExp = new RegExp('^https?://.+');



export const PostBildungTagungenBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(postBildungTagungenBodyCodeRegExp),
  "titel": zod.string().max(postBildungTagungenBodyTitelMax).regex(postBildungTagungenBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(postBildungTagungenBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(postBildungTagungenBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(postBildungTagungenBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(postBildungTagungenBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(postBildungTagungenBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(postBildungTagungenBodyZielgruppeMax).optional(),
  "thema": zod.string().max(postBildungTagungenBodyThemaMax).regex(postBildungTagungenBodyThemaRegExp),
  "terminVon": zod.string().date(),
  "terminBis": zod.string().date().optional(),
  "ort": zod.string().max(postBildungTagungenBodyOrtMax).optional(),
  "programmUrl": zod.string().max(postBildungTagungenBodyProgrammUrlMax).regex(postBildungTagungenBodyProgrammUrlRegExp).optional(),
  "maxTN": zod.number().min(1).optional()
})

export const PostBildungTagungenResponse = zod.unknown()

/**
 * @summary Update Tagung
 */
export const PutBildungTagungenIdParams = zod.object({
  "id": zod.number()
})

export const putBildungTagungenIdBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putBildungTagungenIdBodyTitelMax = 200;


export const putBildungTagungenIdBodyTitelRegExp = new RegExp('\\S');
export const putBildungTagungenIdBodyKurzbeschreibungMax = 2000;

export const putBildungTagungenIdBodyVerantwortlichMax = 120;

export const putBildungTagungenIdBodyPreisCentMin = 0;


export const putBildungTagungenIdBodyRatenGesamtMin = 0;

export const putBildungTagungenIdBodyVendureProductIdMax = 64;

export const putBildungTagungenIdBodyZielgruppeMax = 200;

export const putBildungTagungenIdBodyThemaMax = 200;


export const putBildungTagungenIdBodyThemaRegExp = new RegExp('\\S');
export const putBildungTagungenIdBodyOrtMax = 200;

export const putBildungTagungenIdBodyProgrammUrlMax = 300;


export const putBildungTagungenIdBodyProgrammUrlRegExp = new RegExp('^https?://.+');



export const PutBildungTagungenIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['SEMINAR', 'TAGUNG', 'BERUFSSCHULJAHR', 'STUDIENGANG']).optional(),
  "code": zod.string().regex(putBildungTagungenIdBodyCodeRegExp),
  "titel": zod.string().max(putBildungTagungenIdBodyTitelMax).regex(putBildungTagungenIdBodyTitelRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE']),
  "kurzbeschreibung": zod.string().max(putBildungTagungenIdBodyKurzbeschreibungMax).optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "gueltigAb": zod.string().date(),
  "gueltigBis": zod.string().date().optional(),
  "verantwortlich": zod.string().max(putBildungTagungenIdBodyVerantwortlichMax).optional(),
  "preisModell": zod.enum(['EINMALIG', 'ABO', 'RATEN']),
  "preisCent": zod.number().min(putBildungTagungenIdBodyPreisCentMin).optional(),
  "abrechnungIntervallMonate": zod.number().min(1).optional(),
  "ratenGesamt": zod.number().min(putBildungTagungenIdBodyRatenGesamtMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "vendureProductId": zod.string().max(putBildungTagungenIdBodyVendureProductIdMax).optional(),
  "zielgruppe": zod.string().max(putBildungTagungenIdBodyZielgruppeMax).optional(),
  "thema": zod.string().max(putBildungTagungenIdBodyThemaMax).regex(putBildungTagungenIdBodyThemaRegExp),
  "terminVon": zod.string().date(),
  "terminBis": zod.string().date().optional(),
  "ort": zod.string().max(putBildungTagungenIdBodyOrtMax).optional(),
  "programmUrl": zod.string().max(putBildungTagungenIdBodyProgrammUrlMax).regex(putBildungTagungenIdBodyProgrammUrlRegExp).optional(),
  "maxTN": zod.number().min(1).optional()
})

export const PutBildungTagungenIdResponse = zod.unknown()

/**
 * @summary Get Tagung
 */
export const GetBildungTagungenIdParams = zod.object({
  "id": zod.number()
})

export const GetBildungTagungenIdResponse = zod.unknown()

/**
 * @summary Archive Tagung
 */
export const DeleteBildungTagungenIdParams = zod.object({
  "id": zod.number()
})

export const DeleteBildungTagungenIdResponse = zod.unknown()

