/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AnmeldungDto,
  BestandImportDto,
  Buchungssatz,
  DatevProtokollDto,
  DebitorAliasDto,
  DebitorAnlageDto,
  DebitorDto,
  ExterneBestellung,
  GetRechnungDatevBuchungssaetzeParams,
  GetRechnungDatevBuchungsstapelParams,
  GetRechnungDebitorenAufloesenParams,
  GetRechnungRechnungenParams,
  HochschulLaufRequest,
  KorrekturRequest,
  ManuellePositionDto,
  MergeRequest1,
  PostRechnungDatevUebergabeParams,
  RechnungDto,
  RechnungslaufRequest
} from '../../model';

import { http } from '../../http';



  /**
 * @summary List Anmeldungen
 */
export const getRechnungAnmeldungen = (

 ) => {
      return http<AnmeldungDto[]>(
      {url: `/rechnung/anmeldungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Anmeldung
 */
export const postRechnungAnmeldungen = (
    anmeldungDto: AnmeldungDto,
 ) => {
      return http<unknown>(
      {url: `/rechnung/anmeldungen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: anmeldungDto
    },
      );
    }
  /**
 * @summary Update Anmeldung
 */
export const putRechnungAnmeldungenId = (
    id: number,
    anmeldungDto: AnmeldungDto,
 ) => {
      return http<unknown>(
      {url: `/rechnung/anmeldungen/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: anmeldungDto
    },
      );
    }
  /**
 * @summary Get Anmeldung
 */
export const getRechnungAnmeldungenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/rechnung/anmeldungen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Abbrechen Anmeldung
 */
export const deleteRechnungAnmeldungenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/rechnung/anmeldungen/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Datev Buchungssaetze
 */
export const getRechnungDatevBuchungssaetze = (
    params?: GetRechnungDatevBuchungssaetzeParams,
 ) => {
      return http<Buchungssatz[]>(
      {url: `/rechnung/datev/buchungssaetze`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Datev Buchungsstapel
 */
export const getRechnungDatevBuchungsstapel = (
    params?: GetRechnungDatevBuchungsstapelParams,
 ) => {
      return http<unknown>(
      {url: `/rechnung/datev/buchungsstapel`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Datev Uebergeben
 */
export const postRechnungDatevUebergabe = (
    params?: PostRechnungDatevUebergabeParams,
 ) => {
      return http<DatevProtokollDto>(
      {url: `/rechnung/datev/uebergabe`, method: 'POST',
        params
    },
      );
    }
  /**
 * @summary List Debitoren
 */
export const getRechnungDebitoren = (

 ) => {
      return http<DebitorDto[]>(
      {url: `/rechnung/debitoren`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Debitor
 */
export const postRechnungDebitoren = (
    debitorDto: DebitorDto,
 ) => {
      return http<unknown>(
      {url: `/rechnung/debitoren`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: debitorDto
    },
      );
    }
  /**
 * @summary Anlegen Debitor
 */
export const postRechnungDebitorenAnlegen = (
    debitorAnlageDto: DebitorAnlageDto,
 ) => {
      return http<unknown>(
      {url: `/rechnung/debitoren/anlegen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: debitorAnlageDto
    },
      );
    }
  /**
 * @summary Aufloesen Debitor
 */
export const getRechnungDebitorenAufloesen = (
    params?: GetRechnungDebitorenAufloesenParams,
 ) => {
      return http<unknown>(
      {url: `/rechnung/debitoren/aufloesen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Import Debitor
 */
export const postRechnungDebitorenImport = (
    bestandImportDto: BestandImportDto,
 ) => {
      return http<DebitorDto>(
      {url: `/rechnung/debitoren/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bestandImportDto
    },
      );
    }
  /**
 * @summary Merge Debitoren
 */
export const postRechnungDebitorenMerge = (
    mergeRequest1: MergeRequest1,
 ) => {
      return http<DebitorDto>(
      {url: `/rechnung/debitoren/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeRequest1
    },
      );
    }
  /**
 * @summary Update Debitor
 */
export const putRechnungDebitorenId = (
    id: number,
    debitorDto: DebitorDto,
 ) => {
      return http<unknown>(
      {url: `/rechnung/debitoren/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: debitorDto
    },
      );
    }
  /**
 * @summary Get Debitor
 */
export const getRechnungDebitorenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/rechnung/debitoren/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Aliase
 */
export const getRechnungDebitorenIdAliase = (
    id: number,
 ) => {
      return http<DebitorAliasDto[]>(
      {url: `/rechnung/debitoren/${id}/aliase`, method: 'GET'
    },
      );
    }
  /**
 * @summary Kandidaten
 */
export const getRechnungDebitorenIdKandidaten = (
    id: number,
 ) => {
      return http<DebitorDto[]>(
      {url: `/rechnung/debitoren/${id}/kandidaten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Rechnungslauf
 */
export const postRechnungLaeufe = (
    rechnungslaufRequest: RechnungslaufRequest,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/laeufe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rechnungslaufRequest
    },
      );
    }
  /**
 * @summary Hochschul Lauf
 */
export const postRechnungLaeufeHochschule = (
    hochschulLaufRequest: HochschulLaufRequest,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/laeufe/hochschule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hochschulLaufRequest
    },
      );
    }
  /**
 * @summary Bestellung Uebernehmen
 */
export const postRechnungQuellenBestellung = (
    externeBestellung: ExterneBestellung,
 ) => {
      return http<unknown>(
      {url: `/rechnung/quellen/bestellung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: externeBestellung
    },
      );
    }
  /**
 * @summary List Rechnungen
 */
export const getRechnungRechnungen = (
    params?: GetRechnungRechnungenParams,
 ) => {
      return http<RechnungDto[]>(
      {url: `/rechnung/rechnungen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Get Rechnung
 */
export const getRechnungRechnungenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/rechnung/rechnungen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Ausstellen
 */
export const postRechnungRechnungenIdAusstellen = (
    id: number,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/ausstellen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Gutschrift
 */
export const postRechnungRechnungenIdGutschrift = (
    id: number,
    korrekturRequest: KorrekturRequest,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/gutschrift`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: korrekturRequest
    },
      );
    }
  /**
 * @summary Nachberechnung
 */
export const postRechnungRechnungenIdNachberechnung = (
    id: number,
    korrekturRequest: KorrekturRequest,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/nachberechnung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: korrekturRequest
    },
      );
    }
  /**
 * @summary Add Position
 */
export const postRechnungRechnungenIdPositionen = (
    id: number,
    manuellePositionDto: ManuellePositionDto,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/positionen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: manuellePositionDto
    },
      );
    }
  /**
 * @summary Storno
 */
export const postRechnungRechnungenIdStorno = (
    id: number,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/storno`, method: 'POST'
    },
      );
    }
  /**
 * @summary Versenden
 */
export const postRechnungRechnungenIdVersenden = (
    id: number,
 ) => {
      return http<RechnungDto>(
      {url: `/rechnung/rechnungen/${id}/versenden`, method: 'POST'
    },
      );
    }
  /**
 * @summary Zugferd
 */
export const getRechnungRechnungenIdZugferd = (
    id: number,
 ) => {
      return http<Blob>(
      {url: `/rechnung/rechnungen/${id}/zugferd`, method: 'GET',
        responseType: 'blob'
    },
      );
    }
  export type GetRechnungAnmeldungenResult = NonNullable<Awaited<ReturnType<typeof getRechnungAnmeldungen>>>
export type PostRechnungAnmeldungenResult = NonNullable<Awaited<ReturnType<typeof postRechnungAnmeldungen>>>
export type PutRechnungAnmeldungenIdResult = NonNullable<Awaited<ReturnType<typeof putRechnungAnmeldungenId>>>
export type GetRechnungAnmeldungenIdResult = NonNullable<Awaited<ReturnType<typeof getRechnungAnmeldungenId>>>
export type DeleteRechnungAnmeldungenIdResult = NonNullable<Awaited<ReturnType<typeof deleteRechnungAnmeldungenId>>>
export type GetRechnungDatevBuchungssaetzeResult = NonNullable<Awaited<ReturnType<typeof getRechnungDatevBuchungssaetze>>>
export type GetRechnungDatevBuchungsstapelResult = NonNullable<Awaited<ReturnType<typeof getRechnungDatevBuchungsstapel>>>
export type PostRechnungDatevUebergabeResult = NonNullable<Awaited<ReturnType<typeof postRechnungDatevUebergabe>>>
export type GetRechnungDebitorenResult = NonNullable<Awaited<ReturnType<typeof getRechnungDebitoren>>>
export type PostRechnungDebitorenResult = NonNullable<Awaited<ReturnType<typeof postRechnungDebitoren>>>
export type PostRechnungDebitorenAnlegenResult = NonNullable<Awaited<ReturnType<typeof postRechnungDebitorenAnlegen>>>
export type GetRechnungDebitorenAufloesenResult = NonNullable<Awaited<ReturnType<typeof getRechnungDebitorenAufloesen>>>
export type PostRechnungDebitorenImportResult = NonNullable<Awaited<ReturnType<typeof postRechnungDebitorenImport>>>
export type PostRechnungDebitorenMergeResult = NonNullable<Awaited<ReturnType<typeof postRechnungDebitorenMerge>>>
export type PutRechnungDebitorenIdResult = NonNullable<Awaited<ReturnType<typeof putRechnungDebitorenId>>>
export type GetRechnungDebitorenIdResult = NonNullable<Awaited<ReturnType<typeof getRechnungDebitorenId>>>
export type GetRechnungDebitorenIdAliaseResult = NonNullable<Awaited<ReturnType<typeof getRechnungDebitorenIdAliase>>>
export type GetRechnungDebitorenIdKandidatenResult = NonNullable<Awaited<ReturnType<typeof getRechnungDebitorenIdKandidaten>>>
export type PostRechnungLaeufeResult = NonNullable<Awaited<ReturnType<typeof postRechnungLaeufe>>>
export type PostRechnungLaeufeHochschuleResult = NonNullable<Awaited<ReturnType<typeof postRechnungLaeufeHochschule>>>
export type PostRechnungQuellenBestellungResult = NonNullable<Awaited<ReturnType<typeof postRechnungQuellenBestellung>>>
export type GetRechnungRechnungenResult = NonNullable<Awaited<ReturnType<typeof getRechnungRechnungen>>>
export type GetRechnungRechnungenIdResult = NonNullable<Awaited<ReturnType<typeof getRechnungRechnungenId>>>
export type PostRechnungRechnungenIdAusstellenResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdAusstellen>>>
export type PostRechnungRechnungenIdGutschriftResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdGutschrift>>>
export type PostRechnungRechnungenIdNachberechnungResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdNachberechnung>>>
export type PostRechnungRechnungenIdPositionenResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdPositionen>>>
export type PostRechnungRechnungenIdStornoResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdStorno>>>
export type PostRechnungRechnungenIdVersendenResult = NonNullable<Awaited<ReturnType<typeof postRechnungRechnungenIdVersenden>>>
export type GetRechnungRechnungenIdZugferdResult = NonNullable<Awaited<ReturnType<typeof getRechnungRechnungenIdZugferd>>>
