/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Liste
 */
export const GetOutboxQueryParams = zod.object({
  "status": zod.enum(['OFFEN', 'ERLEDIGT', 'FEHLGESCHLAGEN']).optional()
})

export const GetOutboxResponseItem = zod.object({
  "id": zod.number().optional(),
  "anmeldungId": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "zielsystem": zod.string().optional(),
  "ereignis": zod.string().optional(),
  "status": zod.string().optional(),
  "versuche": zod.number().optional(),
  "naechsterVersuchAm": zod.string().datetime({"offset":true}).optional(),
  "letzterFehler": zod.string().optional(),
  "erstelltAm": zod.string().datetime({"offset":true}).optional(),
  "erledigtAm": zod.string().datetime({"offset":true}).optional()
})
export const GetOutboxResponse = zod.array(GetOutboxResponseItem)

/**
 * @summary Dispatch
 */
export const PostOutboxDispatchResponse = zod.unknown()

/**
 * @summary Neu Versuch
 */
export const PostOutboxIdNeuVersuchParams = zod.object({
  "id": zod.number()
})

export const PostOutboxIdNeuVersuchResponse = zod.unknown()

