/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AnmeldungStatus } from './anmeldungStatus';
import type { AnmeldungTyp } from './anmeldungTyp';
import type { Zimmerart } from './zimmerart';

export interface AnmeldungDto {
  id?: number;
  version?: number;
  typ: AnmeldungTyp;
  /**
     * @maxLength 200
     * @pattern \S
     */
  teilnehmerName: string;
  /** @maxLength 200 */
  teilnehmerEmail?: string;
  bildungsangebotId?: number;
  zahlungspflichtigerDebitorId: number;
  status: AnmeldungStatus;
  /** @pattern ^\d{4}/\d{4}$ */
  schuljahr?: string;
  /**
     * @minimum 1
     * @maximum 2
     */
  halbjahr?: number;
  zimmerart?: Zimmerart;
  /** @minimum 0 */
  unterrichtBetragCent?: number;
  /** @minimum 0 */
  uebernachtungBetragCent?: number;
  /** @pattern ^(WS|SS)\d{4}$ */
  semester?: string;
  /** @minimum 0 */
  semesterbetragCent?: number;
  firmaDebitorId?: number;
  /** @minimum 0 */
  firmaAnteilCent?: number;
  /**
     * @minimum 1
     * @maximum 12
     */
  ratenAnzahl?: number;
}
