/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Zimmerart } from './zimmerart';

export interface AzubiAnmeldungDto {
  organisationId: number;
  /** @pattern \S */
  azubiEmail: string;
  /** @pattern \S */
  azubiName: string;
  /** @pattern \S */
  schuljahr: string;
  halbjahr?: number;
  zimmerart: Zimmerart;
  unterrichtBetragCent?: number;
  uebernachtungBetragCent?: number;
}
