/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalTime } from './localTime';

export interface EinstellungView {
  digest?: boolean;
  quietVon?: LocalTime;
  quietBis?: LocalTime;
  maxProStunde?: number;
}
