/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export enum Entscheidung {
  NEUANLAGE_BESTAETIGT= 'NEUANLAGE_BESTAETIGT',
  GEMERGT= 'GEMERGT',

}