/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface EreignisView {
  id?: number;
  ereignisTyp?: string;
  kategorie?: string;
  betreff?: string;
  zeitpunkt?: LocalDateTime;
  kontextTyp?: string;
  kontextId?: number;
  gelesen?: boolean;
  bestaetigungErforderlich?: boolean;
  bestaetigtAm?: LocalDateTime;
}
