/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { DebitorAnlageDto } from './debitorAnlageDto';
import type { Position } from './position';
import type { Zahlungsart } from './zahlungsart';

export interface ExterneBestellung {
  /**
     * @maxLength 40
     * @pattern \S
     */
  quelle: string;
  /**
     * @maxLength 64
     * @pattern \S
     */
  externeId: string;
  zahlungsart: Zahlungsart;
  debitor: DebitorAnlageDto;
  /** @minItems 1 */
  positionen: Position[];
}
