/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AnmeldungStatus } from './anmeldungStatus';

export type GetPartyAnmeldungenParams = {
status?: AnmeldungStatus;
};
