/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface Hochschulbuchung {
  teilnehmerPersonId: number;
  bestellerPersonId?: number;
  kontextOrganisationId?: number;
  /** @pattern \S */
  semester: string;
  semesterbetragCent?: number;
  firmaAnteilCent?: number;
  ratenAnzahl?: number;
}
