/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export * from './ausbildungsbetriebAnfrage';
export * from './azubiAnmeldungDto';
export * from './belegart';
export * from './bereich1';
export * from './berufsschulbuchung';
export * from './buchungZeile';
export * from './debitorView';
export * from './einladungView';
export * from './einschreibungStatus';
export * from './ereignisView';
export * from './getPartyPersonenIdDebitorParams';
export * from './getPartyPortalRechnungenParams';
export * from './hochschulbuchung';
export * from './kanal';
export * from './kontextView';
export * from './localDate';
export * from './localDateTime';
export * from './login';
export * from './meinTrainingView';
export * from './mergeRequest';
export * from './mitgliedschaftView1';
export * from './organisationDto';
export * from './organisationView';
export * from './orgMergeRequest';
export * from './personView';
export * from './portalRechnungView';
export * from './position';
export * from './praeferenzDto';
export * from './praeferenzView';
export * from './rechnungsKontextView';
export * from './rechnungStatus';
export * from './selbstRegistrierung';
export * from './shopBestellung';
export * from './steuerfall';
export * from './teilnehmerAnlage';
export * from './ungelesenView';
export * from './zahlungsart';
export * from './zimmerart';
