/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Rolle } from './rolle';

export interface KontextView {
  art?: string;
  organisationId?: number;
  bezeichnung?: string;
  rollen?: Rolle[];
}
