/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Instant } from './instant';

export interface Konto {
  name?: string;
  email?: string;
  bezahlkartenNr?: string;
  angelegtAm?: Instant;
}
