/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Leistungsart } from './leistungsart';
import type { Steuerfall } from './steuerfall';

export interface ManuellePositionDto {
  /** @maxLength 200 */
  teilnehmerName?: string;
  /**
     * @maxLength 300
     * @pattern \S
     */
  beschreibung: string;
  menge?: number;
  einzelbetragCent?: number;
  steuerfall: Steuerfall;
  steuersatz?: number;
  /** @maxLength 200 */
  befreiungsgrund?: string;
  leistungsart: Leistungsart;
}
