/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Rolle } from './rolle';

export interface MitgliedschaftView {
  organisationId?: number;
  organisation?: string;
  rolle?: Rolle;
  buchungsberechtigt?: boolean;
}
