/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export enum SeminarKategorie1 {
  FUEHRUNG= 'FUEHRUNG',
  FACHKOMPETENZ= 'FACHKOMPETENZ',
  COMPLIANCE= 'COMPLIANCE',
  IT_DIGITAL= 'IT_DIGITAL',
  SPRACHEN= 'SPRACHEN',
  SONSTIGE= 'SONSTIGE',
  UNBEKANNT= 'UNBEKANNT',

}