/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface TeilnehmerAnlage {
  /** @pattern \S */
  email: string;
  /** @pattern \S */
  anzeigeName: string;
  /** @pattern \S */
  rolle: string;
  buchungsberechtigt?: boolean;
}
