/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Anfrage Ausbildungsbetrieb
 */
export const postPartyAnfragenAusbildungsbetriebBodyNameRegExp = new RegExp('\\S');
export const postPartyAnfragenAusbildungsbetriebBodyAnsprechpartnerEmailRegExp = new RegExp('\\S');
export const postPartyAnfragenAusbildungsbetriebBodyAnsprechpartnerNameRegExp = new RegExp('\\S');


export const PostPartyAnfragenAusbildungsbetriebBody = zod.object({
  "name": zod.string().regex(postPartyAnfragenAusbildungsbetriebBodyNameRegExp),
  "strasse": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "land": zod.string().optional(),
  "ustId": zod.string().optional(),
  "ansprechpartnerEmail": zod.string().regex(postPartyAnfragenAusbildungsbetriebBodyAnsprechpartnerEmailRegExp),
  "ansprechpartnerName": zod.string().regex(postPartyAnfragenAusbildungsbetriebBodyAnsprechpartnerNameRegExp),
  "website": zod.string().optional()
})

export const PostPartyAnfragenAusbildungsbetriebResponse = zod.unknown()

/**
 * @summary Buche Berufsschule
 */
export const postPartyBuchungenBerufsschuleBodySchuljahrRegExp = new RegExp('\\S');


export const PostPartyBuchungenBerufsschuleBody = zod.object({
  "teilnehmerPersonId": zod.number(),
  "bestellerPersonId": zod.number().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "schuljahr": zod.string().regex(postPartyBuchungenBerufsschuleBodySchuljahrRegExp),
  "halbjahr": zod.number().optional(),
  "zimmerart": zod.enum(['KEINE', 'DOPPEL', 'EINZEL']),
  "unterrichtBetragCent": zod.number().optional(),
  "uebernachtungBetragCent": zod.number().optional()
})

export const PostPartyBuchungenBerufsschuleResponse = zod.unknown()

/**
 * @summary Buche Hochschule
 */
export const postPartyBuchungenHochschuleBodySemesterRegExp = new RegExp('\\S');


export const PostPartyBuchungenHochschuleBody = zod.object({
  "teilnehmerPersonId": zod.number(),
  "bestellerPersonId": zod.number().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "semester": zod.string().regex(postPartyBuchungenHochschuleBodySemesterRegExp),
  "semesterbetragCent": zod.number().optional(),
  "firmaAnteilCent": zod.number().optional(),
  "ratenAnzahl": zod.number().optional()
})

export const PostPartyBuchungenHochschuleResponse = zod.unknown()

/**
 * @summary Firmensicht
 */
export const GetPartyFirmensichtOrganisationIdParams = zod.object({
  "organisationId": zod.number()
})

export const GetPartyFirmensichtOrganisationIdResponse = zod.unknown()

/**
 * @summary Create Organisation
 */
export const postPartyOrganisationenBodyNameRegExp = new RegExp('\\S');


export const PostPartyOrganisationenBody = zod.object({
  "name": zod.string().regex(postPartyOrganisationenBodyNameRegExp),
  "strasse": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "land": zod.string().optional(),
  "ustId": zod.string().optional()
})

export const PostPartyOrganisationenResponse = zod.unknown()

/**
 * @summary Merge Organisation
 */
export const PostPartyOrganisationenMergeBody = zod.object({
  "quellId": zod.number(),
  "zielId": zod.number()
})

export const PostPartyOrganisationenMergeResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "ustId": zod.string().optional(),
  "status": zod.string().optional(),
  "goldenOrganisationId": zod.number().optional()
})

/**
 * @summary Get Organisation
 */
export const GetPartyOrganisationenIdParams = zod.object({
  "id": zod.number()
})

export const GetPartyOrganisationenIdResponse = zod.unknown()

/**
 * @summary Organisation Kandidaten
 */
export const GetPartyOrganisationenIdKandidatenParams = zod.object({
  "id": zod.number()
})

export const GetPartyOrganisationenIdKandidatenResponseItem = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "ustId": zod.string().optional(),
  "status": zod.string().optional(),
  "goldenOrganisationId": zod.number().optional()
})
export const GetPartyOrganisationenIdKandidatenResponse = zod.array(GetPartyOrganisationenIdKandidatenResponseItem)

/**
 * @summary Teilnehmer Anlegen
 */
export const PostPartyOrganisationenIdTeilnehmerParams = zod.object({
  "id": zod.number()
})

export const postPartyOrganisationenIdTeilnehmerBodyEmailRegExp = new RegExp('\\S');
export const postPartyOrganisationenIdTeilnehmerBodyAnzeigeNameRegExp = new RegExp('\\S');


export const PostPartyOrganisationenIdTeilnehmerBody = zod.object({
  "email": zod.string().regex(postPartyOrganisationenIdTeilnehmerBodyEmailRegExp),
  "anzeigeName": zod.string().regex(postPartyOrganisationenIdTeilnehmerBodyAnzeigeNameRegExp),
  "rolle": zod.enum(['AUSBILDER', 'ANSPRECHPARTNER_STUDIUM', 'SEMINAR_BUCHER', 'AZUBI', 'STUDENT', 'AUFSICHTSRAT']),
  "buchungsberechtigt": zod.boolean().optional()
})

export const PostPartyOrganisationenIdTeilnehmerResponse = zod.unknown()

/**
 * @summary Login
 */
export const postPartyPersonenLoginBodyEmailRegExp = new RegExp('\\S');
export const postPartyPersonenLoginBodyAnzeigeNameRegExp = new RegExp('\\S');


export const PostPartyPersonenLoginBody = zod.object({
  "email": zod.string().regex(postPartyPersonenLoginBodyEmailRegExp),
  "anzeigeName": zod.string().regex(postPartyPersonenLoginBodyAnzeigeNameRegExp)
})

export const PostPartyPersonenLoginResponse = zod.unknown()

/**
 * @summary Merge
 */
export const PostPartyPersonenMergeBody = zod.object({
  "quellId": zod.number(),
  "zielId": zod.number()
})

export const PostPartyPersonenMergeResponse = zod.object({
  "id": zod.number().optional(),
  "keycloakSub": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "status": zod.string().optional(),
  "goldenPersonId": zod.number().optional(),
  "emails": zod.array(zod.string()).optional(),
  "mitgliedschaften": zod.array(zod.object({
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolle": zod.enum(['AUSBILDER', 'ANSPRECHPARTNER_STUDIUM', 'SEMINAR_BUCHER', 'AZUBI', 'STUDENT', 'AUFSICHTSRAT']).optional(),
  "buchungsberechtigt": zod.boolean().optional()
})).optional()
})

/**
 * @summary Selbst Registrieren
 */
export const postPartyPersonenSelbstregistrierenBodyKeycloakSubRegExp = new RegExp('\\S');
export const postPartyPersonenSelbstregistrierenBodyEmailRegExp = new RegExp('\\S');
export const postPartyPersonenSelbstregistrierenBodyAnzeigeNameRegExp = new RegExp('\\S');


export const PostPartyPersonenSelbstregistrierenBody = zod.object({
  "keycloakSub": zod.string().regex(postPartyPersonenSelbstregistrierenBodyKeycloakSubRegExp),
  "email": zod.string().regex(postPartyPersonenSelbstregistrierenBodyEmailRegExp),
  "anzeigeName": zod.string().regex(postPartyPersonenSelbstregistrierenBodyAnzeigeNameRegExp)
})

export const PostPartyPersonenSelbstregistrierenResponse = zod.unknown()

/**
 * @summary Get Person
 */
export const GetPartyPersonenIdParams = zod.object({
  "id": zod.number()
})

export const GetPartyPersonenIdResponse = zod.unknown()

/**
 * @summary Personen Buchungen
 */
export const GetPartyPersonenIdBuchungenParams = zod.object({
  "id": zod.number()
})

export const GetPartyPersonenIdBuchungenResponseItem = zod.object({
  "anmeldungId": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "teilnehmerPersonId": zod.number().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "zahlungspflichtigerDebitorId": zod.number().optional(),
  "schuljahr": zod.string().optional(),
  "halbjahr": zod.number().optional(),
  "status": zod.string().optional()
})
export const GetPartyPersonenIdBuchungenResponse = zod.array(GetPartyPersonenIdBuchungenResponseItem)

/**
 * @summary Debitor
 */
export const GetPartyPersonenIdDebitorParams = zod.object({
  "id": zod.number()
})

export const GetPartyPersonenIdDebitorQueryParams = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "organisationId": zod.number().optional()
})

export const GetPartyPersonenIdDebitorResponse = zod.object({
  "id": zod.number().optional(),
  "debitorNr": zod.string().optional(),
  "bereich": zod.string().optional(),
  "rolle": zod.string().optional(),
  "name": zod.string().optional()
})

/**
 * @summary Einladung
 */
export const PostPartyPersonenIdEinladungParams = zod.object({
  "id": zod.number()
})

export const PostPartyPersonenIdEinladungResponse = zod.object({
  "personId": zod.number().optional(),
  "email": zod.string().optional(),
  "keycloakUserId": zod.string().optional(),
  "provisioniert": zod.boolean().optional(),
  "eingeladen": zod.boolean().optional()
})

/**
 * @summary Kandidaten
 */
export const GetPartyPersonenIdKandidatenParams = zod.object({
  "id": zod.number()
})

export const GetPartyPersonenIdKandidatenResponseItem = zod.object({
  "id": zod.number().optional(),
  "keycloakSub": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "status": zod.string().optional(),
  "goldenPersonId": zod.number().optional(),
  "emails": zod.array(zod.string()).optional(),
  "mitgliedschaften": zod.array(zod.object({
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolle": zod.enum(['AUSBILDER', 'ANSPRECHPARTNER_STUDIUM', 'SEMINAR_BUCHER', 'AZUBI', 'STUDENT', 'AUFSICHTSRAT']).optional(),
  "buchungsberechtigt": zod.boolean().optional()
})).optional()
})
export const GetPartyPersonenIdKandidatenResponse = zod.array(GetPartyPersonenIdKandidatenResponseItem)

/**
 * @summary Kontexte
 */
export const GetPartyPersonenIdKontexteParams = zod.object({
  "id": zod.number()
})

export const GetPartyPersonenIdKontexteResponseItem = zod.object({
  "art": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "bezeichnung": zod.string().optional(),
  "rollen": zod.array(zod.enum(['AUSBILDER', 'ANSPRECHPARTNER_STUDIUM', 'SEMINAR_BUCHER', 'AZUBI', 'STUDENT', 'AUFSICHTSRAT'])).optional()
})
export const GetPartyPersonenIdKontexteResponse = zod.array(GetPartyPersonenIdKontexteResponseItem)

/**
 * @summary Shop Bestellung
 */
export const postPartyQuellenShopBestellungBodyQuelleRegExp = new RegExp('\\S');
export const postPartyQuellenShopBestellungBodyExterneIdRegExp = new RegExp('\\S');
export const postPartyQuellenShopBestellungBodyKaeuferEmailRegExp = new RegExp('\\S');
export const postPartyQuellenShopBestellungBodyKaeuferNameRegExp = new RegExp('\\S');
export const postPartyQuellenShopBestellungBodyPositionenItemBeschreibungMax = 300;


export const postPartyQuellenShopBestellungBodyPositionenItemBeschreibungRegExp = new RegExp('\\S');

export const postPartyQuellenShopBestellungBodyPositionenItemSteuersatzMin = 0;




export const PostPartyQuellenShopBestellungBody = zod.object({
  "quelle": zod.string().regex(postPartyQuellenShopBestellungBodyQuelleRegExp),
  "externeId": zod.string().regex(postPartyQuellenShopBestellungBodyExterneIdRegExp),
  "zahlungsart": zod.enum(['KARTE', 'RECHNUNG', 'LASTSCHRIFT']),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "kaeuferEmail": zod.string().regex(postPartyQuellenShopBestellungBodyKaeuferEmailRegExp),
  "kaeuferName": zod.string().regex(postPartyQuellenShopBestellungBodyKaeuferNameRegExp),
  "kontextOrganisationId": zod.number().optional(),
  "positionen": zod.array(zod.object({
  "beschreibung": zod.string().max(postPartyQuellenShopBestellungBodyPositionenItemBeschreibungMax).regex(postPartyQuellenShopBestellungBodyPositionenItemBeschreibungRegExp),
  "betragCent": zod.number().min(1).optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']),
  "steuersatz": zod.number().min(postPartyQuellenShopBestellungBodyPositionenItemSteuersatzMin).optional()
})).min(1)
})

export const PostPartyQuellenShopBestellungResponse = zod.unknown()

