/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Entscheide
 */
export const PostPartyReviewsEntscheidungBody = zod.object({
  "art": zod.enum(['FIRMA', 'PERSON']),
  "kandidatId": zod.number(),
  "entscheidung": zod.enum(['NEUANLAGE_BESTAETIGT', 'GEMERGT']),
  "zielId": zod.number().optional()
})

export const PostPartyReviewsEntscheidungResponse = zod.object({
  "id": zod.number().optional(),
  "art": zod.string().optional(),
  "kandidatId": zod.number().optional(),
  "zielId": zod.number().optional(),
  "entscheidung": zod.string().optional(),
  "kiAehnlichkeit": zod.number().optional(),
  "kiEinschaetzung": zod.string().optional(),
  "kiBegruendung": zod.string().optional(),
  "entschiedenVon": zod.string().optional()
})

/**
 * @summary Queue
 */
export const GetPartyReviewsQueueResponseItem = zod.object({
  "art": zod.enum(['FIRMA', 'PERSON']).optional(),
  "kandidatId": zod.number().optional(),
  "bezeichnung": zod.string().optional(),
  "vorschlaege": zod.array(zod.object({
  "zielId": zod.number().optional(),
  "bezeichnung": zod.string().optional(),
  "aehnlichkeit": zod.number().optional(),
  "einschaetzung": zod.string().optional(),
  "begruendung": zod.string().optional()
})).optional()
})
export const GetPartyReviewsQueueResponse = zod.array(GetPartyReviewsQueueResponseItem)

