/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  BerufsschuljahrDto,
  ProjektionErgebnis,
  RegistryItemDto,
  SeminarDto,
  StudiengangDto,
  TagungDto
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Registry
 */
export const getBildungAngebote = (

 ) => {
      return http<RegistryItemDto[]>(
      {url: `/bildung/angebote`, method: 'GET'
    },
      );
    }
  /**
 * @summary Projiziere In Shop
 */
export const postBildungAngeboteIdShopProjektion = (
    id: number,
 ) => {
      return http<ProjektionErgebnis>(
      {url: `/bildung/angebote/${id}/shop-projektion`, method: 'POST'
    },
      );
    }
  /**
 * @summary List Berufsschuljahre
 */
export const getBildungBerufsschuljahre = (

 ) => {
      return http<BerufsschuljahrDto[]>(
      {url: `/bildung/berufsschuljahre`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Berufsschuljahr
 */
export const postBildungBerufsschuljahre = (
    berufsschuljahrDto: BerufsschuljahrDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/berufsschuljahre`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: berufsschuljahrDto
    },
      );
    }
  /**
 * @summary Update Berufsschuljahr
 */
export const putBildungBerufsschuljahreId = (
    id: number,
    berufsschuljahrDto: BerufsschuljahrDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/berufsschuljahre/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: berufsschuljahrDto
    },
      );
    }
  /**
 * @summary Get Berufsschuljahr
 */
export const getBildungBerufsschuljahreId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/berufsschuljahre/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Archive Berufsschuljahr
 */
export const deleteBildungBerufsschuljahreId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/berufsschuljahre/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary List Seminare
 */
export const getBildungSeminare = (

 ) => {
      return http<SeminarDto[]>(
      {url: `/bildung/seminare`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Seminar
 */
export const postBildungSeminare = (
    seminarDto: SeminarDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/seminare`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: seminarDto
    },
      );
    }
  /**
 * @summary Update Seminar
 */
export const putBildungSeminareId = (
    id: number,
    seminarDto: SeminarDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/seminare/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: seminarDto
    },
      );
    }
  /**
 * @summary Get Seminar
 */
export const getBildungSeminareId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/seminare/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Archive Seminar
 */
export const deleteBildungSeminareId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/seminare/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary List Studiengaenge
 */
export const getBildungStudiengaenge = (

 ) => {
      return http<StudiengangDto[]>(
      {url: `/bildung/studiengaenge`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Studiengang
 */
export const postBildungStudiengaenge = (
    studiengangDto: StudiengangDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/studiengaenge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: studiengangDto
    },
      );
    }
  /**
 * @summary Update Studiengang
 */
export const putBildungStudiengaengeId = (
    id: number,
    studiengangDto: StudiengangDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/studiengaenge/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: studiengangDto
    },
      );
    }
  /**
 * @summary Get Studiengang
 */
export const getBildungStudiengaengeId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/studiengaenge/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Archive Studiengang
 */
export const deleteBildungStudiengaengeId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/studiengaenge/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary List Tagungen
 */
export const getBildungTagungen = (

 ) => {
      return http<TagungDto[]>(
      {url: `/bildung/tagungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Tagung
 */
export const postBildungTagungen = (
    tagungDto: TagungDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/tagungen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tagungDto
    },
      );
    }
  /**
 * @summary Update Tagung
 */
export const putBildungTagungenId = (
    id: number,
    tagungDto: TagungDto,
 ) => {
      return http<unknown>(
      {url: `/bildung/tagungen/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: tagungDto
    },
      );
    }
  /**
 * @summary Get Tagung
 */
export const getBildungTagungenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/tagungen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Archive Tagung
 */
export const deleteBildungTagungenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/bildung/tagungen/${id}`, method: 'DELETE'
    },
      );
    }
  export type GetBildungAngeboteResult = NonNullable<Awaited<ReturnType<typeof getBildungAngebote>>>
export type PostBildungAngeboteIdShopProjektionResult = NonNullable<Awaited<ReturnType<typeof postBildungAngeboteIdShopProjektion>>>
export type GetBildungBerufsschuljahreResult = NonNullable<Awaited<ReturnType<typeof getBildungBerufsschuljahre>>>
export type PostBildungBerufsschuljahreResult = NonNullable<Awaited<ReturnType<typeof postBildungBerufsschuljahre>>>
export type PutBildungBerufsschuljahreIdResult = NonNullable<Awaited<ReturnType<typeof putBildungBerufsschuljahreId>>>
export type GetBildungBerufsschuljahreIdResult = NonNullable<Awaited<ReturnType<typeof getBildungBerufsschuljahreId>>>
export type DeleteBildungBerufsschuljahreIdResult = NonNullable<Awaited<ReturnType<typeof deleteBildungBerufsschuljahreId>>>
export type GetBildungSeminareResult = NonNullable<Awaited<ReturnType<typeof getBildungSeminare>>>
export type PostBildungSeminareResult = NonNullable<Awaited<ReturnType<typeof postBildungSeminare>>>
export type PutBildungSeminareIdResult = NonNullable<Awaited<ReturnType<typeof putBildungSeminareId>>>
export type GetBildungSeminareIdResult = NonNullable<Awaited<ReturnType<typeof getBildungSeminareId>>>
export type DeleteBildungSeminareIdResult = NonNullable<Awaited<ReturnType<typeof deleteBildungSeminareId>>>
export type GetBildungStudiengaengeResult = NonNullable<Awaited<ReturnType<typeof getBildungStudiengaenge>>>
export type PostBildungStudiengaengeResult = NonNullable<Awaited<ReturnType<typeof postBildungStudiengaenge>>>
export type PutBildungStudiengaengeIdResult = NonNullable<Awaited<ReturnType<typeof putBildungStudiengaengeId>>>
export type GetBildungStudiengaengeIdResult = NonNullable<Awaited<ReturnType<typeof getBildungStudiengaengeId>>>
export type DeleteBildungStudiengaengeIdResult = NonNullable<Awaited<ReturnType<typeof deleteBildungStudiengaengeId>>>
export type GetBildungTagungenResult = NonNullable<Awaited<ReturnType<typeof getBildungTagungen>>>
export type PostBildungTagungenResult = NonNullable<Awaited<ReturnType<typeof postBildungTagungen>>>
export type PutBildungTagungenIdResult = NonNullable<Awaited<ReturnType<typeof putBildungTagungenId>>>
export type GetBildungTagungenIdResult = NonNullable<Awaited<ReturnType<typeof getBildungTagungenId>>>
export type DeleteBildungTagungenIdResult = NonNullable<Awaited<ReturnType<typeof deleteBildungTagungenId>>>
