/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AktivitaetInput,
  AktivitaetView,
  DublettenKandidat,
  DublettenPruefInput,
  EinwilligungInput,
  EinwilligungView,
  GetCrmOrganisationenParams,
  GetCrmPersonenParams,
  GetCrmSucheParams,
  KontaktpunktInput,
  KontaktpunktView,
  LookupView,
  MitgliedschaftInput,
  MitgliedschaftView,
  OrgDetail,
  OrganisationInput,
  PageViewOrgListItem,
  PageViewPersonListItem,
  PersonDetail,
  PersonInput,
  Treffer,
  WeiterbildungInput,
  WeiterbildungKontoView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Aktivitaet Anlegen
 */
export const postCrmAktivitaeten = (
    aktivitaetInput: AktivitaetInput,
 ) => {
      return http<unknown>(
      {url: `/crm/aktivitaeten`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: aktivitaetInput
    },
      );
    }
  /**
 * @summary Dubletten Pruefung
 */
export const postCrmDublettenPruefung = (
    dublettenPruefInput: DublettenPruefInput,
 ) => {
      return http<DublettenKandidat[]>(
      {url: `/crm/dubletten-pruefung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dublettenPruefInput
    },
      );
    }
  /**
 * @summary Einwilligung Anlegen
 */
export const postCrmEinwilligungen = (
    einwilligungInput: EinwilligungInput,
 ) => {
      return http<unknown>(
      {url: `/crm/einwilligungen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: einwilligungInput
    },
      );
    }
  /**
 * @summary Einwilligung Erteilen
 */
export const postCrmEinwilligungenIdErteilen = (
    id: number,
 ) => {
      return http<EinwilligungView>(
      {url: `/crm/einwilligungen/${id}/erteilen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Einwilligung Widerrufen
 */
export const postCrmEinwilligungenIdWiderrufen = (
    id: number,
 ) => {
      return http<EinwilligungView>(
      {url: `/crm/einwilligungen/${id}/widerrufen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Kontaktpunkt Anlegen
 */
export const postCrmKontaktpunkte = (
    kontaktpunktInput: KontaktpunktInput,
 ) => {
      return http<unknown>(
      {url: `/crm/kontaktpunkte`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: kontaktpunktInput
    },
      );
    }
  /**
 * @summary Kontaktpunkt Loeschen
 */
export const deleteCrmKontaktpunkteId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/crm/kontaktpunkte/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Kontaktpunkt Aendern
 */
export const putCrmKontaktpunkteId = (
    id: number,
    kontaktpunktInput: KontaktpunktInput,
 ) => {
      return http<KontaktpunktView>(
      {url: `/crm/kontaktpunkte/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: kontaktpunktInput
    },
      );
    }
  /**
 * @summary Lookups
 */
export const getCrmLookupsKategorie = (
    kategorie: string,
 ) => {
      return http<LookupView[]>(
      {url: `/crm/lookups/${kategorie}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Mitgliedschaft Aendern
 */
export const putCrmMitgliedschaftenId = (
    id: number,
    mitgliedschaftInput: MitgliedschaftInput,
 ) => {
      return http<MitgliedschaftView>(
      {url: `/crm/mitgliedschaften/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: mitgliedschaftInput
    },
      );
    }
  /**
 * @summary Ausscheiden
 */
export const postCrmMitgliedschaftenIdAusscheiden = (
    id: number,
 ) => {
      return http<MitgliedschaftView>(
      {url: `/crm/mitgliedschaften/${id}/ausscheiden`, method: 'POST'
    },
      );
    }
  /**
 * @summary Organisationen
 */
export const getCrmOrganisationen = (
    params?: GetCrmOrganisationenParams,
 ) => {
      return http<PageViewOrgListItem>(
      {url: `/crm/organisationen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Organisation Anlegen
 */
export const postCrmOrganisationen = (
    organisationInput: OrganisationInput,
 ) => {
      return http<unknown>(
      {url: `/crm/organisationen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: organisationInput
    },
      );
    }
  /**
 * @summary Organisation Aendern
 */
export const putCrmOrganisationenId = (
    id: number,
    organisationInput: OrganisationInput,
 ) => {
      return http<OrgDetail>(
      {url: `/crm/organisationen/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: organisationInput
    },
      );
    }
  /**
 * @summary Organisation
 */
export const getCrmOrganisationenId = (
    id: number,
 ) => {
      return http<OrgDetail>(
      {url: `/crm/organisationen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Organisation Aktivitaeten
 */
export const getCrmOrganisationenIdAktivitaeten = (
    id: number,
 ) => {
      return http<AktivitaetView[]>(
      {url: `/crm/organisationen/${id}/aktivitaeten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Personen
 */
export const getCrmPersonen = (
    params?: GetCrmPersonenParams,
 ) => {
      return http<PageViewPersonListItem>(
      {url: `/crm/personen`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Person Anlegen
 */
export const postCrmPersonen = (
    personInput: PersonInput,
 ) => {
      return http<unknown>(
      {url: `/crm/personen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: personInput
    },
      );
    }
  /**
 * @summary Person Aendern
 */
export const putCrmPersonenId = (
    id: number,
    personInput: PersonInput,
 ) => {
      return http<PersonDetail>(
      {url: `/crm/personen/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: personInput
    },
      );
    }
  /**
 * @summary Person
 */
export const getCrmPersonenId = (
    id: number,
 ) => {
      return http<PersonDetail>(
      {url: `/crm/personen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Person Aktivitaeten
 */
export const getCrmPersonenIdAktivitaeten = (
    id: number,
 ) => {
      return http<AktivitaetView[]>(
      {url: `/crm/personen/${id}/aktivitaeten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Person Einwilligungen
 */
export const getCrmPersonenIdEinwilligungen = (
    id: number,
 ) => {
      return http<EinwilligungView[]>(
      {url: `/crm/personen/${id}/einwilligungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Person Weiterbildung
 */
export const getCrmPersonenIdWeiterbildung = (
    id: number,
 ) => {
      return http<WeiterbildungKontoView>(
      {url: `/crm/personen/${id}/weiterbildung`, method: 'GET'
    },
      );
    }
  /**
 * @summary Mitgliedschaft Anlegen
 */
export const postCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaften = (
    personId: number,
    orgId: number,
    mitgliedschaftInput: MitgliedschaftInput,
 ) => {
      return http<unknown>(
      {url: `/crm/personen/${personId}/organisationen/${orgId}/mitgliedschaften`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mitgliedschaftInput
    },
      );
    }
  /**
 * @summary Suche
 */
export const getCrmSuche = (
    params?: GetCrmSucheParams,
 ) => {
      return http<Treffer[]>(
      {url: `/crm/suche`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Weiterbildung Anlegen
 */
export const postCrmWeiterbildung = (
    weiterbildungInput: WeiterbildungInput,
 ) => {
      return http<unknown>(
      {url: `/crm/weiterbildung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: weiterbildungInput
    },
      );
    }
  /**
 * @summary Weiterbildung Loeschen
 */
export const deleteCrmWeiterbildungId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/crm/weiterbildung/${id}`, method: 'DELETE'
    },
      );
    }
  export type PostCrmAktivitaetenResult = NonNullable<Awaited<ReturnType<typeof postCrmAktivitaeten>>>
export type PostCrmDublettenPruefungResult = NonNullable<Awaited<ReturnType<typeof postCrmDublettenPruefung>>>
export type PostCrmEinwilligungenResult = NonNullable<Awaited<ReturnType<typeof postCrmEinwilligungen>>>
export type PostCrmEinwilligungenIdErteilenResult = NonNullable<Awaited<ReturnType<typeof postCrmEinwilligungenIdErteilen>>>
export type PostCrmEinwilligungenIdWiderrufenResult = NonNullable<Awaited<ReturnType<typeof postCrmEinwilligungenIdWiderrufen>>>
export type PostCrmKontaktpunkteResult = NonNullable<Awaited<ReturnType<typeof postCrmKontaktpunkte>>>
export type DeleteCrmKontaktpunkteIdResult = NonNullable<Awaited<ReturnType<typeof deleteCrmKontaktpunkteId>>>
export type PutCrmKontaktpunkteIdResult = NonNullable<Awaited<ReturnType<typeof putCrmKontaktpunkteId>>>
export type GetCrmLookupsKategorieResult = NonNullable<Awaited<ReturnType<typeof getCrmLookupsKategorie>>>
export type PutCrmMitgliedschaftenIdResult = NonNullable<Awaited<ReturnType<typeof putCrmMitgliedschaftenId>>>
export type PostCrmMitgliedschaftenIdAusscheidenResult = NonNullable<Awaited<ReturnType<typeof postCrmMitgliedschaftenIdAusscheiden>>>
export type GetCrmOrganisationenResult = NonNullable<Awaited<ReturnType<typeof getCrmOrganisationen>>>
export type PostCrmOrganisationenResult = NonNullable<Awaited<ReturnType<typeof postCrmOrganisationen>>>
export type PutCrmOrganisationenIdResult = NonNullable<Awaited<ReturnType<typeof putCrmOrganisationenId>>>
export type GetCrmOrganisationenIdResult = NonNullable<Awaited<ReturnType<typeof getCrmOrganisationenId>>>
export type GetCrmOrganisationenIdAktivitaetenResult = NonNullable<Awaited<ReturnType<typeof getCrmOrganisationenIdAktivitaeten>>>
export type GetCrmPersonenResult = NonNullable<Awaited<ReturnType<typeof getCrmPersonen>>>
export type PostCrmPersonenResult = NonNullable<Awaited<ReturnType<typeof postCrmPersonen>>>
export type PutCrmPersonenIdResult = NonNullable<Awaited<ReturnType<typeof putCrmPersonenId>>>
export type GetCrmPersonenIdResult = NonNullable<Awaited<ReturnType<typeof getCrmPersonenId>>>
export type GetCrmPersonenIdAktivitaetenResult = NonNullable<Awaited<ReturnType<typeof getCrmPersonenIdAktivitaeten>>>
export type GetCrmPersonenIdEinwilligungenResult = NonNullable<Awaited<ReturnType<typeof getCrmPersonenIdEinwilligungen>>>
export type GetCrmPersonenIdWeiterbildungResult = NonNullable<Awaited<ReturnType<typeof getCrmPersonenIdWeiterbildung>>>
export type PostCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenResult = NonNullable<Awaited<ReturnType<typeof postCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaften>>>
export type GetCrmSucheResult = NonNullable<Awaited<ReturnType<typeof getCrmSuche>>>
export type PostCrmWeiterbildungResult = NonNullable<Awaited<ReturnType<typeof postCrmWeiterbildung>>>
export type DeleteCrmWeiterbildungIdResult = NonNullable<Awaited<ReturnType<typeof deleteCrmWeiterbildungId>>>
