/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Schueler
 */
export const GetMockWebuntisSchuelerResponseItem = zod.object({
  "name": zod.string().optional(),
  "email": zod.string().optional(),
  "klasse": zod.string().optional(),
  "importiertAm": zod.string().datetime({"offset":true}).optional()
})
export const GetMockWebuntisSchuelerResponse = zod.array(GetMockWebuntisSchuelerResponseItem)

/**
 * @summary Status
 */
export const GetMockWebuntisStatusResponse = zod.unknown()

/**
 * @summary Verfuegbarkeit
 */
export const PostMockWebuntisVerfuegbarkeitQueryParams = zod.object({
  "verfuegbar": zod.boolean().optional()
})

export const PostMockWebuntisVerfuegbarkeitResponse = zod.unknown()

