/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  ProjektionErgebnis,
  WbtKursDto
} from '../../model';

import { http } from '../../http';



  /**
 * @summary List
 */
export const getLmsKurse = (

 ) => {
      return http<WbtKursDto[]>(
      {url: `/lms/kurse`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create
 */
export const postLmsKurse = (
    wbtKursDto: WbtKursDto,
 ) => {
      return http<unknown>(
      {url: `/lms/kurse`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wbtKursDto
    },
      );
    }
  /**
 * @summary Update
 */
export const putLmsKurseId = (
    id: number,
    wbtKursDto: WbtKursDto,
 ) => {
      return http<unknown>(
      {url: `/lms/kurse/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: wbtKursDto
    },
      );
    }
  /**
 * @summary Get
 */
export const getLmsKurseId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/lms/kurse/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Archive
 */
export const deleteLmsKurseId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/lms/kurse/${id}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Veroeffentlichen
 */
export const postLmsKurseIdVeroeffentlichen = (
    id: number,
 ) => {
      return http<ProjektionErgebnis>(
      {url: `/lms/kurse/${id}/veroeffentlichen`, method: 'POST'
    },
      );
    }
  export type GetLmsKurseResult = NonNullable<Awaited<ReturnType<typeof getLmsKurse>>>
export type PostLmsKurseResult = NonNullable<Awaited<ReturnType<typeof postLmsKurse>>>
export type PutLmsKurseIdResult = NonNullable<Awaited<ReturnType<typeof putLmsKurseId>>>
export type GetLmsKurseIdResult = NonNullable<Awaited<ReturnType<typeof getLmsKurseId>>>
export type DeleteLmsKurseIdResult = NonNullable<Awaited<ReturnType<typeof deleteLmsKurseId>>>
export type PostLmsKurseIdVeroeffentlichenResult = NonNullable<Awaited<ReturnType<typeof postLmsKurseIdVeroeffentlichen>>>
