/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface AktivitaetView {
  id?: number;
  typCode?: string;
  typ?: string;
  richtung?: string;
  betreff?: string;
  inhaltHtml?: string;
  personId?: number;
  person?: string;
  organisationId?: number;
  organisation?: string;
  zeitpunkt?: LocalDateTime;
  dauerMinuten?: number;
}
