/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Instant } from './instant';

export interface AuftragView {
  id?: number;
  anmeldungId?: number;
  teilnehmerName?: string;
  zielsystem?: string;
  ereignis?: string;
  status?: string;
  versuche?: number;
  naechsterVersuchAm?: Instant;
  letzterFehler?: string;
  erstelltAm?: Instant;
  erledigtAm?: Instant;
}
