/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface Buchungssatz {
  umsatzCent?: number;
  sollHaben?: string;
  konto?: string;
  gegenkonto?: string;
  buSchluessel?: string;
  belegdatum?: LocalDate;
  belegfeld1?: string;
  buchungstext?: string;
}
