/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export enum EinschreibungStatus {
  ANGEFORDERT= 'ANGEFORDERT',
  EINGESCHRIEBEN= 'EINGESCHRIEBEN',
  FEHLGESCHLAGEN= 'FEHLGESCHLAGEN',
  STORNO_ANGEFORDERT= 'STORNO_ANGEFORDERT',
  AUSGESCHRIEBEN= 'AUSGESCHRIEBEN',

}