/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface EinwilligungView {
  id?: number;
  kanal?: string;
  zweck?: string;
  status?: string;
  rechtsgrundlage?: string;
  quelleCode?: string;
  organisationId?: number;
  organisation?: string;
  ausstehendSeit?: LocalDateTime;
  erteiltAm?: LocalDateTime;
  widerrufenAm?: LocalDateTime;
}
