/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Bereich1 } from './bereich1';

export type GetPartyPersonenIdDebitorParams = {
bereich?: Bereich1;
organisationId?: number;
};
