/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { DeliveryType } from './deliveryType';
import type { EnrichedBy } from './enrichedBy';
import type { Instant } from './instant';
import type { SeminarKategorie1 } from './seminarKategorie1';

export interface HubSpotDeal {
  dealId?: string;
  dealName?: string;
  companyRaw?: string;
  amountCents?: number;
  currency?: string;
  stage?: string;
  pipeline?: string;
  sourceModifiedAt?: Instant;
  companyNormalized?: string;
  seminarKategorie?: SeminarKategorie1;
  deliveryType?: DeliveryType;
  konfidenz?: number;
  enrichedBy?: EnrichedBy;
  modelId?: string;
  promptVersion?: string;
  enrichedAt?: Instant;
  reviewRequired?: boolean;
  contentHash?: string;
  ingestedAt?: Instant;
}
