/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface IngestionResult {
  fetched?: number;
  skipped?: number;
  upserted?: number;
  reused?: number;
  viaLlm?: number;
  viaFallback?: number;
  reviewRequired?: number;
}
