/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface KontaktpunktInput {
  /** @pattern \S */
  typ: string;
  personId?: number;
  organisationId?: number;
  mitgliedschaftId?: number;
  label?: string;
  primaer?: boolean;
  email?: string;
  nummerE164?: string;
  nummerAnzeige?: string;
  telefonart?: string;
  strasse?: string;
  hausnummer?: string;
  adresszusatz?: string;
  plz?: string;
  ort?: string;
  region?: string;
  landCode?: string;
  auslandsblock?: string;
}
