/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface MitgliedschaftInput {
  /** @pattern \S */
  rolleCode: string;
  position?: string;
  abteilung?: string;
  hauptzugehoerigkeit?: boolean;
  hauptansprechpartner?: boolean;
  buchungsberechtigt?: boolean;
  rechnungsempfaenger?: boolean;
  gueltigVon?: LocalDate;
  gueltigBis?: LocalDate;
}
