/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface MitgliedschaftView {
  id?: number;
  organisationId?: number;
  organisation?: string;
  rolleCode?: string;
  rolle?: string;
  position?: string;
  abteilung?: string;
  hauptzugehoerigkeit?: boolean;
  hauptansprechpartner?: boolean;
  buchungsberechtigt?: boolean;
  rechnungsempfaenger?: boolean;
  gueltigVon?: LocalDate;
  gueltigBis?: LocalDate;
}
