/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface OrganisationDto {
  /** @pattern \S */
  name: string;
  strasse?: string;
  plz?: string;
  ort?: string;
  land?: string;
  ustId?: string;
}
