/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface OrganisationInput {
  /** @pattern \S */
  name: string;
  rechtsform?: string;
  handelsregisternummer?: string;
  registergericht?: string;
  brancheCode?: string;
  website?: string;
  ustId?: string;
  uebergeordneteId?: number;
  bestandsgroesse?: number;
  gewerbeerlaubnis?: string;
  gewerbeerlaubnisBehoerde?: string;
  gewerbeerlaubnisDatum?: LocalDate;
  ausbildungsbetrieb?: boolean;
  ihkKammerCode?: string;
  leadQuelleCode?: string;
  unternehmenstypCodes?: string[];
  schwerpunktCodes?: string[];
  verbandCodes?: string[];
}
