/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { PersonListItem } from './personListItem';

export interface PageViewPersonListItem {
  items?: PersonListItem[];
  total?: number;
  page?: number;
  size?: number;
}
