/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { KontaktpunktView } from './kontaktpunktView';
import type { LocalDate } from './localDate';
import type { MitgliedschaftView } from './mitgliedschaftView';

export interface PersonDetail {
  id?: number;
  vorname?: string;
  nachname?: string;
  anzeigeName?: string;
  geschlecht?: string;
  titel?: string;
  briefanrede?: string;
  geburtsdatum?: LocalDate;
  geburtsort?: string;
  geburtslandCode?: string;
  korrespondenzspracheCode?: string;
  werbesperre?: boolean;
  auskunftssperre?: boolean;
  status?: string;
  loeschStatus?: string;
  emails?: string[];
  kontaktpunkte?: KontaktpunktView[];
  mitgliedschaften?: MitgliedschaftView[];
}
