/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { MitgliedschaftView } from './mitgliedschaftView';

export interface PersonView {
  id?: number;
  keycloakSub?: string;
  anzeigeName?: string;
  plz?: string;
  ort?: string;
  status?: string;
  goldenPersonId?: number;
  emails?: string[];
  mitgliedschaften?: MitgliedschaftView[];
}
