/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface PersonInput {
  /** @pattern \S */
  vorname: string;
  /** @pattern \S */
  nachname: string;
  geschlecht?: string;
  titel?: string;
  geburtsdatum?: LocalDate;
  geburtsort?: string;
  geburtslandCode?: string;
  staatsangehoerigkeit1Code?: string;
  staatsangehoerigkeit2Code?: string;
  korrespondenzspracheCode?: string;
  werbesperre?: boolean;
  auskunftssperre?: boolean;
  leadQuelleCode?: string;
}
