/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Belegart } from './belegart';
import type { Bereich1 } from './bereich1';
import type { Instant } from './instant';
import type { LocalDate } from './localDate';
import type { RechnungPositionDto } from './rechnungPositionDto';
import type { RechnungStatus } from './rechnungStatus';
import type { RechnungVersandStatus } from './rechnungVersandStatus';

export interface RechnungDto {
  id?: number;
  version?: number;
  belegart?: Belegart;
  bereich?: Bereich1;
  nummer?: string;
  debitorId?: number;
  zeitraumBezeichnung?: string;
  ausstellungsdatum?: LocalDate;
  zahlungszielTage?: number;
  status?: RechnungStatus;
  originalRechnungId?: number;
  summeCent?: number;
  versandStatus?: RechnungVersandStatus;
  versendetAm?: Instant;
  versendetAn?: string;
  bezahltAm?: LocalDate;
  zahlbetragCent?: number;
  zahlungsReferenz?: string;
  positionen?: RechnungPositionDto[];
}
