/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface RechnungView {
  id?: number;
  nummer?: string;
  bereich?: string;
  ausstellungsdatum?: LocalDate;
  status?: string;
  summeCent?: number;
  versandStatus?: string;
}
