/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Leistungsart } from './leistungsart';
import type { Steuerfall } from './steuerfall';

export interface RechnungPositionDto {
  id?: number;
  teilnehmerName?: string;
  beschreibung?: string;
  menge?: number;
  einzelbetragCent?: number;
  betragCent?: number;
  steuerfall?: Steuerfall;
  steuersatz?: number;
  befreiungsgrund?: string;
  leistungsart?: Leistungsart;
  herkunft?: string;
}
