/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AngebotStatus } from './angebotStatus';
import type { Bereich } from './bereich';
import type { BildungsangebotTyp } from './bildungsangebotTyp';

export interface RegistryItemDto {
  id?: number;
  typ?: BildungsangebotTyp;
  code?: string;
  titel?: string;
  bereich?: Bereich;
  status?: AngebotStatus;
  shopVerkauf?: boolean;
  vendureProductId?: string;
}
