/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface ReviewView {
  id?: number;
  art?: string;
  kandidatId?: number;
  zielId?: number;
  entscheidung?: string;
  kiAehnlichkeit?: number;
  kiEinschaetzung?: string;
  kiBegruendung?: string;
  entschiedenVon?: string;
}
