/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  PostMockWebuntisVerfuegbarkeitParams,
  Schueler
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Schueler
 */
export const getMockWebuntisSchueler = (

 ) => {
      return http<Schueler[]>(
      {url: `/mock/webuntis/schueler`, method: 'GET'
    },
      );
    }
  /**
 * @summary Status
 */
export const getMockWebuntisStatus = (

 ) => {
      return http<unknown>(
      {url: `/mock/webuntis/status`, method: 'GET'
    },
      );
    }
  /**
 * @summary Verfuegbarkeit
 */
export const postMockWebuntisVerfuegbarkeit = (
    params?: PostMockWebuntisVerfuegbarkeitParams,
 ) => {
      return http<unknown>(
      {url: `/mock/webuntis/verfuegbarkeit`, method: 'POST',
        params
    },
      );
    }
  export type GetMockWebuntisSchuelerResult = NonNullable<Awaited<ReturnType<typeof getMockWebuntisSchueler>>>
export type GetMockWebuntisStatusResult = NonNullable<Awaited<ReturnType<typeof getMockWebuntisStatus>>>
export type PostMockWebuntisVerfuegbarkeitResult = NonNullable<Awaited<ReturnType<typeof postMockWebuntisVerfuegbarkeit>>>
