/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AusbildungsbetriebAnfrage,
  Berufsschulbuchung,
  BuchungZeile,
  DebitorView,
  EinladungView,
  GetPartyPersonenIdDebitorParams,
  Hochschulbuchung,
  KontextView,
  Login,
  MergeRequest,
  OrgMergeRequest,
  OrganisationDto,
  OrganisationView,
  PersonView,
  SelbstRegistrierung,
  ShopBestellung,
  TeilnehmerAnlage
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Anfrage Ausbildungsbetrieb
 */
export const postPartyAnfragenAusbildungsbetrieb = (
    ausbildungsbetriebAnfrage: AusbildungsbetriebAnfrage,
 ) => {
      return http<unknown>(
      {url: `/party/anfragen/ausbildungsbetrieb`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ausbildungsbetriebAnfrage
    },
      );
    }
  /**
 * @summary Buche Berufsschule
 */
export const postPartyBuchungenBerufsschule = (
    berufsschulbuchung: Berufsschulbuchung,
 ) => {
      return http<unknown>(
      {url: `/party/buchungen/berufsschule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: berufsschulbuchung
    },
      );
    }
  /**
 * @summary Buche Hochschule
 */
export const postPartyBuchungenHochschule = (
    hochschulbuchung: Hochschulbuchung,
 ) => {
      return http<unknown>(
      {url: `/party/buchungen/hochschule`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hochschulbuchung
    },
      );
    }
  /**
 * @summary Firmensicht
 */
export const getPartyFirmensichtOrganisationId = (
    organisationId: number,
 ) => {
      return http<unknown>(
      {url: `/party/firmensicht/${organisationId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create Organisation
 */
export const postPartyOrganisationen = (
    organisationDto: OrganisationDto,
 ) => {
      return http<unknown>(
      {url: `/party/organisationen`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: organisationDto
    },
      );
    }
  /**
 * @summary Merge Organisation
 */
export const postPartyOrganisationenMerge = (
    orgMergeRequest: OrgMergeRequest,
 ) => {
      return http<OrganisationView>(
      {url: `/party/organisationen/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: orgMergeRequest
    },
      );
    }
  /**
 * @summary Get Organisation
 */
export const getPartyOrganisationenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/party/organisationen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Organisation Kandidaten
 */
export const getPartyOrganisationenIdKandidaten = (
    id: number,
 ) => {
      return http<OrganisationView[]>(
      {url: `/party/organisationen/${id}/kandidaten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Teilnehmer Anlegen
 */
export const postPartyOrganisationenIdTeilnehmer = (
    id: number,
    teilnehmerAnlage: TeilnehmerAnlage,
 ) => {
      return http<unknown>(
      {url: `/party/organisationen/${id}/teilnehmer`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: teilnehmerAnlage
    },
      );
    }
  /**
 * @summary Login
 */
export const postPartyPersonenLogin = (
    login: Login,
 ) => {
      return http<unknown>(
      {url: `/party/personen/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: login
    },
      );
    }
  /**
 * @summary Merge
 */
export const postPartyPersonenMerge = (
    mergeRequest: MergeRequest,
 ) => {
      return http<PersonView>(
      {url: `/party/personen/merge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mergeRequest
    },
      );
    }
  /**
 * @summary Selbst Registrieren
 */
export const postPartyPersonenSelbstregistrieren = (
    selbstRegistrierung: SelbstRegistrierung,
 ) => {
      return http<unknown>(
      {url: `/party/personen/selbstregistrieren`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: selbstRegistrierung
    },
      );
    }
  /**
 * @summary Get Person
 */
export const getPartyPersonenId = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/party/personen/${id}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Personen Buchungen
 */
export const getPartyPersonenIdBuchungen = (
    id: number,
 ) => {
      return http<BuchungZeile[]>(
      {url: `/party/personen/${id}/buchungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Debitor
 */
export const getPartyPersonenIdDebitor = (
    id: number,
    params?: GetPartyPersonenIdDebitorParams,
 ) => {
      return http<DebitorView>(
      {url: `/party/personen/${id}/debitor`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Einladung
 */
export const postPartyPersonenIdEinladung = (
    id: number,
 ) => {
      return http<EinladungView>(
      {url: `/party/personen/${id}/einladung`, method: 'POST'
    },
      );
    }
  /**
 * @summary Kandidaten
 */
export const getPartyPersonenIdKandidaten = (
    id: number,
 ) => {
      return http<PersonView[]>(
      {url: `/party/personen/${id}/kandidaten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Kontexte
 */
export const getPartyPersonenIdKontexte = (
    id: number,
 ) => {
      return http<KontextView[]>(
      {url: `/party/personen/${id}/kontexte`, method: 'GET'
    },
      );
    }
  /**
 * @summary Shop Bestellung
 */
export const postPartyQuellenShopBestellung = (
    shopBestellung: ShopBestellung,
 ) => {
      return http<unknown>(
      {url: `/party/quellen/shop-bestellung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shopBestellung
    },
      );
    }
  export type PostPartyAnfragenAusbildungsbetriebResult = NonNullable<Awaited<ReturnType<typeof postPartyAnfragenAusbildungsbetrieb>>>
export type PostPartyBuchungenBerufsschuleResult = NonNullable<Awaited<ReturnType<typeof postPartyBuchungenBerufsschule>>>
export type PostPartyBuchungenHochschuleResult = NonNullable<Awaited<ReturnType<typeof postPartyBuchungenHochschule>>>
export type GetPartyFirmensichtOrganisationIdResult = NonNullable<Awaited<ReturnType<typeof getPartyFirmensichtOrganisationId>>>
export type PostPartyOrganisationenResult = NonNullable<Awaited<ReturnType<typeof postPartyOrganisationen>>>
export type PostPartyOrganisationenMergeResult = NonNullable<Awaited<ReturnType<typeof postPartyOrganisationenMerge>>>
export type GetPartyOrganisationenIdResult = NonNullable<Awaited<ReturnType<typeof getPartyOrganisationenId>>>
export type GetPartyOrganisationenIdKandidatenResult = NonNullable<Awaited<ReturnType<typeof getPartyOrganisationenIdKandidaten>>>
export type PostPartyOrganisationenIdTeilnehmerResult = NonNullable<Awaited<ReturnType<typeof postPartyOrganisationenIdTeilnehmer>>>
export type PostPartyPersonenLoginResult = NonNullable<Awaited<ReturnType<typeof postPartyPersonenLogin>>>
export type PostPartyPersonenMergeResult = NonNullable<Awaited<ReturnType<typeof postPartyPersonenMerge>>>
export type PostPartyPersonenSelbstregistrierenResult = NonNullable<Awaited<ReturnType<typeof postPartyPersonenSelbstregistrieren>>>
export type GetPartyPersonenIdResult = NonNullable<Awaited<ReturnType<typeof getPartyPersonenId>>>
export type GetPartyPersonenIdBuchungenResult = NonNullable<Awaited<ReturnType<typeof getPartyPersonenIdBuchungen>>>
export type GetPartyPersonenIdDebitorResult = NonNullable<Awaited<ReturnType<typeof getPartyPersonenIdDebitor>>>
export type PostPartyPersonenIdEinladungResult = NonNullable<Awaited<ReturnType<typeof postPartyPersonenIdEinladung>>>
export type GetPartyPersonenIdKandidatenResult = NonNullable<Awaited<ReturnType<typeof getPartyPersonenIdKandidaten>>>
export type GetPartyPersonenIdKontexteResult = NonNullable<Awaited<ReturnType<typeof getPartyPersonenIdKontexte>>>
export type PostPartyQuellenShopBestellungResult = NonNullable<Awaited<ReturnType<typeof postPartyQuellenShopBestellung>>>
