/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface AktivitaetInput {
  /** @pattern \S */
  typCode: string;
  richtung?: string;
  /** @pattern \S */
  betreff: string;
  inhaltHtml?: string;
  personId?: number;
  organisationId?: number;
  dauerMinuten?: number;
}
