/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface Anforderung {
  /** @pattern \S */
  keycloakSub: string;
  email?: string;
  anzeigeName?: string;
  vendureOrderId?: string;
  /** @minItems 1 */
  wbtKursIds: number[];
}
