/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface AnmeldungView {
  id?: number;
  typ?: string;
  teilnehmerName?: string;
  status?: string;
  zeitraum?: string;
  betragCent?: number;
  kontextOrganisationId?: number;
  kontextOrganisation?: string;
}
