/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface AnrufEvent {
  nummerE164?: string;
  bekannt?: boolean;
  personId?: number;
  personName?: string;
  organisationId?: number;
  organisationName?: string;
  zeitpunkt?: string;
}
