/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface BestaetigungReportView {
  ereignisId?: number;
  personId?: number;
  personName?: string;
  betreff?: string;
  zeitpunkt?: LocalDateTime;
  bestaetigenBis?: LocalDateTime;
  bestaetigtAm?: LocalDateTime;
  eskaliertAm?: LocalDateTime;
  erinnerungen?: number;
  status?: string;
}
