/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { DebitorAnlageDto } from './debitorAnlageDto';

export interface BestandImportDto {
  /**
     * @maxLength 40
     * @pattern \S
     */
  quelle: string;
  /**
     * @maxLength 64
     * @pattern \S
     */
  externeNr: string;
  debitor: DebitorAnlageDto;
}
