/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Bereich1 } from './bereich1';
import type { DebitorRolle } from './debitorRolle';

export interface DebitorDto {
  id?: number;
  version?: number;
  /** @pattern ^[A-Z0-9-]{2,32}$ */
  debitorNr: string;
  bereich: Bereich1;
  rolle: DebitorRolle;
  /**
     * @maxLength 200
     * @pattern \S
     */
  name: string;
  /** @maxLength 200 */
  strasse?: string;
  /** @maxLength 10 */
  plz?: string;
  /** @maxLength 120 */
  ort?: string;
  /** @maxLength 2 */
  land?: string;
  /** @maxLength 20 */
  ustId?: string;
  /** @maxLength 34 */
  iban?: string;
  /** @maxLength 200 */
  email?: string;
  status?: string;
  goldenDebitorId?: number;
}
