/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface DublettenKandidat {
  art?: string;
  id?: number;
  bezeichnung?: string;
  ort?: string;
  aehnlichkeit?: number;
  einschaetzung?: string;
  begruendung?: string;
}
