/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { EinschreibungStatus } from './einschreibungStatus';

export interface EinschreibungDto {
  id?: number;
  wbtKursId?: number;
  kursTitel?: string;
  keycloakSub?: string;
  email?: string;
  status?: EinschreibungStatus;
  openolatIdentityKey?: number;
  versuche?: number;
  letzterFehler?: string;
}
