/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Art } from './art';
import type { ZielVorschlag } from './zielVorschlag';

export interface Fall {
  art?: Art;
  kandidatId?: number;
  bezeichnung?: string;
  vorschlaege?: ZielVorschlag[];
}
