/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface KontaktpunktView {
  id?: number;
  typ?: string;
  label?: string;
  primaer?: boolean;
  status?: string;
  email?: string;
  nummerAnzeige?: string;
  telefonart?: string;
  strasse?: string;
  hausnummer?: string;
  plz?: string;
  ort?: string;
  region?: string;
  landCode?: string;
}
