/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface KonversationView {
  id?: number;
  typ?: string;
  betreff?: string;
  status?: string;
  kontextTyp?: string;
  kontextId?: number;
  partner?: string;
  letzteVorschau?: string;
  letzteZeit?: LocalDateTime;
  ungelesen?: boolean;
}
