/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { ManuellePositionDto } from './manuellePositionDto';

export interface KorrekturRequest {
  /** @maxLength 200 */
  grund?: string;
  /** @minItems 1 */
  positionen: ManuellePositionDto[];
}
