/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDateTime } from './localDateTime';

export interface NachrichtView {
  id?: number;
  absenderTyp?: string;
  absender?: string;
  kiGeneriert?: boolean;
  inhaltHtml?: string;
  zeitpunkt?: LocalDateTime;
}
