/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { OrgMitgliedView } from './orgMitgliedView';

export interface OrgDetail {
  id?: number;
  name?: string;
  rechtsform?: string;
  handelsregisternummer?: string;
  registergericht?: string;
  brancheCode?: string;
  website?: string;
  ustId?: string;
  uebergeordneteId?: number;
  bestandsgroesse?: number;
  gewerbeerlaubnis?: string;
  ausbildungsbetrieb?: boolean;
  ihkKammerCode?: string;
  unternehmenstypen?: string[];
  taetigkeitsschwerpunkte?: string[];
  verbaende?: string[];
  strasse?: string;
  plz?: string;
  ort?: string;
  status?: string;
  mitglieder?: OrgMitgliedView[];
}
