/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface OrgMitgliedView {
  mitgliedschaftId?: number;
  personId?: number;
  person?: string;
  rolle?: string;
  hauptansprechpartner?: boolean;
  buchungsberechtigt?: boolean;
  gueltigBis?: LocalDate;
}
