/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { OrgListItem } from './orgListItem';

export interface PageViewOrgListItem {
  items?: OrgListItem[];
  total?: number;
  page?: number;
  size?: number;
}
