/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Steuerfall } from './steuerfall';

export interface Position {
  /**
     * @maxLength 300
     * @pattern \S
     */
  beschreibung: string;
  /** @minimum 1 */
  betragCent?: number;
  steuerfall: Steuerfall;
  /** @minimum 0 */
  steuersatz?: number;
}
