/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface RechnungslaufRequest {
  /** @pattern ^\d{4}/\d{4}$ */
  schuljahr: string;
  /**
     * @minimum 1
     * @maximum 2
     */
  halbjahr: number;
}
