/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AngebotStatus } from './angebotStatus';
import type { Bereich } from './bereich';
import type { BildungsangebotTyp } from './bildungsangebotTyp';
import type { LocalDate } from './localDate';
import type { PreisModell } from './preisModell';
import type { SeminarKategorie } from './seminarKategorie';

export interface SeminarDto {
  id?: number;
  version?: number;
  typ?: BildungsangebotTyp;
  /** @pattern ^[A-Z0-9-]{2,32}$ */
  code: string;
  /**
     * @maxLength 200
     * @pattern \S
     */
  titel: string;
  bereich: Bereich;
  /** @maxLength 2000 */
  kurzbeschreibung?: string;
  status: AngebotStatus;
  gueltigAb: LocalDate;
  gueltigBis?: LocalDate;
  /** @maxLength 120 */
  verantwortlich?: string;
  preisModell: PreisModell;
  /** @minimum 0 */
  preisCent?: number;
  /** @minimum 1 */
  abrechnungIntervallMonate?: number;
  /** @minimum 0 */
  ratenGesamt?: number;
  shopVerkauf?: boolean;
  /** @maxLength 64 */
  vendureProductId?: string;
  /** @maxLength 200 */
  zielgruppe?: string;
  kategorie: SeminarKategorie;
  /** @minimum 1 */
  dauerUE?: number;
  /** @maxLength 120 */
  abschluss?: string;
  zertifikat?: boolean;
  /** @minimum 0 */
  minTN?: number;
  /** @minimum 1 */
  maxTN?: number;
}
