/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Bereich1 } from './bereich1';

export interface SonderrechnungDto {
  debitorId: number;
  bereich?: Bereich1;
  zeitraumBezeichnung?: string;
  zahlungszielTage?: number;
}
