/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AnmeldungView } from './anmeldungView';
import type { RechnungView } from './rechnungView';

export interface Uebersicht360View {
  anmeldungen?: AnmeldungView[];
  rechnungen?: RechnungView[];
}
