/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface WbtBestellung {
  /** @pattern \S */
  vendureOrderId: string;
  /** @pattern \S */
  keycloakSub: string;
  email?: string;
  anzeigeName?: string;
  /** @minItems 1 */
  vendureProductIds: string[];
}
