/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { AngebotStatus } from './angebotStatus';
import type { ScormVersion } from './scormVersion';

export interface WbtKursDto {
  id?: number;
  version?: number;
  /** @pattern ^[A-Z0-9-]{2,32}$ */
  code: string;
  /**
     * @maxLength 200
     * @pattern \S
     */
  titel: string;
  /** @maxLength 2000 */
  kurzbeschreibung?: string;
  /** @minimum 1 */
  openolatKey?: number;
  scormVersion?: ScormVersion;
  /** @minimum 0 */
  preisCent?: number;
  shopVerkauf?: boolean;
  status: AngebotStatus;
  /** @maxLength 64 */
  vendureProductId?: string;
}
