/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';

export interface WeiterbildungInput {
  personId: number;
  /** @pattern \S */
  titel: string;
  anbieter?: string;
  stunden: number;
  datum: LocalDate;
  extern?: boolean;
}
