/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { LocalDate } from './localDate';
import type { WeiterbildungView } from './weiterbildungView';

export interface WeiterbildungKontoView {
  zeitraumVon?: LocalDate;
  zeitraumBis?: LocalDate;
  soll?: number;
  summe?: number;
  rest?: number;
  erfuellt?: boolean;
  ampel?: string;
  nachweise?: WeiterbildungView[];
}
