/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Review Queue
 */
export const GetIngestReviewResponseItem = zod.object({
  "dealId": zod.string().optional(),
  "dealName": zod.string().optional(),
  "companyRaw": zod.string().optional(),
  "amountCents": zod.number().optional(),
  "currency": zod.string().optional(),
  "stage": zod.string().optional(),
  "pipeline": zod.string().optional(),
  "sourceModifiedAt": zod.string().datetime({"offset":true}).optional(),
  "companyNormalized": zod.string().optional(),
  "seminarKategorie": zod.enum(['FUEHRUNG', 'FACHKOMPETENZ', 'COMPLIANCE', 'IT_DIGITAL', 'SPRACHEN', 'SONSTIGE', 'UNBEKANNT']).optional(),
  "deliveryType": zod.enum(['INHOUSE', 'OFFEN', 'UNBEKANNT']).optional(),
  "konfidenz": zod.number().optional(),
  "enrichedBy": zod.enum(['LLM', 'FALLBACK']).optional(),
  "modelId": zod.string().optional(),
  "promptVersion": zod.string().optional(),
  "enrichedAt": zod.string().datetime({"offset":true}).optional(),
  "reviewRequired": zod.boolean().optional(),
  "contentHash": zod.string().optional(),
  "ingestedAt": zod.string().datetime({"offset":true}).optional()
})
export const GetIngestReviewResponse = zod.array(GetIngestReviewResponseItem)

/**
 * @summary Run
 */
export const PostIngestRunResponse = zod.object({
  "fetched": zod.number().optional(),
  "skipped": zod.number().optional(),
  "upserted": zod.number().optional(),
  "reused": zod.number().optional(),
  "viaLlm": zod.number().optional(),
  "viaFallback": zod.number().optional(),
  "reviewRequired": zod.number().optional()
})

/**
 * @summary Stats
 */
export const GetIngestStatsResponse = zod.object({
  "total": zod.number().optional(),
  "viaLlm": zod.number().optional(),
  "viaFallback": zod.number().optional()
})

