/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Gruppen
 */
export const GetKommunikationAdminGruppenResponseItem = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "quelle": zod.string().optional(),
  "anzahl": zod.number().optional()
})
export const GetKommunikationAdminGruppenResponse = zod.array(GetKommunikationAdminGruppenResponseItem)

/**
 * @summary Gruppe Anlegen
 */
export const PostKommunikationAdminGruppenBody = zod.object({
  "name": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "quelle": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "bildungsangebotId": zod.number().optional()
})

export const PostKommunikationAdminGruppenResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "quelle": zod.string().optional(),
  "anzahl": zod.number().optional()
})

/**
 * @summary Gruppe Loeschen
 */
export const DeleteKommunikationAdminGruppenIdParams = zod.object({
  "id": zod.number()
})

export const DeleteKommunikationAdminGruppenIdResponse = zod.unknown()

/**
 * @summary Broadcast
 */
export const PostKommunikationAdminGruppenIdBroadcastParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationAdminGruppenIdBroadcastBody = zod.object({
  "nachricht": zod.string().optional()
})

export const PostKommunikationAdminGruppenIdBroadcastResponse = zod.object({
  "erreicht": zod.number().optional()
})

/**
 * @summary Mitglied Hinzu
 */
export const PostKommunikationAdminGruppenIdMitgliederParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationAdminGruppenIdMitgliederBody = zod.object({
  "personId": zod.number().optional()
})

export const PostKommunikationAdminGruppenIdMitgliederResponse = zod.unknown()

/**
 * @summary Mitglied Entfernen
 */
export const DeleteKommunikationAdminGruppenIdMitgliederPersonIdParams = zod.object({
  "id": zod.number(),
  "personId": zod.number()
})

export const DeleteKommunikationAdminGruppenIdMitgliederPersonIdResponse = zod.unknown()

/**
 * @summary Konversationen
 */
export const GetKommunikationAdminKonversationenResponseItem = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "betreff": zod.string().optional(),
  "status": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "partner": zod.string().optional(),
  "letzteVorschau": zod.string().optional(),
  "letzteZeit": zod.string().datetime({"offset":true}).optional(),
  "ungelesen": zod.boolean().optional()
})
export const GetKommunikationAdminKonversationenResponse = zod.array(GetKommunikationAdminKonversationenResponseItem)

/**
 * @summary Entwurf
 */
export const PostKommunikationAdminKonversationenIdEntwurfParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationAdminKonversationenIdEntwurfResponse = zod.object({
  "entwurf": zod.string().optional(),
  "kiGeneriert": zod.boolean().optional()
})

/**
 * @summary Gelesen
 */
export const PostKommunikationAdminKonversationenIdGelesenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationAdminKonversationenIdGelesenResponse = zod.unknown()

/**
 * @summary Nachrichten
 */
export const GetKommunikationAdminKonversationenIdNachrichtenParams = zod.object({
  "id": zod.number()
})

export const GetKommunikationAdminKonversationenIdNachrichtenResponseItem = zod.object({
  "id": zod.number().optional(),
  "absenderTyp": zod.string().optional(),
  "absender": zod.string().optional(),
  "kiGeneriert": zod.boolean().optional(),
  "inhaltHtml": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional()
})
export const GetKommunikationAdminKonversationenIdNachrichtenResponse = zod.array(GetKommunikationAdminKonversationenIdNachrichtenResponseItem)

/**
 * @summary Antworten
 */
export const PostKommunikationAdminKonversationenIdNachrichtenParams = zod.object({
  "id": zod.number()
})

export const PostKommunikationAdminKonversationenIdNachrichtenBody = zod.object({
  "personId": zod.number().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional()
})

export const PostKommunikationAdminKonversationenIdNachrichtenResponse = zod.object({
  "id": zod.number().optional(),
  "absenderTyp": zod.string().optional(),
  "absender": zod.string().optional(),
  "kiGeneriert": zod.boolean().optional(),
  "inhaltHtml": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Eroeffne
 */
export const PostKommunikationAdminVorgaengeBody = zod.object({
  "personId": zod.number().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional()
})

export const PostKommunikationAdminVorgaengeResponse = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "betreff": zod.string().optional(),
  "status": zod.string().optional(),
  "kontextTyp": zod.string().optional(),
  "kontextId": zod.number().optional(),
  "partner": zod.string().optional(),
  "letzteVorschau": zod.string().optional(),
  "letzteZeit": zod.string().datetime({"offset":true}).optional(),
  "ungelesen": zod.boolean().optional()
})

