/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface BuchungZeile {
  anmeldungId?: number;
  teilnehmerName?: string;
  teilnehmerPersonId?: number;
  kontextOrganisationId?: number;
  zahlungspflichtigerDebitorId?: number;
  schuljahr?: string;
  halbjahr?: number;
  status?: string;
}
