/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export enum Kategorie {
  ANMELDUNG= 'ANMELDUNG',
  RECHNUNG= 'RECHNUNG',
  EINSCHREIBUNG= 'EINSCHREIBUNG',
  PRUEFUNG= 'PRUEFUNG',
  SYSTEM= 'SYSTEM',
  INTERN= 'INTERN',

}