/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface MitgliedschaftView1 {
  organisationId?: number;
  organisation?: string;
  rolle?: string;
  buchungsberechtigt?: boolean;
}
