/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export interface OrganisationView {
  id?: number;
  name?: string;
  plz?: string;
  ort?: string;
  ustId?: string;
  status?: string;
  goldenOrganisationId?: number;
}
