/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Belegart } from './belegart';
import type { Bereich1 } from './bereich1';
import type { LocalDate } from './localDate';
import type { RechnungStatus } from './rechnungStatus';

export interface PortalRechnungView {
  id?: number;
  nummer?: string;
  belegart?: Belegart;
  bereich?: Bereich1;
  status?: RechnungStatus;
  ausstellungsdatum?: LocalDate;
  zahlungszielTage?: number;
  summeCent?: number;
  zeitraumBezeichnung?: string;
  empfaengerName?: string;
}
