/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */

export enum Rolle {
  AUSBILDER= 'AUSBILDER',
  ANSPRECHPARTNER_STUDIUM= 'ANSPRECHPARTNER_STUDIUM',
  SEMINAR_BUCHER= 'SEMINAR_BUCHER',
  AZUBI= 'AZUBI',
  STUDENT= 'STUDENT',
  AUFSICHTSRAT= 'AUFSICHTSRAT',

}