/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type { Bereich1 } from './bereich1';
import type { Position } from './position';
import type { Zahlungsart } from './zahlungsart';

export interface ShopBestellung {
  /** @pattern \S */
  quelle: string;
  /** @pattern \S */
  externeId: string;
  zahlungsart: Zahlungsart;
  bereich?: Bereich1;
  /** @pattern \S */
  kaeuferEmail: string;
  /** @pattern \S */
  kaeuferName: string;
  kontextOrganisationId?: number;
  /** @minItems 1 */
  positionen: Position[];
}
