/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Meine Trainings
 */
export const GetLmsPortalTrainingsResponseItem = zod.object({
  "einschreibungId": zod.number().optional(),
  "kursTitel": zod.string().optional(),
  "kursCode": zod.string().optional(),
  "status": zod.enum(['ANGEFORDERT', 'EINGESCHRIEBEN', 'FEHLGESCHLAGEN', 'STORNO_ANGEFORDERT', 'AUSGESCHRIEBEN']).optional(),
  "launchUrl": zod.string().optional()
})
export const GetLmsPortalTrainingsResponse = zod.array(GetLmsPortalTrainingsResponseItem)

