/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List Anmeldungen
 */
export const getRechnungAnmeldungenResponseTeilnehmerNameMax = 200;


export const getRechnungAnmeldungenResponseTeilnehmerNameRegExp = new RegExp('\\S');
export const getRechnungAnmeldungenResponseTeilnehmerEmailMax = 200;

export const getRechnungAnmeldungenResponseSchuljahrRegExp = new RegExp('^\\d{4}/\\d{4}$');
export const getRechnungAnmeldungenResponseHalbjahrMax = 2;

export const getRechnungAnmeldungenResponseUnterrichtBetragCentMin = 0;

export const getRechnungAnmeldungenResponseUebernachtungBetragCentMin = 0;

export const getRechnungAnmeldungenResponseSemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');
export const getRechnungAnmeldungenResponseSemesterbetragCentMin = 0;

export const getRechnungAnmeldungenResponseFirmaAnteilCentMin = 0;

export const getRechnungAnmeldungenResponseRatenAnzahlMax = 12;



export const GetRechnungAnmeldungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE']),
  "teilnehmerName": zod.string().max(getRechnungAnmeldungenResponseTeilnehmerNameMax).regex(getRechnungAnmeldungenResponseTeilnehmerNameRegExp),
  "teilnehmerEmail": zod.string().max(getRechnungAnmeldungenResponseTeilnehmerEmailMax).optional(),
  "bildungsangebotId": zod.number().optional(),
  "zahlungspflichtigerDebitorId": zod.number(),
  "status": zod.enum(['ANGEFRAGT', 'BESTAETIGT_EBZ', 'AKTIV', 'ABGEBROCHEN', 'ABGESCHLOSSEN']),
  "schuljahr": zod.string().regex(getRechnungAnmeldungenResponseSchuljahrRegExp).optional(),
  "halbjahr": zod.number().min(1).max(getRechnungAnmeldungenResponseHalbjahrMax).optional(),
  "zimmerart": zod.enum(['KEINE', 'DOPPEL', 'EINZEL']).optional(),
  "unterrichtBetragCent": zod.number().min(getRechnungAnmeldungenResponseUnterrichtBetragCentMin).optional(),
  "uebernachtungBetragCent": zod.number().min(getRechnungAnmeldungenResponseUebernachtungBetragCentMin).optional(),
  "semester": zod.string().regex(getRechnungAnmeldungenResponseSemesterRegExp).optional(),
  "semesterbetragCent": zod.number().min(getRechnungAnmeldungenResponseSemesterbetragCentMin).optional(),
  "firmaDebitorId": zod.number().optional(),
  "firmaAnteilCent": zod.number().min(getRechnungAnmeldungenResponseFirmaAnteilCentMin).optional(),
  "ratenAnzahl": zod.number().min(1).max(getRechnungAnmeldungenResponseRatenAnzahlMax).optional()
})
export const GetRechnungAnmeldungenResponse = zod.array(GetRechnungAnmeldungenResponseItem)

/**
 * @summary Create Anmeldung
 */
export const postRechnungAnmeldungenBodyTeilnehmerNameMax = 200;


export const postRechnungAnmeldungenBodyTeilnehmerNameRegExp = new RegExp('\\S');
export const postRechnungAnmeldungenBodyTeilnehmerEmailMax = 200;

export const postRechnungAnmeldungenBodySchuljahrRegExp = new RegExp('^\\d{4}/\\d{4}$');
export const postRechnungAnmeldungenBodyHalbjahrMax = 2;

export const postRechnungAnmeldungenBodyUnterrichtBetragCentMin = 0;

export const postRechnungAnmeldungenBodyUebernachtungBetragCentMin = 0;

export const postRechnungAnmeldungenBodySemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');
export const postRechnungAnmeldungenBodySemesterbetragCentMin = 0;

export const postRechnungAnmeldungenBodyFirmaAnteilCentMin = 0;

export const postRechnungAnmeldungenBodyRatenAnzahlMax = 12;



export const PostRechnungAnmeldungenBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE']),
  "teilnehmerName": zod.string().max(postRechnungAnmeldungenBodyTeilnehmerNameMax).regex(postRechnungAnmeldungenBodyTeilnehmerNameRegExp),
  "teilnehmerEmail": zod.string().max(postRechnungAnmeldungenBodyTeilnehmerEmailMax).optional(),
  "bildungsangebotId": zod.number().optional(),
  "zahlungspflichtigerDebitorId": zod.number(),
  "status": zod.enum(['ANGEFRAGT', 'BESTAETIGT_EBZ', 'AKTIV', 'ABGEBROCHEN', 'ABGESCHLOSSEN']),
  "schuljahr": zod.string().regex(postRechnungAnmeldungenBodySchuljahrRegExp).optional(),
  "halbjahr": zod.number().min(1).max(postRechnungAnmeldungenBodyHalbjahrMax).optional(),
  "zimmerart": zod.enum(['KEINE', 'DOPPEL', 'EINZEL']).optional(),
  "unterrichtBetragCent": zod.number().min(postRechnungAnmeldungenBodyUnterrichtBetragCentMin).optional(),
  "uebernachtungBetragCent": zod.number().min(postRechnungAnmeldungenBodyUebernachtungBetragCentMin).optional(),
  "semester": zod.string().regex(postRechnungAnmeldungenBodySemesterRegExp).optional(),
  "semesterbetragCent": zod.number().min(postRechnungAnmeldungenBodySemesterbetragCentMin).optional(),
  "firmaDebitorId": zod.number().optional(),
  "firmaAnteilCent": zod.number().min(postRechnungAnmeldungenBodyFirmaAnteilCentMin).optional(),
  "ratenAnzahl": zod.number().min(1).max(postRechnungAnmeldungenBodyRatenAnzahlMax).optional()
})

export const PostRechnungAnmeldungenResponse = zod.unknown()

/**
 * @summary Update Anmeldung
 */
export const PutRechnungAnmeldungenIdParams = zod.object({
  "id": zod.number()
})

export const putRechnungAnmeldungenIdBodyTeilnehmerNameMax = 200;


export const putRechnungAnmeldungenIdBodyTeilnehmerNameRegExp = new RegExp('\\S');
export const putRechnungAnmeldungenIdBodyTeilnehmerEmailMax = 200;

export const putRechnungAnmeldungenIdBodySchuljahrRegExp = new RegExp('^\\d{4}/\\d{4}$');
export const putRechnungAnmeldungenIdBodyHalbjahrMax = 2;

export const putRechnungAnmeldungenIdBodyUnterrichtBetragCentMin = 0;

export const putRechnungAnmeldungenIdBodyUebernachtungBetragCentMin = 0;

export const putRechnungAnmeldungenIdBodySemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');
export const putRechnungAnmeldungenIdBodySemesterbetragCentMin = 0;

export const putRechnungAnmeldungenIdBodyFirmaAnteilCentMin = 0;

export const putRechnungAnmeldungenIdBodyRatenAnzahlMax = 12;



export const PutRechnungAnmeldungenIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "typ": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE']),
  "teilnehmerName": zod.string().max(putRechnungAnmeldungenIdBodyTeilnehmerNameMax).regex(putRechnungAnmeldungenIdBodyTeilnehmerNameRegExp),
  "teilnehmerEmail": zod.string().max(putRechnungAnmeldungenIdBodyTeilnehmerEmailMax).optional(),
  "bildungsangebotId": zod.number().optional(),
  "zahlungspflichtigerDebitorId": zod.number(),
  "status": zod.enum(['ANGEFRAGT', 'BESTAETIGT_EBZ', 'AKTIV', 'ABGEBROCHEN', 'ABGESCHLOSSEN']),
  "schuljahr": zod.string().regex(putRechnungAnmeldungenIdBodySchuljahrRegExp).optional(),
  "halbjahr": zod.number().min(1).max(putRechnungAnmeldungenIdBodyHalbjahrMax).optional(),
  "zimmerart": zod.enum(['KEINE', 'DOPPEL', 'EINZEL']).optional(),
  "unterrichtBetragCent": zod.number().min(putRechnungAnmeldungenIdBodyUnterrichtBetragCentMin).optional(),
  "uebernachtungBetragCent": zod.number().min(putRechnungAnmeldungenIdBodyUebernachtungBetragCentMin).optional(),
  "semester": zod.string().regex(putRechnungAnmeldungenIdBodySemesterRegExp).optional(),
  "semesterbetragCent": zod.number().min(putRechnungAnmeldungenIdBodySemesterbetragCentMin).optional(),
  "firmaDebitorId": zod.number().optional(),
  "firmaAnteilCent": zod.number().min(putRechnungAnmeldungenIdBodyFirmaAnteilCentMin).optional(),
  "ratenAnzahl": zod.number().min(1).max(putRechnungAnmeldungenIdBodyRatenAnzahlMax).optional()
})

export const PutRechnungAnmeldungenIdResponse = zod.unknown()

/**
 * @summary Get Anmeldung
 */
export const GetRechnungAnmeldungenIdParams = zod.object({
  "id": zod.number()
})

export const GetRechnungAnmeldungenIdResponse = zod.unknown()

/**
 * @summary Abbrechen Anmeldung
 */
export const DeleteRechnungAnmeldungenIdParams = zod.object({
  "id": zod.number()
})

export const DeleteRechnungAnmeldungenIdResponse = zod.unknown()

/**
 * @summary Datev Buchungssaetze
 */
export const GetRechnungDatevBuchungssaetzeQueryParams = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "bis": zod.string().optional(),
  "von": zod.string().optional()
})

export const GetRechnungDatevBuchungssaetzeResponseItem = zod.object({
  "umsatzCent": zod.number().optional(),
  "sollHaben": zod.string().optional(),
  "konto": zod.string().optional(),
  "gegenkonto": zod.string().optional(),
  "buSchluessel": zod.string().optional(),
  "belegdatum": zod.string().date().optional(),
  "belegfeld1": zod.string().optional(),
  "buchungstext": zod.string().optional()
})
export const GetRechnungDatevBuchungssaetzeResponse = zod.array(GetRechnungDatevBuchungssaetzeResponseItem)

/**
 * @summary Datev Buchungsstapel
 */
export const GetRechnungDatevBuchungsstapelQueryParams = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "bis": zod.string().optional(),
  "von": zod.string().optional()
})

export const GetRechnungDatevBuchungsstapelResponse = zod.unknown()

/**
 * @summary Datev Uebergeben
 */
export const PostRechnungDatevUebergabeQueryParams = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "bis": zod.string().optional(),
  "von": zod.string().optional()
})

export const PostRechnungDatevUebergabeResponse = zod.object({
  "modus": zod.string().optional(),
  "referenz": zod.string().optional(),
  "anzahlBuchungen": zod.number().optional(),
  "artefaktBytes": zod.number().optional(),
  "hinweis": zod.string().optional()
})

/**
 * @summary List Debitoren
 */
export const getRechnungDebitorenResponseDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getRechnungDebitorenResponseNameMax = 200;


export const getRechnungDebitorenResponseNameRegExp = new RegExp('\\S');
export const getRechnungDebitorenResponseStrasseMax = 200;

export const getRechnungDebitorenResponsePlzMax = 10;

export const getRechnungDebitorenResponseOrtMax = 120;

export const getRechnungDebitorenResponseLandMax = 2;

export const getRechnungDebitorenResponseUstIdMax = 20;

export const getRechnungDebitorenResponseIbanMax = 34;

export const getRechnungDebitorenResponseEmailMax = 200;



export const GetRechnungDebitorenResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(getRechnungDebitorenResponseDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(getRechnungDebitorenResponseNameMax).regex(getRechnungDebitorenResponseNameRegExp),
  "strasse": zod.string().max(getRechnungDebitorenResponseStrasseMax).optional(),
  "plz": zod.string().max(getRechnungDebitorenResponsePlzMax).optional(),
  "ort": zod.string().max(getRechnungDebitorenResponseOrtMax).optional(),
  "land": zod.string().max(getRechnungDebitorenResponseLandMax).optional(),
  "ustId": zod.string().max(getRechnungDebitorenResponseUstIdMax).optional(),
  "iban": zod.string().max(getRechnungDebitorenResponseIbanMax).optional(),
  "email": zod.string().max(getRechnungDebitorenResponseEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})
export const GetRechnungDebitorenResponse = zod.array(GetRechnungDebitorenResponseItem)

/**
 * @summary Create Debitor
 */
export const postRechnungDebitorenBodyDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postRechnungDebitorenBodyNameMax = 200;


export const postRechnungDebitorenBodyNameRegExp = new RegExp('\\S');
export const postRechnungDebitorenBodyStrasseMax = 200;

export const postRechnungDebitorenBodyPlzMax = 10;

export const postRechnungDebitorenBodyOrtMax = 120;

export const postRechnungDebitorenBodyLandMax = 2;

export const postRechnungDebitorenBodyUstIdMax = 20;

export const postRechnungDebitorenBodyIbanMax = 34;

export const postRechnungDebitorenBodyEmailMax = 200;



export const PostRechnungDebitorenBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(postRechnungDebitorenBodyDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungDebitorenBodyNameMax).regex(postRechnungDebitorenBodyNameRegExp),
  "strasse": zod.string().max(postRechnungDebitorenBodyStrasseMax).optional(),
  "plz": zod.string().max(postRechnungDebitorenBodyPlzMax).optional(),
  "ort": zod.string().max(postRechnungDebitorenBodyOrtMax).optional(),
  "land": zod.string().max(postRechnungDebitorenBodyLandMax).optional(),
  "ustId": zod.string().max(postRechnungDebitorenBodyUstIdMax).optional(),
  "iban": zod.string().max(postRechnungDebitorenBodyIbanMax).optional(),
  "email": zod.string().max(postRechnungDebitorenBodyEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})

export const PostRechnungDebitorenResponse = zod.unknown()

/**
 * @summary Anlegen Debitor
 */
export const postRechnungDebitorenAnlegenBodyNameMax = 200;


export const postRechnungDebitorenAnlegenBodyNameRegExp = new RegExp('\\S');
export const postRechnungDebitorenAnlegenBodyStrasseMax = 200;

export const postRechnungDebitorenAnlegenBodyPlzMax = 10;

export const postRechnungDebitorenAnlegenBodyOrtMax = 120;

export const postRechnungDebitorenAnlegenBodyLandMax = 2;

export const postRechnungDebitorenAnlegenBodyUstIdMax = 20;

export const postRechnungDebitorenAnlegenBodyIbanMax = 34;

export const postRechnungDebitorenAnlegenBodyEmailMax = 200;



export const PostRechnungDebitorenAnlegenBody = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungDebitorenAnlegenBodyNameMax).regex(postRechnungDebitorenAnlegenBodyNameRegExp),
  "strasse": zod.string().max(postRechnungDebitorenAnlegenBodyStrasseMax).optional(),
  "plz": zod.string().max(postRechnungDebitorenAnlegenBodyPlzMax).optional(),
  "ort": zod.string().max(postRechnungDebitorenAnlegenBodyOrtMax).optional(),
  "land": zod.string().max(postRechnungDebitorenAnlegenBodyLandMax).optional(),
  "ustId": zod.string().max(postRechnungDebitorenAnlegenBodyUstIdMax).optional(),
  "iban": zod.string().max(postRechnungDebitorenAnlegenBodyIbanMax).optional(),
  "email": zod.string().max(postRechnungDebitorenAnlegenBodyEmailMax).optional()
})

export const PostRechnungDebitorenAnlegenResponse = zod.unknown()

/**
 * @summary Aufloesen Debitor
 */
export const GetRechnungDebitorenAufloesenQueryParams = zod.object({
  "externeNr": zod.string().optional(),
  "quelle": zod.string().optional()
})

export const GetRechnungDebitorenAufloesenResponse = zod.unknown()

/**
 * @summary Import Debitor
 */
export const postRechnungDebitorenImportBodyQuelleMax = 40;


export const postRechnungDebitorenImportBodyQuelleRegExp = new RegExp('\\S');
export const postRechnungDebitorenImportBodyExterneNrMax = 64;


export const postRechnungDebitorenImportBodyExterneNrRegExp = new RegExp('\\S');
export const postRechnungDebitorenImportBodyDebitorNameMax = 200;


export const postRechnungDebitorenImportBodyDebitorNameRegExp = new RegExp('\\S');
export const postRechnungDebitorenImportBodyDebitorStrasseMax = 200;

export const postRechnungDebitorenImportBodyDebitorPlzMax = 10;

export const postRechnungDebitorenImportBodyDebitorOrtMax = 120;

export const postRechnungDebitorenImportBodyDebitorLandMax = 2;

export const postRechnungDebitorenImportBodyDebitorUstIdMax = 20;

export const postRechnungDebitorenImportBodyDebitorIbanMax = 34;

export const postRechnungDebitorenImportBodyDebitorEmailMax = 200;



export const PostRechnungDebitorenImportBody = zod.object({
  "quelle": zod.string().max(postRechnungDebitorenImportBodyQuelleMax).regex(postRechnungDebitorenImportBodyQuelleRegExp),
  "externeNr": zod.string().max(postRechnungDebitorenImportBodyExterneNrMax).regex(postRechnungDebitorenImportBodyExterneNrRegExp),
  "debitor": zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungDebitorenImportBodyDebitorNameMax).regex(postRechnungDebitorenImportBodyDebitorNameRegExp),
  "strasse": zod.string().max(postRechnungDebitorenImportBodyDebitorStrasseMax).optional(),
  "plz": zod.string().max(postRechnungDebitorenImportBodyDebitorPlzMax).optional(),
  "ort": zod.string().max(postRechnungDebitorenImportBodyDebitorOrtMax).optional(),
  "land": zod.string().max(postRechnungDebitorenImportBodyDebitorLandMax).optional(),
  "ustId": zod.string().max(postRechnungDebitorenImportBodyDebitorUstIdMax).optional(),
  "iban": zod.string().max(postRechnungDebitorenImportBodyDebitorIbanMax).optional(),
  "email": zod.string().max(postRechnungDebitorenImportBodyDebitorEmailMax).optional()
})
})

export const postRechnungDebitorenImportResponseDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postRechnungDebitorenImportResponseNameMax = 200;


export const postRechnungDebitorenImportResponseNameRegExp = new RegExp('\\S');
export const postRechnungDebitorenImportResponseStrasseMax = 200;

export const postRechnungDebitorenImportResponsePlzMax = 10;

export const postRechnungDebitorenImportResponseOrtMax = 120;

export const postRechnungDebitorenImportResponseLandMax = 2;

export const postRechnungDebitorenImportResponseUstIdMax = 20;

export const postRechnungDebitorenImportResponseIbanMax = 34;

export const postRechnungDebitorenImportResponseEmailMax = 200;



export const PostRechnungDebitorenImportResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(postRechnungDebitorenImportResponseDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungDebitorenImportResponseNameMax).regex(postRechnungDebitorenImportResponseNameRegExp),
  "strasse": zod.string().max(postRechnungDebitorenImportResponseStrasseMax).optional(),
  "plz": zod.string().max(postRechnungDebitorenImportResponsePlzMax).optional(),
  "ort": zod.string().max(postRechnungDebitorenImportResponseOrtMax).optional(),
  "land": zod.string().max(postRechnungDebitorenImportResponseLandMax).optional(),
  "ustId": zod.string().max(postRechnungDebitorenImportResponseUstIdMax).optional(),
  "iban": zod.string().max(postRechnungDebitorenImportResponseIbanMax).optional(),
  "email": zod.string().max(postRechnungDebitorenImportResponseEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})

/**
 * @summary Merge Debitoren
 */
export const PostRechnungDebitorenMergeBody = zod.object({
  "quellId": zod.number(),
  "zielId": zod.number()
})

export const postRechnungDebitorenMergeResponseDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postRechnungDebitorenMergeResponseNameMax = 200;


export const postRechnungDebitorenMergeResponseNameRegExp = new RegExp('\\S');
export const postRechnungDebitorenMergeResponseStrasseMax = 200;

export const postRechnungDebitorenMergeResponsePlzMax = 10;

export const postRechnungDebitorenMergeResponseOrtMax = 120;

export const postRechnungDebitorenMergeResponseLandMax = 2;

export const postRechnungDebitorenMergeResponseUstIdMax = 20;

export const postRechnungDebitorenMergeResponseIbanMax = 34;

export const postRechnungDebitorenMergeResponseEmailMax = 200;



export const PostRechnungDebitorenMergeResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(postRechnungDebitorenMergeResponseDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungDebitorenMergeResponseNameMax).regex(postRechnungDebitorenMergeResponseNameRegExp),
  "strasse": zod.string().max(postRechnungDebitorenMergeResponseStrasseMax).optional(),
  "plz": zod.string().max(postRechnungDebitorenMergeResponsePlzMax).optional(),
  "ort": zod.string().max(postRechnungDebitorenMergeResponseOrtMax).optional(),
  "land": zod.string().max(postRechnungDebitorenMergeResponseLandMax).optional(),
  "ustId": zod.string().max(postRechnungDebitorenMergeResponseUstIdMax).optional(),
  "iban": zod.string().max(postRechnungDebitorenMergeResponseIbanMax).optional(),
  "email": zod.string().max(postRechnungDebitorenMergeResponseEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})

/**
 * @summary Update Debitor
 */
export const PutRechnungDebitorenIdParams = zod.object({
  "id": zod.number()
})

export const putRechnungDebitorenIdBodyDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putRechnungDebitorenIdBodyNameMax = 200;


export const putRechnungDebitorenIdBodyNameRegExp = new RegExp('\\S');
export const putRechnungDebitorenIdBodyStrasseMax = 200;

export const putRechnungDebitorenIdBodyPlzMax = 10;

export const putRechnungDebitorenIdBodyOrtMax = 120;

export const putRechnungDebitorenIdBodyLandMax = 2;

export const putRechnungDebitorenIdBodyUstIdMax = 20;

export const putRechnungDebitorenIdBodyIbanMax = 34;

export const putRechnungDebitorenIdBodyEmailMax = 200;



export const PutRechnungDebitorenIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(putRechnungDebitorenIdBodyDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(putRechnungDebitorenIdBodyNameMax).regex(putRechnungDebitorenIdBodyNameRegExp),
  "strasse": zod.string().max(putRechnungDebitorenIdBodyStrasseMax).optional(),
  "plz": zod.string().max(putRechnungDebitorenIdBodyPlzMax).optional(),
  "ort": zod.string().max(putRechnungDebitorenIdBodyOrtMax).optional(),
  "land": zod.string().max(putRechnungDebitorenIdBodyLandMax).optional(),
  "ustId": zod.string().max(putRechnungDebitorenIdBodyUstIdMax).optional(),
  "iban": zod.string().max(putRechnungDebitorenIdBodyIbanMax).optional(),
  "email": zod.string().max(putRechnungDebitorenIdBodyEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})

export const PutRechnungDebitorenIdResponse = zod.unknown()

/**
 * @summary Get Debitor
 */
export const GetRechnungDebitorenIdParams = zod.object({
  "id": zod.number()
})

export const GetRechnungDebitorenIdResponse = zod.unknown()

/**
 * @summary Aliase
 */
export const GetRechnungDebitorenIdAliaseParams = zod.object({
  "id": zod.number()
})

export const GetRechnungDebitorenIdAliaseResponseItem = zod.object({
  "id": zod.number().optional(),
  "debitorId": zod.number().optional(),
  "quelle": zod.string().optional(),
  "externeNr": zod.string().optional()
})
export const GetRechnungDebitorenIdAliaseResponse = zod.array(GetRechnungDebitorenIdAliaseResponseItem)

/**
 * @summary Kandidaten
 */
export const GetRechnungDebitorenIdKandidatenParams = zod.object({
  "id": zod.number()
})

export const getRechnungDebitorenIdKandidatenResponseDebitorNrRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getRechnungDebitorenIdKandidatenResponseNameMax = 200;


export const getRechnungDebitorenIdKandidatenResponseNameRegExp = new RegExp('\\S');
export const getRechnungDebitorenIdKandidatenResponseStrasseMax = 200;

export const getRechnungDebitorenIdKandidatenResponsePlzMax = 10;

export const getRechnungDebitorenIdKandidatenResponseOrtMax = 120;

export const getRechnungDebitorenIdKandidatenResponseLandMax = 2;

export const getRechnungDebitorenIdKandidatenResponseUstIdMax = 20;

export const getRechnungDebitorenIdKandidatenResponseIbanMax = 34;

export const getRechnungDebitorenIdKandidatenResponseEmailMax = 200;



export const GetRechnungDebitorenIdKandidatenResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "debitorNr": zod.string().regex(getRechnungDebitorenIdKandidatenResponseDebitorNrRegExp),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(getRechnungDebitorenIdKandidatenResponseNameMax).regex(getRechnungDebitorenIdKandidatenResponseNameRegExp),
  "strasse": zod.string().max(getRechnungDebitorenIdKandidatenResponseStrasseMax).optional(),
  "plz": zod.string().max(getRechnungDebitorenIdKandidatenResponsePlzMax).optional(),
  "ort": zod.string().max(getRechnungDebitorenIdKandidatenResponseOrtMax).optional(),
  "land": zod.string().max(getRechnungDebitorenIdKandidatenResponseLandMax).optional(),
  "ustId": zod.string().max(getRechnungDebitorenIdKandidatenResponseUstIdMax).optional(),
  "iban": zod.string().max(getRechnungDebitorenIdKandidatenResponseIbanMax).optional(),
  "email": zod.string().max(getRechnungDebitorenIdKandidatenResponseEmailMax).optional(),
  "status": zod.string().optional(),
  "goldenDebitorId": zod.number().optional()
})
export const GetRechnungDebitorenIdKandidatenResponse = zod.array(GetRechnungDebitorenIdKandidatenResponseItem)

/**
 * @summary Rechnungslauf
 */
export const postRechnungLaeufeBodySchuljahrRegExp = new RegExp('^\\d{4}/\\d{4}$');
export const postRechnungLaeufeBodyHalbjahrMax = 2;



export const PostRechnungLaeufeBody = zod.object({
  "schuljahr": zod.string().regex(postRechnungLaeufeBodySchuljahrRegExp),
  "halbjahr": zod.number().min(1).max(postRechnungLaeufeBodyHalbjahrMax)
})

export const PostRechnungLaeufeResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Hochschul Lauf
 */
export const postRechnungLaeufeHochschuleBodySemesterRegExp = new RegExp('^(WS|SS)\\d{4}$');


export const PostRechnungLaeufeHochschuleBody = zod.object({
  "semester": zod.string().regex(postRechnungLaeufeHochschuleBodySemesterRegExp)
})

export const PostRechnungLaeufeHochschuleResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Bestellung Uebernehmen
 */
export const postRechnungQuellenBestellungBodyQuelleMax = 40;


export const postRechnungQuellenBestellungBodyQuelleRegExp = new RegExp('\\S');
export const postRechnungQuellenBestellungBodyExterneIdMax = 64;


export const postRechnungQuellenBestellungBodyExterneIdRegExp = new RegExp('\\S');
export const postRechnungQuellenBestellungBodyDebitorNameMax = 200;


export const postRechnungQuellenBestellungBodyDebitorNameRegExp = new RegExp('\\S');
export const postRechnungQuellenBestellungBodyDebitorStrasseMax = 200;

export const postRechnungQuellenBestellungBodyDebitorPlzMax = 10;

export const postRechnungQuellenBestellungBodyDebitorOrtMax = 120;

export const postRechnungQuellenBestellungBodyDebitorLandMax = 2;

export const postRechnungQuellenBestellungBodyDebitorUstIdMax = 20;

export const postRechnungQuellenBestellungBodyDebitorIbanMax = 34;

export const postRechnungQuellenBestellungBodyDebitorEmailMax = 200;

export const postRechnungQuellenBestellungBodyPositionenItemBeschreibungMax = 300;


export const postRechnungQuellenBestellungBodyPositionenItemBeschreibungRegExp = new RegExp('\\S');

export const postRechnungQuellenBestellungBodyPositionenItemSteuersatzMin = 0;




export const PostRechnungQuellenBestellungBody = zod.object({
  "quelle": zod.string().max(postRechnungQuellenBestellungBodyQuelleMax).regex(postRechnungQuellenBestellungBodyQuelleRegExp),
  "externeId": zod.string().max(postRechnungQuellenBestellungBodyExterneIdMax).regex(postRechnungQuellenBestellungBodyExterneIdRegExp),
  "zahlungsart": zod.enum(['KARTE', 'RECHNUNG', 'LASTSCHRIFT']),
  "debitor": zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']),
  "rolle": zod.enum(['FIRMA', 'PRIVAT']),
  "name": zod.string().max(postRechnungQuellenBestellungBodyDebitorNameMax).regex(postRechnungQuellenBestellungBodyDebitorNameRegExp),
  "strasse": zod.string().max(postRechnungQuellenBestellungBodyDebitorStrasseMax).optional(),
  "plz": zod.string().max(postRechnungQuellenBestellungBodyDebitorPlzMax).optional(),
  "ort": zod.string().max(postRechnungQuellenBestellungBodyDebitorOrtMax).optional(),
  "land": zod.string().max(postRechnungQuellenBestellungBodyDebitorLandMax).optional(),
  "ustId": zod.string().max(postRechnungQuellenBestellungBodyDebitorUstIdMax).optional(),
  "iban": zod.string().max(postRechnungQuellenBestellungBodyDebitorIbanMax).optional(),
  "email": zod.string().max(postRechnungQuellenBestellungBodyDebitorEmailMax).optional()
}),
  "positionen": zod.array(zod.object({
  "beschreibung": zod.string().max(postRechnungQuellenBestellungBodyPositionenItemBeschreibungMax).regex(postRechnungQuellenBestellungBodyPositionenItemBeschreibungRegExp),
  "betragCent": zod.number().min(1).optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']),
  "steuersatz": zod.number().min(postRechnungQuellenBestellungBodyPositionenItemSteuersatzMin).optional()
})).min(1)
})

export const PostRechnungQuellenBestellungResponse = zod.unknown()

/**
 * @summary List Rechnungen
 */
export const GetRechnungRechnungenQueryParams = zod.object({
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional()
})

export const GetRechnungRechnungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})
export const GetRechnungRechnungenResponse = zod.array(GetRechnungRechnungenResponseItem)

/**
 * @summary Erstelle Sonderrechnung
 */
export const PostRechnungRechnungenBody = zod.object({
  "debitorId": zod.number(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "zahlungszielTage": zod.number().optional()
})

export const PostRechnungRechnungenResponse = zod.unknown()

/**
 * @summary Get Rechnung
 */
export const GetRechnungRechnungenIdParams = zod.object({
  "id": zod.number()
})

export const GetRechnungRechnungenIdResponse = zod.unknown()

/**
 * @summary Ausstellen
 */
export const PostRechnungRechnungenIdAusstellenParams = zod.object({
  "id": zod.number()
})

export const PostRechnungRechnungenIdAusstellenResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Bezahlen
 */
export const PostRechnungRechnungenIdBezahlenParams = zod.object({
  "id": zod.number()
})

export const PostRechnungRechnungenIdBezahlenResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Gutschrift
 */
export const PostRechnungRechnungenIdGutschriftParams = zod.object({
  "id": zod.number()
})

export const postRechnungRechnungenIdGutschriftBodyGrundMax = 200;

export const postRechnungRechnungenIdGutschriftBodyPositionenItemTeilnehmerNameMax = 200;

export const postRechnungRechnungenIdGutschriftBodyPositionenItemBeschreibungMax = 300;


export const postRechnungRechnungenIdGutschriftBodyPositionenItemBeschreibungRegExp = new RegExp('\\S');
export const postRechnungRechnungenIdGutschriftBodyPositionenItemBefreiungsgrundMax = 200;




export const PostRechnungRechnungenIdGutschriftBody = zod.object({
  "grund": zod.string().max(postRechnungRechnungenIdGutschriftBodyGrundMax).optional(),
  "positionen": zod.array(zod.object({
  "teilnehmerName": zod.string().max(postRechnungRechnungenIdGutschriftBodyPositionenItemTeilnehmerNameMax).optional(),
  "beschreibung": zod.string().max(postRechnungRechnungenIdGutschriftBodyPositionenItemBeschreibungMax).regex(postRechnungRechnungenIdGutschriftBodyPositionenItemBeschreibungRegExp),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().max(postRechnungRechnungenIdGutschriftBodyPositionenItemBefreiungsgrundMax).optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE'])
})).min(1)
})

export const PostRechnungRechnungenIdGutschriftResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Nachberechnung
 */
export const PostRechnungRechnungenIdNachberechnungParams = zod.object({
  "id": zod.number()
})

export const postRechnungRechnungenIdNachberechnungBodyGrundMax = 200;

export const postRechnungRechnungenIdNachberechnungBodyPositionenItemTeilnehmerNameMax = 200;

export const postRechnungRechnungenIdNachberechnungBodyPositionenItemBeschreibungMax = 300;


export const postRechnungRechnungenIdNachberechnungBodyPositionenItemBeschreibungRegExp = new RegExp('\\S');
export const postRechnungRechnungenIdNachberechnungBodyPositionenItemBefreiungsgrundMax = 200;




export const PostRechnungRechnungenIdNachberechnungBody = zod.object({
  "grund": zod.string().max(postRechnungRechnungenIdNachberechnungBodyGrundMax).optional(),
  "positionen": zod.array(zod.object({
  "teilnehmerName": zod.string().max(postRechnungRechnungenIdNachberechnungBodyPositionenItemTeilnehmerNameMax).optional(),
  "beschreibung": zod.string().max(postRechnungRechnungenIdNachberechnungBodyPositionenItemBeschreibungMax).regex(postRechnungRechnungenIdNachberechnungBodyPositionenItemBeschreibungRegExp),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().max(postRechnungRechnungenIdNachberechnungBodyPositionenItemBefreiungsgrundMax).optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE'])
})).min(1)
})

export const PostRechnungRechnungenIdNachberechnungResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Add Position
 */
export const PostRechnungRechnungenIdPositionenParams = zod.object({
  "id": zod.number()
})

export const postRechnungRechnungenIdPositionenBodyTeilnehmerNameMax = 200;

export const postRechnungRechnungenIdPositionenBodyBeschreibungMax = 300;


export const postRechnungRechnungenIdPositionenBodyBeschreibungRegExp = new RegExp('\\S');
export const postRechnungRechnungenIdPositionenBodyBefreiungsgrundMax = 200;



export const PostRechnungRechnungenIdPositionenBody = zod.object({
  "teilnehmerName": zod.string().max(postRechnungRechnungenIdPositionenBodyTeilnehmerNameMax).optional(),
  "beschreibung": zod.string().max(postRechnungRechnungenIdPositionenBodyBeschreibungMax).regex(postRechnungRechnungenIdPositionenBodyBeschreibungRegExp),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().max(postRechnungRechnungenIdPositionenBodyBefreiungsgrundMax).optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE'])
})

export const PostRechnungRechnungenIdPositionenResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Storno
 */
export const PostRechnungRechnungenIdStornoParams = zod.object({
  "id": zod.number()
})

export const PostRechnungRechnungenIdStornoResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Versenden
 */
export const PostRechnungRechnungenIdVersendenParams = zod.object({
  "id": zod.number()
})

export const PostRechnungRechnungenIdVersendenResponse = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "nummer": zod.string().optional(),
  "debitorId": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "originalRechnungId": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.enum(['NICHT_VERSENDET', 'VERSENDET', 'FEHLGESCHLAGEN']).optional(),
  "versendetAm": zod.string().datetime({"offset":true}).optional(),
  "versendetAn": zod.string().optional(),
  "bezahltAm": zod.string().date().optional(),
  "zahlbetragCent": zod.number().optional(),
  "zahlungsReferenz": zod.string().optional(),
  "positionen": zod.array(zod.object({
  "id": zod.number().optional(),
  "teilnehmerName": zod.string().optional(),
  "beschreibung": zod.string().optional(),
  "menge": zod.number().optional(),
  "einzelbetragCent": zod.number().optional(),
  "betragCent": zod.number().optional(),
  "steuerfall": zod.enum(['BEFREIT', 'STANDARD', 'ERMAESSIGT']).optional(),
  "steuersatz": zod.number().optional(),
  "befreiungsgrund": zod.string().optional(),
  "leistungsart": zod.enum(['UNTERRICHT', 'UEBERNACHTUNG', 'KORREKTUR', 'SONSTIGE']).optional(),
  "herkunft": zod.string().optional()
})).optional()
})

/**
 * @summary Zugferd
 */
export const GetRechnungRechnungenIdZugferdParams = zod.object({
  "id": zod.number()
})

export const GetRechnungRechnungenIdZugferdResponse = zod.unknown()

