/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  MeinTrainingView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Meine Trainings
 */
export const getLmsPortalTrainings = (

 ) => {
      return http<MeinTrainingView[]>(
      {url: `/lms/portal/trainings`, method: 'GET'
    },
      );
    }
  export type GetLmsPortalTrainingsResult = NonNullable<Awaited<ReturnType<typeof getLmsPortalTrainings>>>
