/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Aktivitaet Anlegen
 */
export const postCrmAktivitaetenBodyTypCodeRegExp = new RegExp('\\S');
export const postCrmAktivitaetenBodyBetreffRegExp = new RegExp('\\S');


export const PostCrmAktivitaetenBody = zod.object({
  "typCode": zod.string().regex(postCrmAktivitaetenBodyTypCodeRegExp),
  "richtung": zod.string().optional(),
  "betreff": zod.string().regex(postCrmAktivitaetenBodyBetreffRegExp),
  "inhaltHtml": zod.string().optional(),
  "personId": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "dauerMinuten": zod.number().optional()
})

export const PostCrmAktivitaetenResponse = zod.unknown()

/**
 * @summary Dubletten Pruefung
 */
export const postCrmDublettenPruefungBodyArtRegExp = new RegExp('\\S');


export const PostCrmDublettenPruefungBody = zod.object({
  "art": zod.string().regex(postCrmDublettenPruefungBodyArtRegExp),
  "vorname": zod.string().optional(),
  "nachname": zod.string().optional(),
  "titel": zod.string().optional(),
  "name": zod.string().optional(),
  "ustId": zod.string().optional()
})

export const PostCrmDublettenPruefungResponseItem = zod.object({
  "art": zod.string().optional(),
  "id": zod.number().optional(),
  "bezeichnung": zod.string().optional(),
  "ort": zod.string().optional(),
  "aehnlichkeit": zod.number().optional(),
  "einschaetzung": zod.string().optional(),
  "begruendung": zod.string().optional()
})
export const PostCrmDublettenPruefungResponse = zod.array(PostCrmDublettenPruefungResponseItem)

/**
 * @summary Einwilligung Anlegen
 */
export const postCrmEinwilligungenBodyKanalRegExp = new RegExp('\\S');
export const postCrmEinwilligungenBodyZweckRegExp = new RegExp('\\S');


export const PostCrmEinwilligungenBody = zod.object({
  "personId": zod.number(),
  "organisationId": zod.number().optional(),
  "kanal": zod.string().regex(postCrmEinwilligungenBodyKanalRegExp),
  "zweck": zod.string().regex(postCrmEinwilligungenBodyZweckRegExp),
  "rechtsgrundlage": zod.string().optional(),
  "quelleCode": zod.string().optional()
})

export const PostCrmEinwilligungenResponse = zod.unknown()

/**
 * @summary Einwilligung Erteilen
 */
export const PostCrmEinwilligungenIdErteilenParams = zod.object({
  "id": zod.number()
})

export const PostCrmEinwilligungenIdErteilenResponse = zod.object({
  "id": zod.number().optional(),
  "kanal": zod.string().optional(),
  "zweck": zod.string().optional(),
  "status": zod.string().optional(),
  "rechtsgrundlage": zod.string().optional(),
  "quelleCode": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "ausstehendSeit": zod.string().datetime({"offset":true}).optional(),
  "erteiltAm": zod.string().datetime({"offset":true}).optional(),
  "widerrufenAm": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Einwilligung Widerrufen
 */
export const PostCrmEinwilligungenIdWiderrufenParams = zod.object({
  "id": zod.number()
})

export const PostCrmEinwilligungenIdWiderrufenResponse = zod.object({
  "id": zod.number().optional(),
  "kanal": zod.string().optional(),
  "zweck": zod.string().optional(),
  "status": zod.string().optional(),
  "rechtsgrundlage": zod.string().optional(),
  "quelleCode": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "ausstehendSeit": zod.string().datetime({"offset":true}).optional(),
  "erteiltAm": zod.string().datetime({"offset":true}).optional(),
  "widerrufenAm": zod.string().datetime({"offset":true}).optional()
})

/**
 * @summary Kontaktpunkt Anlegen
 */
export const postCrmKontaktpunkteBodyTypRegExp = new RegExp('\\S');


export const PostCrmKontaktpunkteBody = zod.object({
  "typ": zod.string().regex(postCrmKontaktpunkteBodyTypRegExp),
  "personId": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "mitgliedschaftId": zod.number().optional(),
  "label": zod.string().optional(),
  "primaer": zod.boolean().optional(),
  "email": zod.string().optional(),
  "nummerE164": zod.string().optional(),
  "nummerAnzeige": zod.string().optional(),
  "telefonart": zod.string().optional(),
  "strasse": zod.string().optional(),
  "hausnummer": zod.string().optional(),
  "adresszusatz": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "region": zod.string().optional(),
  "landCode": zod.string().optional(),
  "auslandsblock": zod.string().optional()
})

export const PostCrmKontaktpunkteResponse = zod.unknown()

/**
 * @summary Kontaktpunkt Loeschen
 */
export const DeleteCrmKontaktpunkteIdParams = zod.object({
  "id": zod.number()
})

export const DeleteCrmKontaktpunkteIdResponse = zod.unknown()

/**
 * @summary Kontaktpunkt Aendern
 */
export const PutCrmKontaktpunkteIdParams = zod.object({
  "id": zod.number()
})

export const putCrmKontaktpunkteIdBodyTypRegExp = new RegExp('\\S');


export const PutCrmKontaktpunkteIdBody = zod.object({
  "typ": zod.string().regex(putCrmKontaktpunkteIdBodyTypRegExp),
  "personId": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "mitgliedschaftId": zod.number().optional(),
  "label": zod.string().optional(),
  "primaer": zod.boolean().optional(),
  "email": zod.string().optional(),
  "nummerE164": zod.string().optional(),
  "nummerAnzeige": zod.string().optional(),
  "telefonart": zod.string().optional(),
  "strasse": zod.string().optional(),
  "hausnummer": zod.string().optional(),
  "adresszusatz": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "region": zod.string().optional(),
  "landCode": zod.string().optional(),
  "auslandsblock": zod.string().optional()
})

export const PutCrmKontaktpunkteIdResponse = zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "label": zod.string().optional(),
  "primaer": zod.boolean().optional(),
  "status": zod.string().optional(),
  "email": zod.string().optional(),
  "nummerAnzeige": zod.string().optional(),
  "telefonart": zod.string().optional(),
  "strasse": zod.string().optional(),
  "hausnummer": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "region": zod.string().optional(),
  "landCode": zod.string().optional()
})

/**
 * @summary Lookups
 */
export const GetCrmLookupsKategorieParams = zod.object({
  "kategorie": zod.string()
})

export const GetCrmLookupsKategorieResponseItem = zod.object({
  "code": zod.string().optional(),
  "bezeichnung": zod.string().optional()
})
export const GetCrmLookupsKategorieResponse = zod.array(GetCrmLookupsKategorieResponseItem)

/**
 * @summary Mitgliedschaft Aendern
 */
export const PutCrmMitgliedschaftenIdParams = zod.object({
  "id": zod.number()
})

export const putCrmMitgliedschaftenIdBodyRolleCodeRegExp = new RegExp('\\S');


export const PutCrmMitgliedschaftenIdBody = zod.object({
  "rolleCode": zod.string().regex(putCrmMitgliedschaftenIdBodyRolleCodeRegExp),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})

export const PutCrmMitgliedschaftenIdResponse = zod.object({
  "id": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolleCode": zod.string().optional(),
  "rolle": zod.string().optional(),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})

/**
 * @summary Ausscheiden
 */
export const PostCrmMitgliedschaftenIdAusscheidenParams = zod.object({
  "id": zod.number()
})

export const PostCrmMitgliedschaftenIdAusscheidenResponse = zod.object({
  "id": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolleCode": zod.string().optional(),
  "rolle": zod.string().optional(),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})

/**
 * @summary Organisationen
 */
export const getCrmOrganisationenQueryPageDefault = 0;
export const getCrmOrganisationenQuerySizeDefault = 20;

export const GetCrmOrganisationenQueryParams = zod.object({
  "page": zod.number().default(getCrmOrganisationenQueryPageDefault),
  "q": zod.string().optional(),
  "size": zod.number().default(getCrmOrganisationenQuerySizeDefault)
})

export const GetCrmOrganisationenResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "ort": zod.string().optional(),
  "ustId": zod.string().optional(),
  "status": zod.string().optional()
})).optional(),
  "total": zod.number().optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

/**
 * @summary Organisation Anlegen
 */
export const postCrmOrganisationenBodyNameRegExp = new RegExp('\\S');


export const PostCrmOrganisationenBody = zod.object({
  "name": zod.string().regex(postCrmOrganisationenBodyNameRegExp),
  "rechtsform": zod.string().optional(),
  "handelsregisternummer": zod.string().optional(),
  "registergericht": zod.string().optional(),
  "brancheCode": zod.string().optional(),
  "website": zod.string().optional(),
  "ustId": zod.string().optional(),
  "uebergeordneteId": zod.number().optional(),
  "bestandsgroesse": zod.number().optional(),
  "gewerbeerlaubnis": zod.string().optional(),
  "gewerbeerlaubnisBehoerde": zod.string().optional(),
  "gewerbeerlaubnisDatum": zod.string().date().optional(),
  "ausbildungsbetrieb": zod.boolean().optional(),
  "ihkKammerCode": zod.string().optional(),
  "leadQuelleCode": zod.string().optional(),
  "unternehmenstypCodes": zod.array(zod.string()).optional(),
  "schwerpunktCodes": zod.array(zod.string()).optional(),
  "verbandCodes": zod.array(zod.string()).optional()
})

export const PostCrmOrganisationenResponse = zod.unknown()

/**
 * @summary Organisation Aendern
 */
export const PutCrmOrganisationenIdParams = zod.object({
  "id": zod.number()
})

export const putCrmOrganisationenIdBodyNameRegExp = new RegExp('\\S');


export const PutCrmOrganisationenIdBody = zod.object({
  "name": zod.string().regex(putCrmOrganisationenIdBodyNameRegExp),
  "rechtsform": zod.string().optional(),
  "handelsregisternummer": zod.string().optional(),
  "registergericht": zod.string().optional(),
  "brancheCode": zod.string().optional(),
  "website": zod.string().optional(),
  "ustId": zod.string().optional(),
  "uebergeordneteId": zod.number().optional(),
  "bestandsgroesse": zod.number().optional(),
  "gewerbeerlaubnis": zod.string().optional(),
  "gewerbeerlaubnisBehoerde": zod.string().optional(),
  "gewerbeerlaubnisDatum": zod.string().date().optional(),
  "ausbildungsbetrieb": zod.boolean().optional(),
  "ihkKammerCode": zod.string().optional(),
  "leadQuelleCode": zod.string().optional(),
  "unternehmenstypCodes": zod.array(zod.string()).optional(),
  "schwerpunktCodes": zod.array(zod.string()).optional(),
  "verbandCodes": zod.array(zod.string()).optional()
})

export const PutCrmOrganisationenIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "rechtsform": zod.string().optional(),
  "handelsregisternummer": zod.string().optional(),
  "registergericht": zod.string().optional(),
  "brancheCode": zod.string().optional(),
  "website": zod.string().optional(),
  "ustId": zod.string().optional(),
  "uebergeordneteId": zod.number().optional(),
  "bestandsgroesse": zod.number().optional(),
  "gewerbeerlaubnis": zod.string().optional(),
  "ausbildungsbetrieb": zod.boolean().optional(),
  "ihkKammerCode": zod.string().optional(),
  "unternehmenstypen": zod.array(zod.string()).optional(),
  "taetigkeitsschwerpunkte": zod.array(zod.string()).optional(),
  "verbaende": zod.array(zod.string()).optional(),
  "strasse": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "status": zod.string().optional(),
  "mitglieder": zod.array(zod.object({
  "mitgliedschaftId": zod.number().optional(),
  "personId": zod.number().optional(),
  "person": zod.string().optional(),
  "rolle": zod.string().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "gueltigBis": zod.string().date().optional()
})).optional()
})

/**
 * @summary Organisation
 */
export const GetCrmOrganisationenIdParams = zod.object({
  "id": zod.number()
})

export const GetCrmOrganisationenIdResponse = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional(),
  "rechtsform": zod.string().optional(),
  "handelsregisternummer": zod.string().optional(),
  "registergericht": zod.string().optional(),
  "brancheCode": zod.string().optional(),
  "website": zod.string().optional(),
  "ustId": zod.string().optional(),
  "uebergeordneteId": zod.number().optional(),
  "bestandsgroesse": zod.number().optional(),
  "gewerbeerlaubnis": zod.string().optional(),
  "ausbildungsbetrieb": zod.boolean().optional(),
  "ihkKammerCode": zod.string().optional(),
  "unternehmenstypen": zod.array(zod.string()).optional(),
  "taetigkeitsschwerpunkte": zod.array(zod.string()).optional(),
  "verbaende": zod.array(zod.string()).optional(),
  "strasse": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "status": zod.string().optional(),
  "mitglieder": zod.array(zod.object({
  "mitgliedschaftId": zod.number().optional(),
  "personId": zod.number().optional(),
  "person": zod.string().optional(),
  "rolle": zod.string().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "gueltigBis": zod.string().date().optional()
})).optional()
})

/**
 * @summary Organisation Aktivitaeten
 */
export const GetCrmOrganisationenIdAktivitaetenParams = zod.object({
  "id": zod.number()
})

export const GetCrmOrganisationenIdAktivitaetenResponseItem = zod.object({
  "id": zod.number().optional(),
  "typCode": zod.string().optional(),
  "typ": zod.string().optional(),
  "richtung": zod.string().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "personId": zod.number().optional(),
  "person": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional(),
  "dauerMinuten": zod.number().optional()
})
export const GetCrmOrganisationenIdAktivitaetenResponse = zod.array(GetCrmOrganisationenIdAktivitaetenResponseItem)

/**
 * @summary Organisation Uebersicht
 */
export const GetCrmOrganisationenIdUebersichtParams = zod.object({
  "id": zod.number()
})

export const GetCrmOrganisationenIdUebersichtResponse = zod.object({
  "anmeldungen": zod.array(zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "teilnehmerName": zod.string().optional(),
  "status": zod.string().optional(),
  "zeitraum": zod.string().optional(),
  "betragCent": zod.number().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "kontextOrganisation": zod.string().optional()
})).optional(),
  "rechnungen": zod.array(zod.object({
  "id": zod.number().optional(),
  "nummer": zod.string().optional(),
  "bereich": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "status": zod.string().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.string().optional()
})).optional()
})

/**
 * @summary Personen
 */
export const getCrmPersonenQueryPageDefault = 0;
export const getCrmPersonenQuerySizeDefault = 20;

export const GetCrmPersonenQueryParams = zod.object({
  "page": zod.number().default(getCrmPersonenQueryPageDefault),
  "q": zod.string().optional(),
  "size": zod.number().default(getCrmPersonenQuerySizeDefault)
})

export const GetCrmPersonenResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number().optional(),
  "anzeigeName": zod.string().optional(),
  "ort": zod.string().optional(),
  "hauptFirma": zod.string().optional(),
  "status": zod.string().optional()
})).optional(),
  "total": zod.number().optional(),
  "page": zod.number().optional(),
  "size": zod.number().optional()
})

/**
 * @summary Person Anlegen
 */
export const postCrmPersonenBodyVornameRegExp = new RegExp('\\S');
export const postCrmPersonenBodyNachnameRegExp = new RegExp('\\S');


export const PostCrmPersonenBody = zod.object({
  "vorname": zod.string().regex(postCrmPersonenBodyVornameRegExp),
  "nachname": zod.string().regex(postCrmPersonenBodyNachnameRegExp),
  "geschlecht": zod.string().optional(),
  "titel": zod.string().optional(),
  "geburtsdatum": zod.string().date().optional(),
  "geburtsort": zod.string().optional(),
  "geburtslandCode": zod.string().optional(),
  "staatsangehoerigkeit1Code": zod.string().optional(),
  "staatsangehoerigkeit2Code": zod.string().optional(),
  "korrespondenzspracheCode": zod.string().optional(),
  "werbesperre": zod.boolean().optional(),
  "auskunftssperre": zod.boolean().optional(),
  "leadQuelleCode": zod.string().optional()
})

export const PostCrmPersonenResponse = zod.unknown()

/**
 * @summary Person Aendern
 */
export const PutCrmPersonenIdParams = zod.object({
  "id": zod.number()
})

export const putCrmPersonenIdBodyVornameRegExp = new RegExp('\\S');
export const putCrmPersonenIdBodyNachnameRegExp = new RegExp('\\S');


export const PutCrmPersonenIdBody = zod.object({
  "vorname": zod.string().regex(putCrmPersonenIdBodyVornameRegExp),
  "nachname": zod.string().regex(putCrmPersonenIdBodyNachnameRegExp),
  "geschlecht": zod.string().optional(),
  "titel": zod.string().optional(),
  "geburtsdatum": zod.string().date().optional(),
  "geburtsort": zod.string().optional(),
  "geburtslandCode": zod.string().optional(),
  "staatsangehoerigkeit1Code": zod.string().optional(),
  "staatsangehoerigkeit2Code": zod.string().optional(),
  "korrespondenzspracheCode": zod.string().optional(),
  "werbesperre": zod.boolean().optional(),
  "auskunftssperre": zod.boolean().optional(),
  "leadQuelleCode": zod.string().optional()
})

export const PutCrmPersonenIdResponse = zod.object({
  "id": zod.number().optional(),
  "vorname": zod.string().optional(),
  "nachname": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "geschlecht": zod.string().optional(),
  "titel": zod.string().optional(),
  "briefanrede": zod.string().optional(),
  "geburtsdatum": zod.string().date().optional(),
  "geburtsort": zod.string().optional(),
  "geburtslandCode": zod.string().optional(),
  "korrespondenzspracheCode": zod.string().optional(),
  "werbesperre": zod.boolean().optional(),
  "auskunftssperre": zod.boolean().optional(),
  "status": zod.string().optional(),
  "loeschStatus": zod.string().optional(),
  "emails": zod.array(zod.string()).optional(),
  "kontaktpunkte": zod.array(zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "label": zod.string().optional(),
  "primaer": zod.boolean().optional(),
  "status": zod.string().optional(),
  "email": zod.string().optional(),
  "nummerAnzeige": zod.string().optional(),
  "telefonart": zod.string().optional(),
  "strasse": zod.string().optional(),
  "hausnummer": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "region": zod.string().optional(),
  "landCode": zod.string().optional()
})).optional(),
  "mitgliedschaften": zod.array(zod.object({
  "id": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolleCode": zod.string().optional(),
  "rolle": zod.string().optional(),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})).optional()
})

/**
 * @summary Person
 */
export const GetCrmPersonenIdParams = zod.object({
  "id": zod.number()
})

export const GetCrmPersonenIdResponse = zod.object({
  "id": zod.number().optional(),
  "vorname": zod.string().optional(),
  "nachname": zod.string().optional(),
  "anzeigeName": zod.string().optional(),
  "geschlecht": zod.string().optional(),
  "titel": zod.string().optional(),
  "briefanrede": zod.string().optional(),
  "geburtsdatum": zod.string().date().optional(),
  "geburtsort": zod.string().optional(),
  "geburtslandCode": zod.string().optional(),
  "korrespondenzspracheCode": zod.string().optional(),
  "werbesperre": zod.boolean().optional(),
  "auskunftssperre": zod.boolean().optional(),
  "status": zod.string().optional(),
  "loeschStatus": zod.string().optional(),
  "emails": zod.array(zod.string()).optional(),
  "kontaktpunkte": zod.array(zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "label": zod.string().optional(),
  "primaer": zod.boolean().optional(),
  "status": zod.string().optional(),
  "email": zod.string().optional(),
  "nummerAnzeige": zod.string().optional(),
  "telefonart": zod.string().optional(),
  "strasse": zod.string().optional(),
  "hausnummer": zod.string().optional(),
  "plz": zod.string().optional(),
  "ort": zod.string().optional(),
  "region": zod.string().optional(),
  "landCode": zod.string().optional()
})).optional(),
  "mitgliedschaften": zod.array(zod.object({
  "id": zod.number().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "rolleCode": zod.string().optional(),
  "rolle": zod.string().optional(),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})).optional()
})

/**
 * @summary Person Aktivitaeten
 */
export const GetCrmPersonenIdAktivitaetenParams = zod.object({
  "id": zod.number()
})

export const GetCrmPersonenIdAktivitaetenResponseItem = zod.object({
  "id": zod.number().optional(),
  "typCode": zod.string().optional(),
  "typ": zod.string().optional(),
  "richtung": zod.string().optional(),
  "betreff": zod.string().optional(),
  "inhaltHtml": zod.string().optional(),
  "personId": zod.number().optional(),
  "person": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "zeitpunkt": zod.string().datetime({"offset":true}).optional(),
  "dauerMinuten": zod.number().optional()
})
export const GetCrmPersonenIdAktivitaetenResponse = zod.array(GetCrmPersonenIdAktivitaetenResponseItem)

/**
 * @summary Person Einwilligungen
 */
export const GetCrmPersonenIdEinwilligungenParams = zod.object({
  "id": zod.number()
})

export const GetCrmPersonenIdEinwilligungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "kanal": zod.string().optional(),
  "zweck": zod.string().optional(),
  "status": zod.string().optional(),
  "rechtsgrundlage": zod.string().optional(),
  "quelleCode": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "organisation": zod.string().optional(),
  "ausstehendSeit": zod.string().datetime({"offset":true}).optional(),
  "erteiltAm": zod.string().datetime({"offset":true}).optional(),
  "widerrufenAm": zod.string().datetime({"offset":true}).optional()
})
export const GetCrmPersonenIdEinwilligungenResponse = zod.array(GetCrmPersonenIdEinwilligungenResponseItem)

/**
 * @summary Person Uebersicht
 */
export const GetCrmPersonenIdUebersichtParams = zod.object({
  "id": zod.number()
})

export const GetCrmPersonenIdUebersichtResponse = zod.object({
  "anmeldungen": zod.array(zod.object({
  "id": zod.number().optional(),
  "typ": zod.string().optional(),
  "teilnehmerName": zod.string().optional(),
  "status": zod.string().optional(),
  "zeitraum": zod.string().optional(),
  "betragCent": zod.number().optional(),
  "kontextOrganisationId": zod.number().optional(),
  "kontextOrganisation": zod.string().optional()
})).optional(),
  "rechnungen": zod.array(zod.object({
  "id": zod.number().optional(),
  "nummer": zod.string().optional(),
  "bereich": zod.string().optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "status": zod.string().optional(),
  "summeCent": zod.number().optional(),
  "versandStatus": zod.string().optional()
})).optional()
})

/**
 * @summary Person Weiterbildung
 */
export const GetCrmPersonenIdWeiterbildungParams = zod.object({
  "id": zod.number()
})

export const GetCrmPersonenIdWeiterbildungResponse = zod.object({
  "zeitraumVon": zod.string().date().optional(),
  "zeitraumBis": zod.string().date().optional(),
  "soll": zod.number().optional(),
  "summe": zod.number().optional(),
  "rest": zod.number().optional(),
  "erfuellt": zod.boolean().optional(),
  "ampel": zod.string().optional(),
  "nachweise": zod.array(zod.object({
  "id": zod.number().optional(),
  "titel": zod.string().optional(),
  "anbieter": zod.string().optional(),
  "stunden": zod.number().optional(),
  "datum": zod.string().date().optional(),
  "extern": zod.boolean().optional()
})).optional()
})

/**
 * @summary Mitgliedschaft Anlegen
 */
export const PostCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenParams = zod.object({
  "orgId": zod.number(),
  "personId": zod.number()
})

export const postCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenBodyRolleCodeRegExp = new RegExp('\\S');


export const PostCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenBody = zod.object({
  "rolleCode": zod.string().regex(postCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenBodyRolleCodeRegExp),
  "position": zod.string().optional(),
  "abteilung": zod.string().optional(),
  "hauptzugehoerigkeit": zod.boolean().optional(),
  "hauptansprechpartner": zod.boolean().optional(),
  "buchungsberechtigt": zod.boolean().optional(),
  "rechnungsempfaenger": zod.boolean().optional(),
  "gueltigVon": zod.string().date().optional(),
  "gueltigBis": zod.string().date().optional()
})

export const PostCrmPersonenPersonIdOrganisationenOrgIdMitgliedschaftenResponse = zod.unknown()

/**
 * @summary Suche
 */
export const GetCrmSucheQueryParams = zod.object({
  "q": zod.string().optional()
})

export const GetCrmSucheResponseItem = zod.object({
  "art": zod.string().optional(),
  "id": zod.number().optional(),
  "titel": zod.string().optional(),
  "untertitel": zod.string().optional()
})
export const GetCrmSucheResponse = zod.array(GetCrmSucheResponseItem)

/**
 * @summary Weiterbildung Anlegen
 */
export const postCrmWeiterbildungBodyTitelRegExp = new RegExp('\\S');


export const PostCrmWeiterbildungBody = zod.object({
  "personId": zod.number(),
  "titel": zod.string().regex(postCrmWeiterbildungBodyTitelRegExp),
  "anbieter": zod.string().optional(),
  "stunden": zod.number(),
  "datum": zod.string().date(),
  "extern": zod.boolean().optional()
})

export const PostCrmWeiterbildungResponse = zod.unknown()

/**
 * @summary Weiterbildung Loeschen
 */
export const DeleteCrmWeiterbildungIdParams = zod.object({
  "id": zod.number()
})

export const DeleteCrmWeiterbildungIdResponse = zod.unknown()

