/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AzubiAnmeldungDto
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Vertrag Bestaetigen
 */
export const postPartyPortalAnmeldungenIdVertragBestaetigen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/party/portal/anmeldungen/${id}/vertrag-bestaetigen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Azubi Anmelden
 */
export const postPartyPortalAzubiAnmeldung = (
    azubiAnmeldungDto: AzubiAnmeldungDto,
 ) => {
      return http<unknown>(
      {url: `/party/portal/azubi-anmeldung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: azubiAnmeldungDto
    },
      );
    }
  export type PostPartyPortalAnmeldungenIdVertragBestaetigenResult = NonNullable<Awaited<ReturnType<typeof postPartyPortalAnmeldungenIdVertragBestaetigen>>>
export type PostPartyPortalAzubiAnmeldungResult = NonNullable<Awaited<ReturnType<typeof postPartyPortalAzubiAnmeldung>>>
