/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  HubSpotDeal,
  IngestionResult,
  Stats
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Review Queue
 */
export const getIngestReview = (

 ) => {
      return http<HubSpotDeal[]>(
      {url: `/ingest/review`, method: 'GET'
    },
      );
    }
  /**
 * @summary Run
 */
export const postIngestRun = (

 ) => {
      return http<IngestionResult>(
      {url: `/ingest/run`, method: 'POST'
    },
      );
    }
  /**
 * @summary Stats
 */
export const getIngestStats = (

 ) => {
      return http<Stats>(
      {url: `/ingest/stats`, method: 'GET'
    },
      );
    }
  export type GetIngestReviewResult = NonNullable<Awaited<ReturnType<typeof getIngestReview>>>
export type PostIngestRunResult = NonNullable<Awaited<ReturnType<typeof postIngestRun>>>
export type GetIngestStatsResult = NonNullable<Awaited<ReturnType<typeof getIngestStats>>>
