/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  AuftragView,
  GetOutboxParams
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Liste
 */
export const getOutbox = (
    params?: GetOutboxParams,
 ) => {
      return http<AuftragView[]>(
      {url: `/outbox`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Dispatch
 */
export const postOutboxDispatch = (

 ) => {
      return http<unknown>(
      {url: `/outbox/dispatch`, method: 'POST'
    },
      );
    }
  /**
 * @summary Neu Versuch
 */
export const postOutboxIdNeuVersuch = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/outbox/${id}/neu-versuch`, method: 'POST'
    },
      );
    }
  export type GetOutboxResult = NonNullable<Awaited<ReturnType<typeof getOutbox>>>
export type PostOutboxDispatchResult = NonNullable<Awaited<ReturnType<typeof postOutboxDispatch>>>
export type PostOutboxIdNeuVersuchResult = NonNullable<Awaited<ReturnType<typeof postOutboxIdNeuVersuch>>>
