/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Auftraege
 */
export const GetHubspotSyncAuftraegeResponseItem = zod.object({
  "id": zod.number().optional(),
  "objektTyp": zod.string().optional(),
  "operation": zod.string().optional(),
  "status": zod.string().optional(),
  "partei": zod.string().optional(),
  "versuche": zod.number().optional(),
  "letzterFehler": zod.string().optional(),
  "erstelltAm": zod.string().datetime({"offset":true}).optional(),
  "erledigtAm": zod.string().datetime({"offset":true}).optional()
})
export const GetHubspotSyncAuftraegeResponse = zod.array(GetHubspotSyncAuftraegeResponseItem)

/**
 * @summary Backfill
 */
export const PostHubspotSyncBackfillResponse = zod.record(zod.string(), zod.number())

/**
 * @summary Company
 */
export const PostHubspotSyncCompaniesOrganisationIdParams = zod.object({
  "organisationId": zod.number()
})

export const PostHubspotSyncCompaniesOrganisationIdResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Consent
 */
export const PostHubspotSyncConsentPersonIdParams = zod.object({
  "personId": zod.number()
})

export const PostHubspotSyncConsentPersonIdResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Contact
 */
export const PostHubspotSyncContactsPersonIdParams = zod.object({
  "personId": zod.number()
})

export const PostHubspotSyncContactsPersonIdResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Erasure
 */
export const PostHubspotSyncErasurePersonIdParams = zod.object({
  "personId": zod.number()
})

export const PostHubspotSyncErasurePersonIdResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Retry
 */
export const PostHubspotSyncRetryAuftragIdParams = zod.object({
  "auftragId": zod.number()
})

export const PostHubspotSyncRetryAuftragIdResponse = zod.record(zod.string(), zod.unknown())

/**
 * @summary Run
 */
export const PostHubspotSyncRunResponse = zod.record(zod.string(), zod.unknown())

