/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  BeratungDto,
  EinstellungView,
  EreignisView,
  Kanal,
  KonversationView,
  NachrichtView,
  PraeferenzDto,
  PraeferenzView,
  PutKommunikationPortalPraeferenzenKanalParams,
  SendenDto,
  UngelesenView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Beratung
 */
export const postKommunikationPortalBeratung = (
    beratungDto: BeratungDto,
 ) => {
      return http<KonversationView>(
      {url: `/kommunikation/portal/beratung`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: beratungDto
    },
      );
    }
  /**
 * @summary Direkt
 */
export const postKommunikationPortalDirekt = (
    sendenDto: SendenDto,
 ) => {
      return http<KonversationView>(
      {url: `/kommunikation/portal/direkt`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendenDto
    },
      );
    }
  /**
 * @summary Setze Einstellungen
 */
export const putKommunikationPortalEinstellungen = (
    einstellungView: EinstellungView,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/einstellungen`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: einstellungView
    },
      );
    }
  /**
 * @summary Einstellungen
 */
export const getKommunikationPortalEinstellungen = (

 ) => {
      return http<EinstellungView>(
      {url: `/kommunikation/portal/einstellungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Ereignisse
 */
export const getKommunikationPortalEreignisse = (

 ) => {
      return http<EreignisView[]>(
      {url: `/kommunikation/portal/ereignisse`, method: 'GET'
    },
      );
    }
  /**
 * @summary Bestaetigen
 */
export const postKommunikationPortalEreignisseIdBestaetigen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/ereignisse/${id}/bestaetigen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Gelesen
 */
export const postKommunikationPortalEreignisseIdGelesen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/ereignisse/${id}/gelesen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Konversationen
 */
export const getKommunikationPortalKonversationen = (

 ) => {
      return http<KonversationView[]>(
      {url: `/kommunikation/portal/konversationen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Konversationen Ungelesen
 */
export const getKommunikationPortalKonversationenUngelesen = (

 ) => {
      return http<UngelesenView>(
      {url: `/kommunikation/portal/konversationen/ungelesen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Konversation Gelesen
 */
export const postKommunikationPortalKonversationenIdGelesen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/konversationen/${id}/gelesen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Nachrichten
 */
export const getKommunikationPortalKonversationenIdNachrichten = (
    id: number,
 ) => {
      return http<NachrichtView[]>(
      {url: `/kommunikation/portal/konversationen/${id}/nachrichten`, method: 'GET'
    },
      );
    }
  /**
 * @summary Antworten
 */
export const postKommunikationPortalKonversationenIdNachrichten = (
    id: number,
    sendenDto: SendenDto,
 ) => {
      return http<NachrichtView>(
      {url: `/kommunikation/portal/konversationen/${id}/nachrichten`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendenDto
    },
      );
    }
  /**
 * @summary Praeferenzen
 */
export const getKommunikationPortalPraeferenzen = (

 ) => {
      return http<PraeferenzView[]>(
      {url: `/kommunikation/portal/praeferenzen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Setze Praeferenz
 */
export const putKommunikationPortalPraeferenzenKanal = (
    kanal: Kanal,
    praeferenzDto: PraeferenzDto,
    params?: PutKommunikationPortalPraeferenzenKanalParams,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/praeferenzen/${kanal}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: praeferenzDto,
        params
    },
      );
    }
  /**
 * @summary Ungelesen
 */
export const getKommunikationPortalUngelesen = (

 ) => {
      return http<UngelesenView>(
      {url: `/kommunikation/portal/ungelesen`, method: 'GET'
    },
      );
    }
  export type PostKommunikationPortalBeratungResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalBeratung>>>
export type PostKommunikationPortalDirektResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalDirekt>>>
export type PutKommunikationPortalEinstellungenResult = NonNullable<Awaited<ReturnType<typeof putKommunikationPortalEinstellungen>>>
export type GetKommunikationPortalEinstellungenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalEinstellungen>>>
export type GetKommunikationPortalEreignisseResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalEreignisse>>>
export type PostKommunikationPortalEreignisseIdBestaetigenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalEreignisseIdBestaetigen>>>
export type PostKommunikationPortalEreignisseIdGelesenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalEreignisseIdGelesen>>>
export type GetKommunikationPortalKonversationenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalKonversationen>>>
export type GetKommunikationPortalKonversationenUngelesenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalKonversationenUngelesen>>>
export type PostKommunikationPortalKonversationenIdGelesenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalKonversationenIdGelesen>>>
export type GetKommunikationPortalKonversationenIdNachrichtenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalKonversationenIdNachrichten>>>
export type PostKommunikationPortalKonversationenIdNachrichtenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalKonversationenIdNachrichten>>>
export type GetKommunikationPortalPraeferenzenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalPraeferenzen>>>
export type PutKommunikationPortalPraeferenzenKanalResult = NonNullable<Awaited<ReturnType<typeof putKommunikationPortalPraeferenzenKanal>>>
export type GetKommunikationPortalUngelesenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalUngelesen>>>
