/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import type {
  EinstellungView,
  EreignisView,
  Kanal,
  PraeferenzDto,
  PraeferenzView,
  PutKommunikationPortalPraeferenzenKanalParams,
  UngelesenView
} from '../../model';

import { http } from '../../http';



  /**
 * @summary Setze Einstellungen
 */
export const putKommunikationPortalEinstellungen = (
    einstellungView: EinstellungView,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/einstellungen`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: einstellungView
    },
      );
    }
  /**
 * @summary Einstellungen
 */
export const getKommunikationPortalEinstellungen = (

 ) => {
      return http<EinstellungView>(
      {url: `/kommunikation/portal/einstellungen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Ereignisse
 */
export const getKommunikationPortalEreignisse = (

 ) => {
      return http<EreignisView[]>(
      {url: `/kommunikation/portal/ereignisse`, method: 'GET'
    },
      );
    }
  /**
 * @summary Bestaetigen
 */
export const postKommunikationPortalEreignisseIdBestaetigen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/ereignisse/${id}/bestaetigen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Gelesen
 */
export const postKommunikationPortalEreignisseIdGelesen = (
    id: number,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/ereignisse/${id}/gelesen`, method: 'POST'
    },
      );
    }
  /**
 * @summary Praeferenzen
 */
export const getKommunikationPortalPraeferenzen = (

 ) => {
      return http<PraeferenzView[]>(
      {url: `/kommunikation/portal/praeferenzen`, method: 'GET'
    },
      );
    }
  /**
 * @summary Setze Praeferenz
 */
export const putKommunikationPortalPraeferenzenKanal = (
    kanal: Kanal,
    praeferenzDto: PraeferenzDto,
    params?: PutKommunikationPortalPraeferenzenKanalParams,
 ) => {
      return http<unknown>(
      {url: `/kommunikation/portal/praeferenzen/${kanal}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: praeferenzDto,
        params
    },
      );
    }
  /**
 * @summary Ungelesen
 */
export const getKommunikationPortalUngelesen = (

 ) => {
      return http<UngelesenView>(
      {url: `/kommunikation/portal/ungelesen`, method: 'GET'
    },
      );
    }
  export type PutKommunikationPortalEinstellungenResult = NonNullable<Awaited<ReturnType<typeof putKommunikationPortalEinstellungen>>>
export type GetKommunikationPortalEinstellungenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalEinstellungen>>>
export type GetKommunikationPortalEreignisseResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalEreignisse>>>
export type PostKommunikationPortalEreignisseIdBestaetigenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalEreignisseIdBestaetigen>>>
export type PostKommunikationPortalEreignisseIdGelesenResult = NonNullable<Awaited<ReturnType<typeof postKommunikationPortalEreignisseIdGelesen>>>
export type GetKommunikationPortalPraeferenzenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalPraeferenzen>>>
export type PutKommunikationPortalPraeferenzenKanalResult = NonNullable<Awaited<ReturnType<typeof putKommunikationPortalPraeferenzenKanal>>>
export type GetKommunikationPortalUngelesenResult = NonNullable<Awaited<ReturnType<typeof getKommunikationPortalUngelesen>>>
