/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary List
 */
export const getLmsKurseResponseCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const getLmsKurseResponseTitelMax = 200;


export const getLmsKurseResponseTitelRegExp = new RegExp('\\S');
export const getLmsKurseResponseKurzbeschreibungMax = 2000;


export const getLmsKurseResponsePreisCentMin = 0;

export const getLmsKurseResponseVendureProductIdMax = 64;



export const GetLmsKurseResponseItem = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "code": zod.string().regex(getLmsKurseResponseCodeRegExp),
  "titel": zod.string().max(getLmsKurseResponseTitelMax).regex(getLmsKurseResponseTitelRegExp),
  "kurzbeschreibung": zod.string().max(getLmsKurseResponseKurzbeschreibungMax).optional(),
  "openolatKey": zod.number().min(1).optional(),
  "scormVersion": zod.enum(['SCORM_12', 'SCORM_2004']).optional(),
  "preisCent": zod.number().min(getLmsKurseResponsePreisCentMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "vendureProductId": zod.string().max(getLmsKurseResponseVendureProductIdMax).optional()
})
export const GetLmsKurseResponse = zod.array(GetLmsKurseResponseItem)

/**
 * @summary Create
 */
export const postLmsKurseBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const postLmsKurseBodyTitelMax = 200;


export const postLmsKurseBodyTitelRegExp = new RegExp('\\S');
export const postLmsKurseBodyKurzbeschreibungMax = 2000;


export const postLmsKurseBodyPreisCentMin = 0;

export const postLmsKurseBodyVendureProductIdMax = 64;



export const PostLmsKurseBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "code": zod.string().regex(postLmsKurseBodyCodeRegExp),
  "titel": zod.string().max(postLmsKurseBodyTitelMax).regex(postLmsKurseBodyTitelRegExp),
  "kurzbeschreibung": zod.string().max(postLmsKurseBodyKurzbeschreibungMax).optional(),
  "openolatKey": zod.number().min(1).optional(),
  "scormVersion": zod.enum(['SCORM_12', 'SCORM_2004']).optional(),
  "preisCent": zod.number().min(postLmsKurseBodyPreisCentMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "vendureProductId": zod.string().max(postLmsKurseBodyVendureProductIdMax).optional()
})

export const PostLmsKurseResponse = zod.unknown()

/**
 * @summary Update
 */
export const PutLmsKurseIdParams = zod.object({
  "id": zod.number()
})

export const putLmsKurseIdBodyCodeRegExp = new RegExp('^[A-Z0-9-]{2,32}$');
export const putLmsKurseIdBodyTitelMax = 200;


export const putLmsKurseIdBodyTitelRegExp = new RegExp('\\S');
export const putLmsKurseIdBodyKurzbeschreibungMax = 2000;


export const putLmsKurseIdBodyPreisCentMin = 0;

export const putLmsKurseIdBodyVendureProductIdMax = 64;



export const PutLmsKurseIdBody = zod.object({
  "id": zod.number().optional(),
  "version": zod.number().optional(),
  "code": zod.string().regex(putLmsKurseIdBodyCodeRegExp),
  "titel": zod.string().max(putLmsKurseIdBodyTitelMax).regex(putLmsKurseIdBodyTitelRegExp),
  "kurzbeschreibung": zod.string().max(putLmsKurseIdBodyKurzbeschreibungMax).optional(),
  "openolatKey": zod.number().min(1).optional(),
  "scormVersion": zod.enum(['SCORM_12', 'SCORM_2004']).optional(),
  "preisCent": zod.number().min(putLmsKurseIdBodyPreisCentMin).optional(),
  "shopVerkauf": zod.boolean().optional(),
  "status": zod.enum(['ENTWURF', 'AKTIV', 'ARCHIVIERT']),
  "vendureProductId": zod.string().max(putLmsKurseIdBodyVendureProductIdMax).optional()
})

export const PutLmsKurseIdResponse = zod.unknown()

/**
 * @summary Get
 */
export const GetLmsKurseIdParams = zod.object({
  "id": zod.number()
})

export const GetLmsKurseIdResponse = zod.unknown()

/**
 * @summary Archive
 */
export const DeleteLmsKurseIdParams = zod.object({
  "id": zod.number()
})

export const DeleteLmsKurseIdResponse = zod.unknown()

/**
 * @summary Veroeffentlichen
 */
export const PostLmsKurseIdVeroeffentlichenParams = zod.object({
  "id": zod.number()
})

export const PostLmsKurseIdVeroeffentlichenResponse = zod.object({
  "id": zod.number().optional(),
  "code": zod.string().optional(),
  "vendureProductId": zod.string().optional(),
  "vendureVariantId": zod.string().optional()
})

