/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * EBZ MDM — Bildungsangebote
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Meine Rechnungen
 */
export const GetPartyPortalRechnungenQueryParams = zod.object({
  "organisationId": zod.number().optional()
})

export const GetPartyPortalRechnungenResponseItem = zod.object({
  "id": zod.number().optional(),
  "nummer": zod.string().optional(),
  "belegart": zod.enum(['RECHNUNG', 'GUTSCHRIFT', 'STORNO', 'NACHBERECHNUNG']).optional(),
  "bereich": zod.enum(['BERUFSSCHULE', 'HOCHSCHULE', 'AKADEMIE', 'SHOP']).optional(),
  "status": zod.enum(['ENTWURF', 'AUSGESTELLT', 'BEZAHLT', 'STORNIERT']).optional(),
  "ausstellungsdatum": zod.string().date().optional(),
  "zahlungszielTage": zod.number().optional(),
  "summeCent": zod.number().optional(),
  "zeitraumBezeichnung": zod.string().optional(),
  "empfaengerName": zod.string().optional()
})
export const GetPartyPortalRechnungenResponse = zod.array(GetPartyPortalRechnungenResponseItem)

/**
 * @summary Zugferd
 */
export const GetPartyPortalRechnungenIdZugferdParams = zod.object({
  "id": zod.number()
})

export const GetPartyPortalRechnungenIdZugferdResponse = zod.unknown()

/**
 * @summary Rechnungs Kontexte
 */
export const GetPartyPortalRechnungsKontexteResponseItem = zod.object({
  "art": zod.string().optional(),
  "organisationId": zod.number().optional(),
  "bezeichnung": zod.string().optional()
})
export const GetPartyPortalRechnungsKontexteResponse = zod.array(GetPartyPortalRechnungsKontexteResponseItem)

